### ISSUE TITLE
make the dependencies optionnal (yaml, xml and syntax highlighting)

### ISSUE THREAD

**Issue by tst2005** [kellyjonbrazil/jc#108]
Hello,

When I discovered `jc` I thought "Wow so many "command to json" parsers ready to use that I don't have time to make by my own".

For me, the main interest of jc is to be able to process text from command line output and get the result on json.
You have dependencies on syntax highlighting, yaml and xml.

In my case, `jc` for now is only available for debian in testing or unstable branches and comes with theses mandatory depedencies.
I hope to be able to get `jc` without dependencies (except python it self, of course).
I can try to contact the debian's jc maitainer to change from mandatory to optional dependencies,
but jc it self should be able to deals with missing dependencies.

I search where dependencies are required.
if I'm not wrong:
- yaml is only used for `jc --yaml`
- xml is only used for `jc --xml`
- pygments is use at the cli.py

Do you think is it possible to make them optionnal ?
- in cli.py Trying to import pygments if it's fail/not available, just disable the color/highlighting stuff ?
- for yaml and xml, try to import, if it's fail then raise an error message ?

`jc` is a beautifull util to parse text from command line to json.
There a plenty other utils to convert yaml to json or xml to json.

I hope to be able to drop the yaml/xml/color stuff to get back to the main power of jc : parsing text.

I hope you will understand my point of view.
Best Regards,

**Comment by kellyjonbrazil** [comment]
Hi there!

I think this is a reasonable request. I'm currently working on v1.15.0 and hope to release it in the next few weeks. I think I can work this into the release as well.

Thanks again for the feedback - always appreciated!

Kelly

**Comment by kellyjonbrazil** [comment]
I have made all of the external library requirements optional in these commits:

https://github.com/kellyjonbrazil/jc/commit/808c7bc0a94ecfd160ee2b257e5feec347829a5e
https://github.com/kellyjonbrazil/jc/commit/4d394015f458f284d052ce2c1a0c8492916c5b3e
https://github.com/kellyjonbrazil/jc/commit/3638298af8ebc01d54aa3ab5668d0adedca957e5

I'll release these in `jc` v1.15.0 in the next couple weeks or so.

Thanks!

**Comment by tst2005** [comment]
Thanks a lot !

(and I just received [a pygments security update](https://www.linuxcompatible.org/story/dsa-48781-pygments-security-update/))

**Comment by kellyjonbrazil** [comment]
@tst2005 just a heads-up I found an issue where if parser libraries are not installed then running `jc -h` or `jc -a` will fail since those options iterate through the parser list and fail if one of them are missing. I'm fixing this in v1.15.5. I hope to have it out in the next couple weeks.
