### ISSUE TITLE
a compact json output ?

### ISSUE THREAD

**Issue by tst2005** [kellyjonbrazil/jc#110]
`jc -p` is the pretty print output, ok no problem.

`jc -r` is the raw json, but it is not the compact one.
There are still space between key and value, between each array items.

Is there a reason to not using the most compact output ?

**Comment by kellyjonbrazil** [comment]
I had been thinking of this but hadn't gotten around to it. Just fixed it and it will be in v1.15.0.

https://github.com/kellyjonbrazil/jc/commit/8912a99986a977ee6ca7bbe2368f5033644577b0

**Comment by kellyjonbrazil** [comment]
FYI, 'raw' in this context just means the parsed data hasn't gone through any additional processing, like added convenience fields or converting numbers into ints/floats. Now all non-pretty output will be compact.

**Comment by tst2005** [comment]
Thanks!
Yes, I understand.
I think
a tool with pretty print output is usefull,
a tool with compact output is usefull, but
a tool with raw output is more like a debug output or a "the easiest code" output, but less usefull than the both other output.
IMHO, `jc` only needs "pretty print" and "compact" output.
I suppose renaming the raw output option to compact output with a `-c` or whatever is a lost of time and a gain of confusion.
The raw output == compact output seems the better way (the one you choose).

My last suggestion, change the help/man output to tell people that is now a compact output ?

```diff
 Options:
-        -a               about jc
+        -a               about jc (JSON content)
         -d               debug - show traceback (-dd for verbose traceback)
         -m               monochrome output
-        -p               pretty print output
+        -p               pretty print output (JSON content)
         -q               quiet - suppress parser warnings
-        -r               raw JSON output
+        -r               raw/compact output (JSON content)
```

**Comment by kellyjonbrazil** [comment]
Yeah, since `jc` is already being used in scripts I try not to make any option changes that will significantly change the behavior. In this case, removing spaces from the default output won't change how the JSON is parsed and it will be slightly smaller, so it was an easier change.
