### ISSUE TITLE
Feature request - /usr/bin/time

### ISSUE THREAD

**Issue by DerBroader71** [kellyjonbrazil/jc#111]
A parser for /usr/bin/time would be great - we use it a lot during tests/builds

/usr/bin/time --verbose free -m
              total        used        free      shared  buff/cache   available
Mem:          15923        3532         163         372       12227       11791
Swap:           510         510           0
        Command being timed: "free -m"
        User time (seconds): 0.00
        System time (seconds): 0.00
        Percent of CPU this job got: 100%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.00
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 3996
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 203
        Voluntary context switches: 1
        Involuntary context switches: 4
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0

**Comment by kellyjonbrazil** [comment]
Thank you for the feature request! This does look doable. I'm curious how this is used in practice? Is the `-o` option used to write the `time` input to a file and that's what `jc` would parse, or would you redirect STDERR to `jc`?

**Comment by DerBroader71** [comment]
In our current playbooks, we do both (grr! depending on who wrote it). 
My preference would be to use `-o`  and have `jc` parse that, which we would do as a separate step in the test script, so that the results can be ingested and reported in later in the process.

**Comment by kellyjonbrazil** [comment]
Hi there - I have a working version of the `/usr/bin/time` parser available here: https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/time.py

I'm planning on adding this to the next 1.15.0 release in a couple weeks, but in the meantime you can test the parser by copy/pasting the code in the link above to a file called `~/.local/share/jc/jcparsers/time.py`

Let me know if you notice any issues.

Thanks!

**Comment by DerBroader71** [comment]
Hi

It has worked on everything I have thrown at it, so I call this working :+1: 

Thanks

**Comment by kellyjonbrazil** [comment]
Sweet, thanks for testing! I'll close this out when 1.15.0 is released.
