### ISSUE TITLE
more modular parsers ?

### ISSUE THREAD

**Issue by tst2005** [kellyjonbrazil/jc#113]
Hello it's me again! :-)

I'm using jc 1.14.3 provided by debian (10) stable.

- I took the [rpm_qi.py](https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/rpm_qi.py) file, injected it into my `/usr/lib/python3/dist-packages/jc/parsers/`.
- `jc --rpm_qi < sample` didn't recognize the parser
- I edited the `/usr/lib/python3/dist-packages/jc/cli.py`, added the 'rpm_qi' value in the list.
- `jc --rpm_qi < sample` recognize the parser but fail due to missing `jc.utils.timestamp`
- I comment the [if block](https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/rpm_qi.py#L190-L193) that manage the `build_epoc*` fields.
- I run perfectly (but without build_epoc stuff)

I launch a think about how hard is it to make jc more modular.
In the futur...
- should we think about auto-discovery instead of static list in cli.py ?
- from one directory ?
- from more than one directories ? support a custom user directory for additionnal parsers ?

I don't know if the jc's core features are changed frequently.

About my use case...

I'm working on huge different version of OS (Win, Linux, OSX but also AIX, HP-UX, Solaris and more... all of them in almost all OS versions that never existed...)
My case of use is more "using jc on my linux, with data remotely get over ssh",
I will probably only use the `jc --parsername ...` and almost never `jc commandname ...`.
For now,
I don't massively try jc with my old exotic OS.
I only made a simple test with `dh -k` on AIX what needs minor workaround to be parsed by `jc`.
For now this test, I fix it on the fly on the data itself.
Another solution should be to try to make my own parser, and/or a patch for an existing one.
For now it seems not so hard to add a parser, but harder than just puting the file in the good directory.

What is your opinion ?

**Comment by kellyjonbrazil** [comment]
Hi there - sorry I should have mentioned that you could put the parser file in ~/.local/jc/jcparsers. The instructions are in the readme under ‘custom parsers’.

You will probably get an error with this new parser on the current version of jc since it uses a new shared function to calculate time stamps. If you use the `-r` option it will work by skipping that functionality.

**Comment by tst2005** [comment]
Oh, it seems exactly what I need !

Since which version is it possible?
I tried without success with my jq 1.14.3.

**Comment by kellyjonbrazil** [comment]
It was added in v1.11.3. I use it quite a bit when developing new parsers and having users test new parser versions.

**Comment by kellyjonbrazil** [comment]
I just remembered - there is slight weirdness with parsers like `rpm_qi` that have an underscore. I can take a look at the code and see if I can fix it, but for custom parsers you would use `rpm -qia | jc --rpm_qi` instead of `rpm -qia | jc --rpm-qi`.

**Comment by tst2005** [comment]
I read  `/.local/share/jc/parsers` instead of `~/.local/share/jc/jcparsers`.
It's run correctly, like you said `jc --rpm_qi`. Perfect!

There is still the case of recent parsers code that use feature that was not present in older jc version.
I think it is not hard to workaround : disable the code or more check to use a method only when it really exist.

**Comment by kellyjonbrazil** [comment]
Good stuff - version 1.15.0 is now available via pip, packages, and binaries: https://kellyjonbrazil.github.io/jc-packaging

**Comment by tst2005** [comment]
Thanks a lot !
