### ISSUE TITLE
helptext() - print('...', file=sys.stderr)

### ISSUE THREAD

**Issue by ilyash-b** [kellyjonbrazil/jc#12]
`print('...', file=sys.stderr)` can be factored out

**Comment by kellyjonbrazil** [comment]
Are you saying to use a single variable to store the whole text and just use a single `print(variable, file=sys.stderr)` command or are you saying not to send help text to stderr?

**Comment by ilyash-b** [comment]
I was thinking just about factoring out the repeating part and define a function that takes one parameter - `s` and then does print(s, file=sys.stderr)

**Comment by ilyash-b** [comment]
alternatively you can put all the strings in an array and loop on that

**Comment by kellyjonbrazil** [comment]
gotcha - makes sense, thanks!
