### ISSUE TITLE
Feature request: docker cli

### ISSUE THREAD

**Issue by ksurl** [kellyjonbrazil/jc#122]
mostly `docker ps`, `docker ps -a` and `docker images`, but others may be useful also such as network, volumes, etc.

**Comment by kellyjonbrazil** [comment]
I had docker commands on my list, but then I discovered that you can get JSON output by doing the following:
```
docker images --format='{{json .}}'
```
Does that meet your requirements?

**Comment by ksurl** [comment]
oh I didn't know about that flag. looks like it works well with `jq`.
