### ISSUE TITLE
Add support for UFW

### ISSUE THREAD

**Issue by YannMCX** [kellyjonbrazil/jc#124]
Hello,

First of all, I would like to thank the creators / contributors of this lib, it is very useful for my projects !

I want know if it possible to add support for ufw command, like `ufw status` :)

Thank's

**Comment by kellyjonbrazil** [comment]
Hi there - thanks for the suggestion! This command looks like a good parser candidate. I'll have to play around with it for a bit to see if there are any interesting things to look out for in the verbose output, but otherwise it looks pretty straightforward.

I'll start working on this and when I have something to test, I'll deliver it as a custom parser plugin. (https://github.com/kellyjonbrazil/jc#custom-parsers). Once it tests well I can package it in the next release.

Cheers!

**Comment by YannMCX** [comment]
Great! I had started a parser under Node.js, if I can give an advice, be careful with the multiple possibilities of source and destination that UFW allows, it caused me problems :)

**Comment by kellyjonbrazil** [comment]
Excellent - if you have any problematic samples you can share here, that would be very helpful.

**Comment by YannMCX** [comment]
Here's an example 
![image](https://user-images.githubusercontent.com/23440844/115413185-431d8680-a1f5-11eb-95d1-b34388e33f03.png)

You can add rule per interface, per protocol (TCP or UDP only), per port, you can set up port on source and/or destination, you can specify range (as described with `<start port>:<end port>`) and finally you can specify service name too (smtp, http, etc...) depending on the rules present in `/etc/ufw/applications.d/`

PS: Sorry if my english is not perfect, i'm from :fr: :)

**Comment by kellyjonbrazil** [comment]
Cool, thanks!

**Comment by kellyjonbrazil** [comment]
I'm still working out how to do this and I think I have it figured out, but want to share the first-pass at a schema to see if this would work for you:
```
{
  "status":                   string,
  "logging":                  string,      # split with a filed for `logging_level`?
  "default":                  string,      # split this?
  "new_profiles":             string,
  "rules": [
    {
      "number":               integer,
      "to_interface":         string,
      "to_ip":                string,      # split on subnet?
      "to_port":              string,
      "to_port_num":          integer,     # if `port` is numeric
      "to_protocol":          string,
      "to_v6":                boolean
      "action":               string,
      "direction":            string,
      "from_interface":       string,
      "from_ip":              string,      # split on subnet?
      "from_port":            string,
      "from_port_num":        integer,     # if `port` is numeric
      "from_protocol":        string,
      "from_v6":              boolean
    }
  ]
}
```
I like to keep the schema as flat as possible, so I didn't create separate `to` and `from` objects.

**Comment by YannMCX** [comment]
Looking great, what's the behavior if there's a range for the port, like my screen, line 4

And what's the behavior for apps ? If you use the following command : `ufw allow openssh`

In `rules` you can change `number` by `index`, because it's the index for the rule, right ?

What's the `new_profiles` field purpose ? Btw, I didn't know if you can get the rules when UFW is disabled

**Comment by kellyjonbrazil** [comment]
For apps, I was thinking they would just be in the to/from `protocol` field.

I probably could remove the `number` field since it will probably match the array index, but there is an option to print the rule number in `ufw`, so I added it in case the rule number is printed:
```
$ ufw status numbered
Status: active
 
To                         Action      From
--                         ------      ----
[ 1] 22/tcp                     ALLOW IN    Anywhere
[ 2] 22/tcp (v6)                ALLOW IN    Anywhere (v6)
```
I'm not sure what `new_profiles` does, but I saw it in example output:
```
$ ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), deny (routed)
New profiles: skip
 
To                         Action      From
--                         ------      ----
22/tcp                     ALLOW IN    Anywhere
```
Yes, probably if `status` is not active, the result will look something like:
```
{
  "status": "disabled
}
```

**Comment by kellyjonbrazil** [comment]
> I think you can split for the subnet, because if I use this parser, I prefer to have all part of a field separately, same for logging_level.
> PS: flat object is really good, I've done some deep object, but it's not a really good way...
> PPS: If you can convert words like "Anywhere" to something more like "0.0.0.0" it could be nice too...

Sounds good - I can do that. Thanks for the quick feedback!

**Comment by YannMCX** [comment]
This can be great, i can try it out tomorrow if you need some feedback

**Comment by kellyjonbrazil** [comment]
I'll think about splitting on port range. I'm not sure how to handle that and if there are other conditions, like a list of port numbers to deal with (e.g. `22,80,443`) or something like that.

**Comment by YannMCX** [comment]
From what I know, the port range work like that `<start_port>:<end_port>`

I didn't know if you can set a port list, I think you should create multiple rule to make a list of port...

**Comment by kellyjonbrazil** [comment]
I have an initial working parser here: https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/ufw.py

I still need to run it through tests, but I think I'm close. Let me know if you run into any issues.

Thanks!

**Comment by YannMCX** [comment]
Here's some tests, this is my current firewall configuration:
```
➜ ufw status                
Status: active

To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere                  
50307                      ALLOW       Anywhere                  
50207:50208/tcp            ALLOW       Anywhere                  
22 (v6)                    ALLOW       Anywhere (v6)             
50307 (v6)                 ALLOW       Anywhere (v6)             
50207:50208/tcp (v6)       ALLOW       Anywhere (v6)             
```

Here's the result from your parser:
```
{
  "status": "active",
  "rules": [
    {
      "action": "ALLOW",
      "action_direction": null,
      "index": null,
      "network_protocol": "ipv4",
      "to_interface": "any",
      "to_transport": "any",
      "to_start_port": 22,
      "to_end_port": 22,
      "to_ip": "0.0.0.0",
      "to_ip_prefix": "0",
      "from_ip": "0.0.0.0",
      "from_ip_prefix": "0",
      "from_interface": "any",
      "from_transport": "any",
      "from_start_port": 0,
      "from_end_port": 65535,
      "from_service": null
    },
    {
      "action": "ALLOW",
      "action_direction": null,
      "index": null,
      "network_protocol": "ipv4",
      "to_interface": "any",
      "to_transport": "any",
      "to_start_port": 50307,
      "to_end_port": 50307,
      "to_ip": "0.0.0.0",
      "to_ip_prefix": "0",
      "from_ip": "0.0.0.0",
      "from_ip_prefix": "0",
      "from_interface": "any",
      "from_transport": "any",
      "from_start_port": 0,
      "from_end_port": 65535,
      "from_service": null
    },
    {
      "action": "ALLOW",
      "action_direction": null,
      "index": null,
      "network_protocol": "ipv4",
      "to_interface": "any",
      "to_transport": "tcp",
      "to_start_port": 50207,
      "to_end_port": 50208,
      "to_ip": "0.0.0.0",
      "to_ip_prefix": "0",
      "from_ip": "0.0.0.0",
      "from_ip_prefix": "0",
      "from_interface": "any",
      "from_transport": "any",
      "from_start_port": 0,
      "from_end_port": 65535,
      "from_service": null
    },
    {
      "action": "ALLOW",
      "action_direction": null,
      "index": null,
      "network_protocol": "ipv6",
      "to_interface": "any",
      "to_transport": "any",
      "to_start_port": 22,
      "to_end_port": 22,
      "to_ip": "::",
      "to_ip_prefix": "0",
      "from_ip": "::",
      "from_ip_prefix": "0",
      "from_interface": "any",
      "from_transport": "any",
      "from_start_port": 0,
      "from_end_port": 65535,
      "from_service": null
    },
    {
      "action": "ALLOW",
      "action_direction": null,
      "index": null,
      "network_protocol": "ipv6",
      "to_interface": "any",
      "to_transport": "any",
      "to_start_port": 50307,
      "to_end_port": 50307,
      "to_ip": "::",
      "to_ip_prefix": "0",
      "from_ip": "::",
      "from_ip_prefix": "0",
      "from_interface": "any",
      "from_transport": "any",
      "from_start_port": 0,
      "from_end_port": 65535,
      "from_service": null
    },
    {
      "action": "ALLOW",
      "action_direction": null,
      "index": null,
      "network_protocol": "ipv6",
      "to_interface": "any",
      "to_transport": "tcp",
      "to_start_port": 50207,
      "to_end_port": 50208,
      "to_ip": "::",
      "to_ip_prefix": "0",
      "from_ip": "::",
      "from_ip_prefix": "0",
      "from_interface": "any",
      "from_transport": "any",
      "from_start_port": 0,
      "from_end_port": 65535,
      "from_service": null
    }
  ]
}
```
There's a little weird comportement for `from_ip` and `to_ip` if there's no IP specified, same for the prefix. And for fields `from_start_port` and `from_end_port` why just don't leave them at `null` if they're not specified ?

**Comment by YannMCX** [comment]
> Could you explain the behavior issue with the from_ip and to_ip with a port range? I'm on my first coffee and I'm not seeing it yet. I'm a firewall guy, so I'm being more specific than any by using the actual ipv4/ipv6 designations for any IP: 0.0.0.0/0 and ::/0, respectively.

Ok, for this point I had not seen that we were in ipv6, so no problem on this side... Not enough coffee for me :smile: 

For the `end_port` i think consistency is better than just have a `null` value...

**Comment by kellyjonbrazil** [comment]
No problem - this was a really fun parser to write. Many different techniques required to get the fields in order and this is the first parser I found a use for the `ipaddress` module, which I think really helped a lot. I'll start working on tests and release in 1.15.3 in the next week or so.

If you see any other issues, please let me know.

**Comment by YannMCX** [comment]
It's okay for me, haven't seen any bug, nice job ! I'll use it to make an firewall rules editor on my app

**Comment by kellyjonbrazil** [comment]
I added support for rule comments and other actions like reject and limit, as well as fwd as a direction. 

I’m looking into adding a parser for ufw info APP as well.

**Comment by YannMCX** [comment]
Yeah seem great to have it too, i'll update the parser on my server to try it out

**Comment by kellyjonbrazil** [comment]
Cool - I'm doing some more testing on Ubuntu and found some more scenarios. I'm looking into better support for lists of ports, like rules 2 and 5:
```
Status: active

     To                         Action      From
     --                         ------      ----
[ 1] 22                         ALLOW IN    Anywhere                  
[ 2] 80,443/tcp                 ALLOW IN    Anywhere                  
[ 3] 80 on eth0                 ALLOW IN    Anywhere                   # test
[ 4] 22 (v6)                    ALLOW IN    Anywhere (v6)             
[ 5] 80,443/tcp (v6)            ALLOW IN    Anywhere (v6)             
[ 6] 80 (v6) on eth0            ALLOW IN    Anywhere (v6)              # test
```
Right now there is a bug, so `transport protocol` is `null` for those rules and the port list is going into the to/from`_service` fields. I think this might be ok if I just fix the `transport_protocol` bug and leave things as they are so you an split the `service` field for the list of ports. 
```
{
      "action": "ALLOW",
      "action_direction": "IN",
      "index": 2,
      "network_protocol": "ipv4",
      "to_interface": "any",
      "to_transport": null,                <--- I'll fix this bug
      "to_service": "80,443",           <--- list of ports
      "to_start_port": null,
      "to_end_port": null,
      "to_ip": "0.0.0.0",
      "to_ip_prefix": 0,
      "comment": null,
      "from_ip": "0.0.0.0",
      "from_ip_prefix": 0,
      "from_interface": "any",
      "from_transport": "any",
      "from_start_port": 0,
      "from_end_port": 65535,
      "from_service": null
    }
```
Alternatively, I could parse this into another `port_list` field. My only concern is that if I do that, it starts to get messy and you'll have to check multiple locations for port information: `start_port`, `end_port`, `port_list`, `service`. So I'm thinking it might be simpler just to leave as is.

Let me know if you have a better solution for this or if you think it makes sense to create another field for port lists.

Thanks!

**Comment by kellyjonbrazil** [comment]
I added the `--ufw-appinfo` [parser](https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/ufw_appinfo.py). It might be helpful for your application because if an app name is found in a rule, then you can run `ufw app info [appname]` to gather the udp/tcp ports for the app and display in your front-end.

It's a kind of interesting parser because `ufw` app profiles allow overlapping lists and ranges of ports. If that is fine with you, then you can use the normal udp/tcp port fields. But I also added `normalized` fields that remove the duplicates and overlapping ranges and gives you a true sense of what the app profile is in case it is configured strangely.

**Comment by kellyjonbrazil** [comment]
I was doing some more research and tests and it turns out `ufw` allows lists of ports and lists of port ranges, so I made some changes to the schema to support these scenarios. I think this is the last schema change and I'll be pushing this out in v1.15.3 this week.

Here is the new schema:
```
{
  "status":                     string,
  "logging":                    string,
  "logging_level":              string,
  "default":                    string,
  "new_profiles":               string,
  "rules": [
    {
      "action":                 string,
      "action_direction":       string,     # null if blank
      "index":                  integer,    # null if blank
      "network_protocol":       string,
      "to_ip":                  string,
      "to_ip_prefix":           integer,
      "to_interface":           string,
      "to_transport":           string,
      "to_ports": [
                                integer
      ],
      "to_port_ranges": [
        {
          "start":              integer,
          "end":                integer
        }
      ],
      "to_service":             string,     # null if any to ports or port_ranges are set
      "from_ip":                string,
      "from_ip_prefix":         integer,
      "from_interface":         string,
      "from_transport":         string,
      "from_ports": [
                                integer
      ],
      "from_port_ranges": [
        {
          "start":              integer,
          "end":                integer
        }
      ],
      "from_service":           string,     # null if any from ports or port_ranges are set
      "comment":                string      # null if no comment
    }
  ]
}
```

**Comment by kellyjonbrazil** [comment]
v1.15.3 has been released
