### ISSUE TITLE
Change deb package name to match Debian's official convention

### ISSUE THREAD

**Issue by YannMCX** [kellyjonbrazil/jc#125]
Hey !

I've seen your deb package is named like that: `jc-1.15.2-1.x86_64.deb`

But the debian's convention is like that: `<package_name>`\_`<version>`\_`<arch>`.deb, at this moment, you're correct for the RPM naming convention :smile: 

Réf: https://manpages.debian.org/buster/dpkg-dev/dpkg-name.1.en.html

Friendly.

**Comment by kellyjonbrazil** [comment]
Good catch! I'll change that for the next release (v1.15.3). I suppose it should look like:
```
jc_1.15.3-1_amd64.deb
```
correct?

**Comment by YannMCX** [comment]
Yep that's correct

**Comment by kellyjonbrazil** [comment]
v1.15.3 released
