### ISSUE TITLE
--dig should ignore +noall in ~/.digrc

### ISSUE THREAD

**Issue by nightbread** [kellyjonbrazil/jc#133]
I have a ~/.digrc file to make using it a little less verbose where I specify `+noall` and `+answer`. Because of this, `jc --dig` always outputs `[]` unless I use `+all` explicitly.

`~/.digrc` can be ignored with the `-r` option as mentioned in the manpage.

**Comment by kellyjonbrazil** [comment]
Hi there!

Thanks for opening this issue. I think the only real solution here is to always use the `-r` option with `dig` if you are piping to `jc` in a script and have a `~/.digrc` file to customize your `dig` output.

`jc` doesn't actually run the `dig` command. `jc` just parses the text that it receives via STDIN so it doesn't have any context as to whether any special flags were set on the command that produced the output. `jc` likes the output to be as 'standard' as possible or even verbose so it can generate all of the fields and then you would use a tool like `jq` or `jello`, etc. to filter which field values you want to extract.

There is one case where it would be possible to do this, but even then it feels a bit like a hack. When using the "magic" syntax (e.g. `jc dig example.com`) `jc` is actually rewriting the command as `dig example.com | jc --dig`. It would be possible to to rewrite it as `dig -r example.com | jc --dig`, but it's a bit of an exception and maybe there are use cases where users would not want that to happen. Also, the "magic" syntax is really designed more for interactive use than for use in scripts where you typically want to be more explicit.

I think the right way to do it would be:
```
$ dig -r example.com | jc --dig
```
or
```
$ jc dig -r example.com
```

**Comment by nightbread** [comment]
Yes it's only in newer versions unfortunately.

**Comment by nightbread** [comment]
Would you be willing to support `dig +noall +answer ...` output? It consists of only the answer, if there is one. It's the only line that doesn't start with `;;` and isn't blank.

**Comment by kellyjonbrazil** [comment]
I might be able to do something with that:
```
$ dig +noall +answer example.com
example.com.		56118	IN	A	93.184.216.34
```
I might be able to fall back to assuming the dig output is just the answer section if all else failed or something. I'll investigate.

**Comment by kellyjonbrazil** [comment]
I have added support for `+noall +answer` in the `dev` branch: https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/dig.py

You can place that file in your custom parser plugin directory to test it out. See https://github.com/kellyjonbrazil/jc#custom-parsers for details.

Let me know if that works for you. If so, I can package it into the next release.

Thanks!

**Comment by nightbread** [comment]
Works great. Thanks.
