### ISSUE TITLE
multi-platform readiness

### ISSUE THREAD

**Issue by ilyash-b** [kellyjonbrazil/jc#14]
Even if multi-platform is not implemented at the moment, I recommend to think how the code should be structured to support that feature. If you do it later, you might need to change a lot of code.

**Comment by kellyjonbrazil** [comment]
Off the top of my head I'm thinking that each parse module can do its own `sys.platform` check and branch if necessary or send a message to stderr that the running platform is not supported.

**Comment by kellyjonbrazil** [comment]
added the beginnings of this to the dev branch.
