### ISSUE TITLE
New Parser: xrandr

### ISSUE THREAD

**Issue by lyterk** [kellyjonbrazil/jc#142]
I can do a PR for this, I just wanted to see: Has anyone worked on this before?

**Comment by kellyjonbrazil** [comment]
Hi there - I think this would be an excellent parser addition and there is no-one working on it yet. Feel free to get a PR started. Let's work out a schema before getting in too deep. Looking forward to it.

Thanks!

**Comment by lyterk** [comment]
Neat yeah I'll get that written up.

**Comment by kellyjonbrazil** [comment]
Not sure if anyone would find it useful, but the `xrandr` conf files could also be converted to JSON with its own parser.

**Comment by lyterk** [comment]
Here's a preliminary schema:

`Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
eDP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
   1920x1080     60.03*+  59.93
   1680x1050     59.88
   1400x1050     59.98
   1600x900      60.00    59.95    59.82
   1280x1024     60.02
   1400x900      59.96    59.88
   1280x960      60.00
   1368x768      60.00    59.88    59.85
   1280x800      59.81    59.91
   1280x720      59.86    60.00    59.74
   1024x768      60.00
   1024x576      60.00    59.90    59.82
   960x540       60.00    59.63    59.82
   800x600       60.32    56.25
   864x486       60.00    59.92    59.57
   640x480       59.94
   720x405       59.51    60.00    58.99
   640x360       59.84    59.32    60.00
DP1 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
HDMI1 connected (normal left inverted right x axis y axis)
   1920x1080     60.00 +  50.00    59.94
   1920x1080i    60.00    50.00    59.94
   1680x1050     59.88
   1280x1024     75.02    60.02
   1440x900      59.90
   1280x960      60.00
   1280x720      60.00    50.00    59.94
   1024x768      75.03    70.07    60.00
   832x624       74.55
   800x600       72.19    75.00    60.32    56.25
   720x576       50.00
   720x480       60.00    59.94
   640x480       75.00    72.81    66.67    60.00    59.94
   720x400       70.08
VIRTUAL1 disconnected (normal left inverted right x axis y axis)`

`{
    "outputs": [
        {
            "name": string, // eDP1
            "is_connected": boolean,
            "is_primary": boolean,
            "associated_screen": {
                "screen_number": integer,
                "minimum_resolution_px": {
                    "width": integer,
                    "height": integer,
                },
                "current_resolution_px": {
                    "width": integer,
                    "height": integer,
                },
                "maximum_resolution_px": {
                    "width": integer,
                    "height": integer,
                },
                "resolution_px": {
                    "width": integer,
                    "height": integer,
                    "offset_width": integer,
                    "offset_height": integer,
                },
                "dimensions_mm": {
                    "width": integer,
                    "height": integer,
                }
            },
            "modes": [
                {
                    "dimension_px": {
                        "width": integer,
                        "height": integer,
                    },
                    "frequencies": [
                        {
                            "clock_khz": float,
                            "is_current": boolean,
                            "is_preferred": boolean
                        },
                        ...
                    ]
                },
                ...
            ]
        },
        {
            "name": string, // HDMI1
            ...
            "associated_screen": {}
            ...
        }
    ]

}`

**Comment by kellyjonbrazil** [comment]
Nice! Could we just remove the "outputs" key and make the output a list of dictionaries? That would match the other parsers' output more closely.

**Comment by lyterk** [comment]
Sure, not a problem

-- 
  Kevin Lyter
  ***@***.***

**Comment by kellyjonbrazil** [comment]
Hi there - just checking in to see how things are going with this. I'm planning on pushing out a new release soon with a new `sfdisk` parser and was wondering if I should go ahead or hold off for a bit if your parser is close to complete.

No rush - thanks!

**Comment by lyterk** [comment]
I’m on vacation, have only written preliminary regexes so far, haven’t tested. Feel free to push your new parser, I’ll pull when I get back

**Comment by kellyjonbrazil** [comment]
Just wanted to give you a heads up that I’m planning on releasing JC version 1.17.0 soon. It will be a pretty significant release with the addition of streaming parser support. I’m also including three streaming parsers: ping, ls, and vmstat.

If you are close to finishing the xrandr parser we can include it with the release. No pressure - if you’re not ready we can always add it to a minor release later.

**Comment by kellyjonbrazil** [comment]
Linking to https://github.com/kellyjonbrazil/jc/pull/204

**Comment by kellyjonbrazil** [comment]
This parser has been added to `jc` v1.18.3
