### ISSUE TITLE
New Parser: sfdisk

### ISSUE THREAD

**Issue by deknos** [kellyjonbrazil/jc#146]
Hello,
just a suggestion, a parser which parses sfdisk output? like with 

```
# sfdisk -l /dev/sdf
Disk /dev/sdf: 1044 cylinders, 255 heads, 63 sectors/track
Units: cylinders of 8225280 bytes, blocks of 1024 bytes, counting from 0

   Device Boot Start     End   #cyls    #blocks   Id  System
/dev/sdf1          0+    499     500-   4016249+  83  Linux
/dev/sdf2        500    1043     544    4369680   83  Linux
/dev/sdf3          0       -       0          0    0  Empty
/dev/sdf4          0       -       0          0    0  Empty
```

for example? :)

**Comment by kellyjonbrazil** [comment]
Hi there - thank you for the parser suggestion. This does look like a good candidate for `jc` and I can start working on this soon.

**Comment by kellyjonbrazil** [comment]
I have an initial working version in the `dev` branch here: https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/sfdisk.py

You can add this file to your local parser plugins directory as documented here: https://github.com/kellyjonbrazil/jc#custom-parsers

Could you test and let me know if you run into any issues?

Thanks!

**Comment by kellyjonbrazil** [comment]
Added in v1.16.0
