### ISSUE TITLE
Name conflict with autojump's 'jc'

### ISSUE THREAD

**Issue by s2k** [kellyjonbrazil/jc#150]
#### Context

I would like to use William Ting's `autojump` (see https://github.com/wting/autojump) as well as `jc` in the same context.

#### Observation

Both use `jc` as a shell command. Obviously only one of them can possibly first in the `PATH` first and therefore babe run.

#### Question or (feature) request

Is it possible to resolve this name clash, so that users of both pieces of software aren't affected by it?

I see a number of possibilities:

1. jc changes the name
2. autokump changes the name
3. Both include a way to circumvent the issue described above
4. Both READMEs (or other documentation) mention the issue and provide a workaround (if we find one, which should certainly be possible)

For (cross) reference, I added a similar issue to the other repo (and will link it as soon as both issues have a link): https://github.com/wting/autojump/issues/633

**Comment by kellyjonbrazil** [comment]
Thank you for reporting this - I was not aware of this conflict. I'm thinking the best way to workaround this issue would be to create an alias. Depending on how `jc` is installed (`pip`, OS package install, downloaded binary, etc.) the binary or launch script can be in different locations.  You could find the location of `jc` and then add an alias to your `.bashrc` file or similar:
```
alias jc2=/usr/bin/jc
```
