### ISSUE TITLE
Using -la flags with `ls` gives wrong filename and date.

### ISSUE THREAD

**Issue by antonaut** [kellyjonbrazil/jc#151]
Hey!

I ran `jc ls -la` and got attributes mixed up. I run Ubuntu and use Swedish locales (LC_ALL="sv_SE.UTF-8").

Example output:

```json
{
  "filename": "07:34 .",
  "flags": "drwxr-x---",
  "links": 64,
  "owner": "antonaut",
  "group": "domain",
  "size": null,
  "date": "4096 Aug 12",
  "epoch": null,
  "epoch_utc": null
}
```

**Comment by kellyjonbrazil** [comment]
Hi there - thanks for reporting this.

As noted in the [Caveats](https://github.com/kellyjonbrazil/jc#caveats) section of the Readme, you may get incorrect results with some parsers when not using the `C` or `en_US.UTF-8` locales.

Could you paste the `ls -al` output using the `sv_SE.UTF-8` locale? If it is not too different than other locales it might not be to hard to support it.
