### ISSUE TITLE
Process substitutions are broken with magic syntax

### ISSUE THREAD

**Issue by buecking** [kellyjonbrazil/jc#153]
Process substitutions are broken.  Since these use named pipes under the hood, most systems should support their use.  Note, not all shells support this syntax, for example, dash does not.

**Works**
```
% head -n 100 /dev/urandom > somefile
% jc wc somefile
[
  {
    "filename": "somefile",
    "lines": 100,
    "words": 567,
    "characters": 27151
  }
]
```

**Fails**
```
% jc wc  <(cut -c 1-10 somefile)
wc: /proc/self/fd/11: No such file or directory
[]
```

**workaround**
```
% wc <(cut -c 1-10 somefile) | jc --wc
[
  {
    "filename": "/proc/self/fd/11",
    "lines": 0,
    "words": 1,
    "characters": 950
  }
]
```

**Comment by kellyjonbrazil** [comment]
I added a check for too many open files exception in `dev` branch. Still testing and researching the implications of inheriting file descriptors in the subprocess:

http://zderadicka.eu/subtle-evil-of-close_fds-parameter-in-subprocess-popen/
https://www.python.org/dev/peps/pep-0446/

Wondering if this will be ok to deploy as the new default or if a new command line option should be added to allow this behavior. Seems like the `jc` use cases would not necessarily run into the issues described but still want to be cautious with this setting.

**Comment by buecking** [comment]
Keep in mind you can also nest process substations, each returns a unique fd to its parent.

```
 % echo <(echo <(echo $((1*2))))
/proc/self/fd/11
 % cat <(echo <(echo $((1*2)))) 
/proc/self/fd/10
 % echo <(cat <(echo $((1*2))))
/proc/self/fd/11
```

**Comment by kellyjonbrazil** [comment]
I uploaded `jc` v1.16.1 to PyPi. Could you let me know if that works for you?

Thanks!
