### ISSUE TITLE
bug sfdisk parcer

### ISSUE THREAD

**Issue by caisyew** [kellyjonbrazil/jc#162]
HI!
I tried the parser on two operating systems :
Debian 10 and CentOS 8.

If I specify sfdisk -l /dev/sda1 | jc --sfdisk , the output is :
[{"disk":"/dev/sda1","cylinders":1,"units":"sectors of 1 * 512 = 512 bytes"}]

But, if I want to get information on the entire sdc drive,
I get a parser error :
```
 sfdisk -l /dev/sda | jc --sfdisk -dd :

Traceback (most recent call last):
  File "/usr/local/bin/jc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/jc/cli.py", line 618, in main
    result = parser.parse(data, raw=raw, quiet=quiet)
  File "/usr/local/lib/python3.8/site-packages/jc/parsers/sfdisk.py", line 296, in parse
    item['heads'] = line.split()[4]
IndexError: list index out of range

.... sfdisk.py in parse(data='Disk /dev/sda: 32 GiB, 34359738368 bytes, 671088...     2099200 67108863 65009664  31G 8e Linux LVM\n', raw=False, quiet=False)

```
If I comment out 2 lines ::

296 # item['heads'] = line.split()[4]
297 # item['sectors_per_track'] = line.split()[6]

I have this result :
[{"disk":"/dev/sda","cylinders":32,"units":"sectors of 1 * 512 = 512 bytes"},{"disk":"identifier","cylinders":57705}]

If my normal sfdisk output here:

```
# sfdisk -l /dev/sda
Disk /dev/sda: 32 GiB, 34359738368 bytes, 67108864 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x5fac7705

Device     Boot   Start      End  Sectors Size Id Type
/dev/sda1  *       2048  2099199  2097152   1G 83 Linux
/dev/sda2       2099200 67108863 65009664  31G 8e Linux LVM 

```
 
That is, all drive information is not displayed.
I would also like to ask for support for the -F flag, I often use it to get information about disk resizing.

Thanx

**Comment by kellyjonbrazil** [comment]
Thank you for reporting this!

Could you put the full `sfdisk` output in triple backticks so I can copy paste it without losing any formatting? Hopefully it's just a quick tweak to the parsers.  I'll look into the `-F` flag as well.

**Comment by caisyew** [comment]
for -F flag output : 
''' # sfdisk -F /dev/sdc
Unpartitioned space /dev/sdc: 1 GiB, 1073741824 bytes, 2097152 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes

  Start     End Sectors Size
4194304 6291455 2097152   1G
'''

**Comment by kellyjonbrazil** [comment]
Thanks - just to be sure, could you make sure to use backticks? (`````)

**Comment by kellyjonbrazil** [comment]
Yep, it looks like the command output changed significantly in the newer versions of `sfdisk`. I should be able to get a fix out in the next few days.

**Comment by kellyjonbrazil** [comment]
I have an updated `sfdisk` parser in the `dev` branch. Could you copy the [`sfdisk.py`](https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/sfdisk.py) file to your [custom parser plugin directory](https://github.com/kellyjonbrazil/jc#custom-parsers) and let me know if that works ok for you?

Thanks!

**Comment by caisyew** [comment]
sfdisl -l : correct now : 

```
$ sudo  sfdisk -l /dev/sda |jc --sfdisk -p
[
  {
    "disk": "/dev/sda",
    "disk_size": "32 GiB",
    "bytes": 34359738368,
    "sectors": 67108864,
    "units": "sectors of 1 * 512 = 512 bytes",
    "logical_sector_size": 512,
    "physical_sector_size": 512,
    "min_io_size": 512,
    "optimal_io_size": 512,
    "disk_label_type": "dos",
    "disk_identifier": "0x5fac7705",
    "partitions": [
      {
        "device": "/dev/sda1",
        "boot": true,
        "start": 2048,
        "end": 2099199,
        "sectors": 2097152,
        "size": 1,
        "id": "83",
        "type": "Linux"
      },
      {
        "device": "/dev/sda2",
        "boot": false,
        "start": 2099200,
        "end": 67108863,
        "sectors": 65009664,
        "size": 31,
        "id": "8e",
        "type": "Linux LVM"
      }
    ]
  }
]
```


But in sfdisk -F /dev/sdc i dont have info about START and END sector :

```
$ sudo  sfdisk -F /dev/sdc |jc --sfdisk -p
[
  {
    "disk": "/dev/sdc",
    "free_disk_size": "1 GiB",
    "free_bytes": 1073741824,
    "free_sectors": 2097152,
    "units": "sectors of 1 * 512 = 512 bytes",
    "logical_sector_size": 512,
    "physical_sector_size": 512
  }
]
```

**Comment by caisyew** [comment]
But ! If i have "Disklabel type: gpt" the output of the command will be different and the parser cannot get disk partition information because there is no BOOT column:

1 example with "dos" type label ( parser works correct ):
```
sudo sfdisk -l /dev/sda
Disk /dev/sda: 32 GiB, 34359738368 bytes, 67108864 sectors
Disk model: QEMU HARDDISK   
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x4f1ce2bf

Device     Boot    Start      End  Sectors  Size Id Type
/dev/sda1  *        2048 13260799 13258752  6.3G 83 Linux
/dev/sda2       13262846 67106815 53843970 25.7G  5 Extended
/dev/sda5       13262848 18331647  5068800  2.4G 83 Linux
/dev/sda6       18333696 20332543  1998848  976M 82 Linux swap / Solaris
/dev/sda7       20334592 21352447  1017856  497M 83 Linux
/dev/sda8       21354496 67106815 45752320 21.8G 83 Linux
'''

And 2 example with  "gpt" label :

```

sfdisk -l /dev/sda
Disk /dev/sda: 238.5 GiB, 256060514304 bytes, 500118192 sectors
Disk model: NT-256          
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 50DEF501-A333-48D1-B1FC-C2F1CCFD5715

Device         Start       End   Sectors   Size Type
/dev/sda1       2048    526335    524288   256M Linux root (x86)
/dev/sda2     526336 138545151 138018816  65.8G Linux root (x86)
/dev/sda3  483684352 500117503  16433152   7.9G Linux swap
/dev/sda4  138545152 483684351 345139200 164.6G Linux filesystem
'''

output parser :

```
sfdisk -l /dev/sda |jc --sfdisk -p
[
  {
    "disk": "/dev/sda",
    "disk_size": "238.5 GiB",
    "bytes": 256060514304,
    "sectors": 500118192,
    "disk_model": "NT-256",
    "units": "sectors of 1 * 512 = 512 bytes",
    "logical_sector_size": 512,
    "physical_sector_size": 512,
    "min_io_size": 512,
    "optimal_io_size": 512,
    "disk_label_type": "gpt",
    "disk_identifier": "50DEF501-A333-48D1-B1FC-C2F1CCFD5715"
  }
]
'''

( test in DEBIAN 10 )

**Comment by kellyjonbrazil** [comment]
I think I was able to fix the remaining issues. Could you pull down the latest changes from the `sfdisk.py` file above and try again? Thanks!

**Comment by caisyew** [comment]
Thank you very match !!! Work is very well!!! Great job!

```
sfdisk -l /dev/sdc |jc --sfdisk -p
[
  {
    "disk": "/dev/sdc",
    "disk_size": "931.5 GiB",
    "bytes": 1000204886016,
    "sectors": 1953525168,
    "disk_model": "",
    "units": "sectors of 1 * 512 = 512 bytes",
    "logical_sector_size": 512,
    "physical_sector_size": 4096,
    "min_io_size": 4096,
    "optimal_io_size": 4096,
    "disk_label_type": "gpt",
    "disk_identifier": "00005954-4A70-0000-E60F-0000E3510000",
    "partitions": [
      {
        "device": "/dev/sdc1",
        "start": 40,
        "end": 409639,
        "sectors": 409600,
        "size": "200M",
        "type": "EFI System"
      },
      {
        "device": "/dev/sdc2",
        "start": 411648,
        "end": 1952255591,
        "sectors": 1951843944,
        "size": "930.7G",
        "type": "Microsoft basic data"
      },
      {
        "device": "/dev/sdc3",
        "start": 1952255592,
        "end": 1953525127,
        "sectors": 1269536,
        "size": "619.9M",
        "type": "Apple boot"
      }
    ]
  }
]
```
And with flag -F:

```
sfdisk -F /dev/sdc |jc --sfdisk -p
[
  {
    "disk": "/dev/sdc",
    "free_disk_size": "16 EiB",
    "free_bytes": 18446744073708523520,
    "free_sectors": 18446744073709549608,
    "units": "sectors of 1 * 512 = 512 bytes",
    "logical_sector_size": 512,
    "physical_sector_size": 4096,
    "partitions": [
      {
        "start": 2048,
        "end": 39,
        "sectors": 18446744073709549608,
        "size": "16E"
      }
    ]
  }
]
```

**Comment by kellyjonbrazil** [comment]
Great news! I'll push these out to PyPi in the next few minutes in v1.16.2.

**Comment by caisyew** [comment]
By the way, your parser also works fine directly with FDISK, like this:

```
sudo echo "F" | sudo fdisk /dev/sdc |jc --sfdisk -p
[
  {
    "units": "sectors of 1 * 512 = 512 bytes",
    "logical_sector_size": 512,
    "physical_sector_size": 512,
    "partitions": [
      {
        "start": 4194304,
        "end": 6291455,
        "sectors": 2097152,
        "size": "1G"
      }
    ]
  }
]
```

**Comment by kellyjonbrazil** [comment]
Very cool - I didn't realize that.

**Comment by kellyjonbrazil** [comment]
Oh, I forgot to mention - I noticed there is now a `-J` JSON output option in `sfdisk`, which is great! Unfortunately, though, it is quite limited at the moment.
