### ISSUE TITLE
Parser for NVidia SMI command

### ISSUE THREAD

**Issue by YannMCX** [kellyjonbrazil/jc#166]
Create a parser for nvidia-smi commands, here's an attached files of the output of the command

[nvidia-smi-output.txt](https://github.com/kellyjonbrazil/jc/files/7121561/nvidia-smi-output.txt)

**Comment by kellyjonbrazil** [comment]
Hi there - thank you for your suggestion!

I was checking out the `nvidia-smi` [documentation](https://developer.download.nvidia.com/compute/DCGM/docs/nvidia-smi-367.38.pdf) and it looks like there is an XML output option with `-x`.
```
-x, --xml-format
 Produce XML output in place of the default human-readable format. Both
 GPU and Unit query outputs conform to corresponding DTDs. These are
 available via the --dtd flag.
```
If you would prefer JSON, then you could convert the XML output to JSON using `jc` with something like this:
```
$ nvidia-smi -a -q -x | jc --xml
```
