### ISSUE TITLE
alpine linux ping

### ISSUE THREAD

**Issue by shaikustin** [kellyjonbrazil/jc#178]
alpine linux's ping output does not have the mdev result and the parser fails on it.
here is an example ping that the parser fails on

PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=42 time=1.637 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.637/1.637/1.637 ms

**Comment by kellyjonbrazil** [comment]
Thanks for reporting this and providing a fix! I'll take a look at the PR.

**Comment by kellyjonbrazil** [comment]
BTW, did you happen to notice any issues with the streaming ping parser? (`ping-s`)

I'm thinking there may be no issue since the summary lines may be ignored in the streaming parser (I'll have to check)

**Comment by shaikustin** [comment]
I did not use the streaming parser, but I think it should be fine, the problem was in the summary line
