### ISSUE TITLE
apt-get install jc failed

### ISSUE THREAD

**Issue by 0x217** [kellyjonbrazil/jc#181]
Hi,

jc is a great tool!
I would like to install jc using apt install on Ubuntu20.04.
I got error:
`ubuntu@0x217~$ sudo apt-get install jc
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package jc`

Should i using your repo?

I will be happy to your assistance.

Thanks!

**Comment by kellyjonbrazil** [comment]
Hi there - thanks!

It looks like the earliest Ubuntu version `jc` is packaged for is v20.10.

https://kellyjonbrazil.github.io/jc-packaging/

It looks like you would either have to upgrade Ubuntu or you could use the latest DEB package (1.17.1) available here:
https://jc-packages.s3-us-west-1.amazonaws.com/jc_1.17.1-1_amd64.deb

or via the Release page on github:
https://github.com/kellyjonbrazil/jc/releases/tag/v1.17.1

Then you can use `dpkg` to install the DEB.
```
dpkg -i jc_1.17.1-1_amd64.deb
```
Hope that helps!
