### ISSUE TITLE
Using custom parser as python module

### ISSUE THREAD

**Issue by ismarslomic** [kellyjonbrazil/jc#196]
I have created custom parser `crontab_h.py` and placed it in the `$HOME/.local/share/jc/jcparsers` folder.

I can successfully use this parser when executing `crontab -l | jc --crontab_h`, but when I try to use it as python module, I get error that module is not found: `ModuleNotFoundError: No module named 'jc.parsers.crontab_h'`.

**test.py**
```python
#!/usr/bin/env python3

import subprocess
import jc.parsers.crontab_h

command_output = subprocess.check_output(['crontab', '-l'], text=True)
result = jc.parsers.crontab_h.parse(command_output)
print(result)
```

**output:**
```bash
> python3 test.py
Traceback (most recent call last):
  File "//test.py", line 4, in <module>
    import jc.parsers.crontab_h
ModuleNotFoundError: No module named 'jc.parsers.crontab_h'
```

Does this mean that custom parsers cant be used as python modules?

Even if I override default parser `crontab.py` (by renaming the custom `crontab_h.py` to `crontab.py`), the _default_ parser is still imported as python module in stead of the custom one when using `import jc.parsers.crontab`.

**Comment by kellyjonbrazil** [comment]
Hi - thanks for reporting this issue! You should be able to use custom parsers as python modules, but I’ll need to properly document this. 

The `cli.py` module loads custom parsers so I’ll see if there is a simple, generic way to make it work.

**Comment by kellyjonbrazil** [comment]
Here is a not-so-elegant solution for now. I'll look into creating true interface for this:
```
import os
import sys
import jc.appdirs
data_dir = jc.appdirs.user_data_dir('jc', 'jc')
local_parsers_dir = os.path.join(data_dir, 'jcparsers')
sys.path.append(local_parsers_dir)

# now you can import your parser in the plugin directory
import my_custom_parser
```

**Comment by kellyjonbrazil** [comment]
I have a new high-level API to call the parsers, including custom plugin parsers, more easily:
```
>>> import subprocess
>>> import jc
>>>
>>> cmd_output = subprocess.check_output(['dig', 'example.com'], text=True)
>>> data = jc.parse('dig', cmd_output)
```
I'm not testing this in the `dev` branch.

**Comment by kellyjonbrazil** [comment]
The new API to call builtin and plugin parsers is now available with v1.18.1

**Comment by ismarslomic** [comment]
Thanks @kellyjonbrazil! I will test it out on sunday!

**Comment by kellyjonbrazil** [comment]
Sweet - let me know if you run into any issues. Happy to help!
