### ISSUE TITLE
Failed downloading binary jc using Ansible - 403 Forbidden

### ISSUE THREAD

**Issue by 0x217** [kellyjonbrazil/jc#205]
Hi,

I got an error (403 Forbidden) when I tried downloading binary jc using Ansible.

My code:
```
- name: install jc
  unarchive:
    src: https://jc-packages.s3-us-west-1.amazonaws.com/bin/jc-{{ jc_version }}-linux-x86_64.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
```

The error:
```
12:13:37  TASK [roles/toka-env-prep : copy-scripts | install jc] *************************
12:13:41  fatal: [192.168.1.100]: FAILED! => changed=false 
12:13:41    msg: 'Failure downloading https://jc-packages.s3-us-west-1.amazonaws.com/bin/jc-1.17.4-linux-x86_64.tar.gz", HTTP Error 403: Forbidden'
```

I succeeded download through wget command (also if i changed the user agent to ansible agent (ansible-httpget) ).

I will be happy to any assistance.

Thanks :)

**Comment by kellyjonbrazil** [comment]
Hi there - I'm not sure why it failed - maybe AWS is doing some sort of anti-bot check? I have those files set to be publicly available in S3.

One thing to note is that I have deprecated the jc-packages site and now I only use GitHub Releases to host the binaries.

For instance, the current latest version (v1.18.2) can be found at:
https://github.com/kellyjonbrazil/jc/releases/download/v1.18.2/jc-1.18.2-darwin-x86_64.tar.gz

**Comment by kellyjonbrazil** [comment]
Do you still need assistance with this? FYI, I also started adding the DEB and RPM packages to the releases again (simplified some packaging scripts) so you could also use them. The real difference between those and the binary is the packages include the man pages.
