### ISSUE TITLE
Installable for arm64 or aarch64?

### ISSUE THREAD

**Issue by manju-rn** [kellyjonbrazil/jc#210]
Let me state that this is a wonderful utility and have been using it to extract the JSON various commands.  
However, the default package in RPI - arm64 / aarch64 based system is still eons old - 1.14.  **Can we have the latest 1.18.x for arm64 bases?**

**Comment by kellyjonbrazil** [comment]
Hi @manju-rn - thanks for reporting this issue. I don’t have much control over the versions the package maintainers support on the different platforms. That version is pretty old at this point. I think you might need to open a ticket on one of the Raspbian packaging forums. 

My Pi recently broke so I’m not able to test, but is it possible to install JC via pip?

**Comment by kellyjonbrazil** [comment]
It looks like and email to these addresses may help:

[team+python@tracker.debian.org](https://repology.org/maintainer/team%2Bpython%40tracker.debian.org), [sudipm.mukherjee@gmail.com](https://repology.org/maintainer/sudipm.mukherjee%40gmail.com)
