### ISSUE TITLE
Git log parser?

### ISSUE THREAD

**Issue by emilebosch** [kellyjonbrazil/jc#221]
Would be nice to have a git log in json format, unfortunately my python skills are too  bad at the moment.

```sh
git log a..b --format=%h|%s|%an|%cs
```
And then regex it like this:

```sh
/(?<sha>.*?)\|(?<msg>.*?)\|(?<author>.*?)\|(?<date>.*)/
```

The groups will contain the json format

**Comment by kellyjonbrazil** [comment]
It does look like a parser for `git log` could be created. There are a ton of format options, though, so I'd have to understand the default and maybe most common format users tend to use.

In the mean time, though, it seems like you might be able to generate JSON Lines directly with the format option:
```
git log --format='{"hash": "%H", "author": "%an", "subject": "%s", "body": "%b", "date": %at}'
```
The only issue is that certain characters, like `\n` may not be properly escaped for JSON.

Here's how it looks on my system:
```
$ git log --format='{"hash": "%H", "author": "%an", "subject": "%s", "body": "%b", "date": %at}' | jq
{
  "hash": "e85f11c6fcad5461bae612dd5a945c20d300e59a",
  "author": "Kelly Brazil",
  "subject": "doc formatting",
  "body": "",
  "date": 1649098841
}
{
  "hash": "49a9d7b07e89696f2e022655d7256b7d6ad4bf7b",
  "author": "Kelly Brazil",
  "subject": "doc update",
  "body": "",
  "date": 1649097736
}
```

**Comment by kellyjonbrazil** [comment]
Here is a format string that does a bit of escaping for the **subject** field and omits the **body** field so you won't get escaping errors in the JSON:
```
git log --format='{"hash": "%H", "author": "%an", "subject": "%f", "date": %at}' | jq
```

**Comment by emilebosch** [comment]
Hi Kelly! Yeah the escaping was the reason why I wanted to offload it to a tool like jc. That's why I separated it with pipes and then made proper JSON out of it via the regex groups, in order to limit collisions. Ofcourse if you use a pipe in your body/subject you're still screwed 😄

**Comment by kellyjonbrazil** [comment]
I think this may end up being two parsers - one standard parser and one streaming parser because the output can be very long.

**Comment by emilebosch** [comment]
@kellyjonbrazil thank you!

**Comment by kellyjonbrazil** [comment]
@emilebosch I have a functional version of the --git-log parser available to test at the link below:

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/git_log.py

You can test the parser by copy/pasting the file above into your [plugin directory](https://github.com/kellyjonbrazil/jc#custom-parsers).

I am supporting the most common format styles:
- `oneline`
- `short`
- `medium`
- `full`
- `fuller`

and a couple of `stat` options:
- --stat
- --shortstat

Could you let me know if you run into any issues?

Thanks!

**Comment by emilebosch** [comment]
Hi @kellyjonbrazil  thanks! I totally missed this message! I'll go test it out and report back <3 thanks so far!

**Comment by kellyjonbrazil** [comment]
I'm going to release this now in the v1.18.7 release on PIP-only. If things test ok, then I'll bump the github release as well. Thanks!
