### ISSUE TITLE
New parser: update-alternatives --query

### ISSUE THREAD

**Issue by chriscroome** [kellyjonbrazil/jc#230]
The [Debian alternatives system](https://wiki.debian.org/DebianAlternatives) has a [`update-alternatives` command](https://manpages.debian.org/bullseye/dpkg/update-alternatives.1.en.html) which has a [`--query` option](https://manpages.debian.org/bullseye/dpkg/update-alternatives.1.en.html#query) which will:

> Display information about the link group like `--display` does, but in a machine parseable way (since version 1.15.0, see section [QUERY FORMAT](https://manpages.debian.org/bullseye/dpkg/update-alternatives.1.en.html#QUERY_FORMAT) below).

For example for the `editor` (omitting the Slaves output):

```bash
update-alternatives --query editor
Name: editor
Link: /usr/bin/editor
Status: manual
Best: /bin/nano
Value: /usr/bin/vim.basic

Alternative: /bin/nano
Priority: 40

Alternative: /usr/bin/nvim
Priority: 30

Alternative: /usr/bin/vim.basic
Priority: 30

Alternative: /usr/bin/vim.tiny
Priority: 15
```

Perhaps this might be a useful new parser for `jc`, the [Ansible alternatives module](https://docs.ansible.com/ansible/latest/collections/community/general/alternatives_module.html) is only able to set alternatives, not read them, so I've written some Bash to use as a Ansible `facts.d` script for converting the output into JSON:

```bash
#!/usr/bin/env bash

set -euo pipefail

jo $(
  echo "${1}"=$( 
    if query=$(update-alternatives --query "${1}")
    then
      declare -a alternatives=()
      readarray -t alternatives < <(grep -e '^Alternative' <<< "${query}" | sed 's/Alternative: //')
      declare -a priorities=()
      readarray -t priorities < <(grep -e '^Priority' <<< "${query}" | sed 's/Priority: //')
      jo name="${1}" link=$(
        grep ^Link <<< "${query}" | sed 's/^Link: //'
      ) value=$(
        grep ^Value <<< "${query}" | sed 's/^Value: //'
      ) best=$(
        grep ^Best <<< "${query}" | sed 's/Best: //'
      ) alternatives=$(
        jo -a $(
          i=0
          while [[ "${i}" -lt "${#alternatives[@]}" ]]
          do
            jo path="${alternatives[${i}]}" priority="${priorities[${i}]}" 
            ((i++))
          done
        )
      )
    else
      jo state=absent
    fi
  )
)
```
Running this script with an argument, for example `editor` results in:

```json
{
  "editor": {
    "name": "editor",
    "link": "/usr/bin/editor",
    "value": "/usr/bin/vim.basic",
    "best": "/bin/nano",
    "alternatives": [
      {
        "path": "/bin/nano",
        "priority": 40
      },
      {
        "path": "/usr/bin/nvim",
        "priority": 30
      },
      {
        "path": "/usr/bin/vim.basic",
        "priority": 30
      },
      {
        "path": "/usr/bin/vim.tiny",
        "priority": 15
      }
    ]
  }
}
```

**Comment by kellyjonbrazil** [comment]
Thank you for the parser suggestion. Sweet script! I’ll definitely take a look at this.

**Comment by kellyjonbrazil** [comment]
Is this fairly representative of the output? Are there any fields you see missing?
```
Name: editor
Link: /usr/bin/editor
Slaves:
 editor.1.gz /usr/share/man/man1/editor.1.gz
 editor.da.1.gz /usr/share/man/da/man1/editor.1.gz
 editor.de.1.gz /usr/share/man/de/man1/editor.1.gz
 editor.fr.1.gz /usr/share/man/fr/man1/editor.1.gz
 editor.it.1.gz /usr/share/man/it/man1/editor.1.gz
 editor.ja.1.gz /usr/share/man/ja/man1/editor.1.gz
 editor.pl.1.gz /usr/share/man/pl/man1/editor.1.gz
 editor.ru.1.gz /usr/share/man/ru/man1/editor.1.gz
Status: auto
Best: /bin/nano
Value: /bin/nano

Alternative: /bin/ed
Priority: -100
Slaves:
 editor.1.gz /usr/share/man/man1/ed.1.gz

Alternative: /bin/nano
Priority: 40
Slaves:
 editor.1.gz /usr/share/man/man1/nano.1.gz

Alternative: /usr/bin/vim.basic
Priority: 30
Slaves:
 editor.1.gz /usr/share/man/man1/vim.1.gz
 editor.da.1.gz /usr/share/man/da/man1/vim.1.gz
 editor.de.1.gz /usr/share/man/de/man1/vim.1.gz
 editor.fr.1.gz /usr/share/man/fr/man1/vim.1.gz
 editor.it.1.gz /usr/share/man/it/man1/vim.1.gz
 editor.ja.1.gz /usr/share/man/ja/man1/vim.1.gz
 editor.pl.1.gz /usr/share/man/pl/man1/vim.1.gz
 editor.ru.1.gz /usr/share/man/ru/man1/vim.1.gz

Alternative: /usr/bin/vim.tiny
Priority: 15
Slaves:
 editor.1.gz /usr/share/man/man1/vim.1.gz
 editor.da.1.gz /usr/share/man/da/man1/vim.1.gz
 editor.de.1.gz /usr/share/man/de/man1/vim.1.gz
 editor.fr.1.gz /usr/share/man/fr/man1/vim.1.gz
 editor.it.1.gz /usr/share/man/it/man1/vim.1.gz
 editor.ja.1.gz /usr/share/man/ja/man1/vim.1.gz
 editor.pl.1.gz /usr/share/man/pl/man1/vim.1.gz
 editor.ru.1.gz /usr/share/man/ru/man1/vim.1.gz
```
Looks pretty simple to parse - I can probably get this into the next release.

The schema could look something like this:
```
{
    "name":                     string,
    "link":                     string,
    "slaves": [
        {
            "name":             string,
            "link":             string
        }
    ],
    "status":                   string,
    "best":                     string,
    "value":                    string,
    "alternatives": [
        {
            "name":             string,
            "priority":         integer,
            "slaves": [
                {
                    "name":     string,
                    "link":     string
                }
            ]
        }
    ]
}
```

**Comment by chriscroome** [comment]
Yes to all the above!

I've had a quick scan through the output of this:

```bash
for alt in $(update-alternatives --get-selections | awk '{ print $1 }'); do update-alternatives --query ${alt}; done | less
```

And I didn't see anything that didn't match the pattern above.

I agree that it would be good to also generate JSON from `update-alternatives --get-selections`.

I'm currently working on a Ansible role for which I picked a slightly different format, a dictionary rather than a list:

```yml
alternatives_update:
  'php':
    state: present
    link: /usr/bin/php
    alternatives:
      - path: /usr/bin/php7.4
        state: present
        priority: 50
      - path: /usr/bin/php8.0
        state: present
        priority: 80
      - path: /usr/bin/php8.1
        state: present
        priority: 81
  'php-fpm.sock':
    link: /run/php/php-fpm.sock
    state: present
    alternatives:
      - path: /run/php/php7.4-fpm.sock
        state: present
        priority: 74
      - path: /run/php/php8.0-fpm.sock
        state: present
        priority: 80
      - path: /run/php/php8.1-fpm.sock
        state: present
        priority: 81
```

But your format probably makes more sense so I'll look at updating it, your version in YAML is this:

```yml
name: string
link: string
slaves:
  - name: string
    path: string
status: string
best: string
value: string
alternatives:
  - name: string
    priority: integer
    slaves:
      - name: string
        path: string
```

**Comment by kellyjonbrazil** [comment]
I notice you have a `state` field in your examples. Is that needed in the `jc` parser?

**Comment by chriscroome** [comment]
Sorry I should have omitted that above, `state` is just something I added, when `state: absent` I'll use Ansible to remove selection groups or alternatives -- unless `jc` adds additional variables for any other parsers then I don't think you should for `update-alternatives`.

**Comment by kellyjonbrazil** [comment]
I have a working version in `dev` for `update-alternatives --query` if you would like to test:

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/update_alt_q.py

You can copy this file to your [plugin folder](https://github.com/kellyjonbrazil/jc#custom-parsers) and it should work like `update-alternatives --query | jc --update-alt-q` or `jc update-alternatives --query`.

**Comment by kellyjonbrazil** [comment]
A working version of the `update-alternatives --get-selections` parser is also available in `dev` if you would like to test:

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/update_alt_gs.py

Usage is similar: `update-alternatives --get-selections | jc --update-alt-gs` or `jc update-alternatives --get-selections`

**Comment by chriscroome** [comment]
Thanks, I've done this:

```bash
pip install jc
mkdir -p "${HOME}/.local/share/jc/jcparsers"
cd "${HOME}/.local/share/jc/jcparsers"
wget https://raw.githubusercontent.com/kellyjonbrazil/jc/dev/jc/parsers/update_alt_q.py 
cd
update-alternatives --get-selections | jc --update-alt-q
```

And the output is:

```
jc:     missing or incorrect arguments
```

Have I missed something? I also tried:

```
update-alternatives --query editor | jc --update-alt-q
```

And that has the same result.

**Comment by chriscroome** [comment]
Sorry, I half read the first of your comments above via email and then the second via the web and got them mixed up... trying again...

```
cd "${HOME}/.local/share/jc/jcparsers"
wget https://raw.githubusercontent.com/kellyjonbrazil/jc/dev/jc/parsers/update_alt_gs.py -O update_alt_gs.py
wget https://raw.githubusercontent.com/kellyjonbrazil/jc/dev/jc/parsers/update_alt_q.py -O update_alt_q.py
cd
update-alternatives --query editor | jc --update-alt-q

jc:     missing or incorrect arguments

update-alternatives --get-selections | jc --update-alt-gs

jc:     missing or incorrect arguments
```

Am I doing something wrong?

**Comment by kellyjonbrazil** [comment]
I tried the above on an ubuntu VM and it seemed to work. What happens if you do `jc -h` and `jc -ap`. Does `--update-alt-q` show up at the bottom?
```
$ jc -h
<snip>
        --xrandr         `xrandr` command parser
        --yaml           YAML file parser
        --zipinfo        `zipinfo` command parser
        --update-alt-q   `update-alternatives --query` command parser

Options:
        -a    about jc
        -C    force color output even when using pipes (overrides -m)
        -d    debug (-dd for verbose debug)
        -h    help (-h --parser_name for parser documentation)
        -m    monochrome output
        -p    pretty print output
        -q    quiet - suppress parser warnings (-qq to ignore streaming errors)
        -r    raw JSON output
        -u    unbuffer output
        -v    version info

Examples:
        Standard Syntax:
            $ dig www.google.com | jc --dig -p

        Magic Syntax:
            $ jc -p dig www.google.com

        Parser Documentation:
            $ jc -h --dig
$ jc -ap
<snip>
    {
      "name": "update_alt_q",
      "argument": "--update-alt-q",
      "version": "1.0",
      "description": "`update-alternatives --query` command parser",
      "author": "Kelly Brazil",
      "author_email": "kellyjonbrazil@gmail.com",
      "compatible": [
        "linux"
      ],
      "magic_commands": [
        "update-alternatives --query"
      ],
      "plugin": true
    }
  ]
}
```

**Comment by chriscroome** [comment]
Weird, yes the plugins are there:

```bash
jc -h 2>&1 | grep update
        --update_alt_gs  `update-alternatives --get-selections` command parser
        --update_alt_q   `update-alternatives --query` command parser
```

And `jc -ap` also lists the two plugins at the end...

**Comment by kellyjonbrazil** [comment]
Funny because this feels like you have an older version of `jc`. Was this recently installed? Curious of the version of `jc` running. I did recently add plugin support for parser-names containing dashes.

**Comment by chriscroome** [comment]
I was just wondering if this was the issue also, I appear to be running the Debian Buster version:

```bash
cat $(which jc) | head
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'jc==1.14.3','console_scripts','jc'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'jc==1.14.3'

try:
    from importlib.metadata import distribution
```

**Comment by chriscroome** [comment]
This did the trick...

```bash
wget "https://github.com/kellyjonbrazil/jc/releases/download/v1.18.6/jc_1.18.6-1_amd64.deb"
gdebi jc_1.18.6-1_amd64.deb
```

Now both these work:

```
update-alternatives --query editor | jc --update-alt-q
update-alternatives --get-selections | jc --update-alt-gs
```

That's fantastic! 

I'll stop writing Bash to parse the output and write an Ansible role to install the latest version of `jc` instead!

**Comment by kellyjonbrazil** [comment]
Right on! I still need to write some tests and then I'll add these into v1.18.7. I'll probably release it by next week some time.  Thanks for your contributions!

**Comment by chriscroome** [comment]
Thanks again for your work on this @kellyjonbrazil, I've written [an Ansible role to install jc using debs from GitHub](https://galaxy.ansible.com/chriscroome/jc) and I'll now work on a role that uses the parsers you have written to update alternatives.

**Comment by chriscroome** [comment]
One thought, the `name` which is in caps here:

```
{
    "name":                     string,
    "link":                     string,
    "slaves": [
        {
            "name":             string,
            "path":             string
        }
    ],
    "status":                   string,
    "best":                     string,
    "value":                    string,    # null if 'none'?
    "alternatives": [
        {
            "NAME":             string,
            "priority":         integer,
            "slaves": [
                {
                    "name":     string,
                    "path":     string
                }
            ]
        }
    ]
}
```

Is described [like this in the man page](https://manpages.debian.org/bullseye/dpkg/update-alternatives.1.en.html#alternative~2):

> alternative (or alternative path)
>    The name of a specific file in the filesystem, which may be made accessible via a generic name using the alternatives system.

Since it is a absolute path it might make more sense to use `path` or even `alternative` to avoid potential confusion?

**Comment by kellyjonbrazil** [comment]
Yeah, that makes sense. There are a lot of ‘name’s there that can get confusing. I can change that no problem.

**Comment by chriscroome** [comment]
Thinking about this some more I think the best approach would be to stick with [what is in the `--query` out put and what used in the manpage](https://manpages.debian.org/bullseye/dpkg/update-alternatives.1.en.html), so use `alternative` rather than `name` for `Alternative`, eg [like in this copy of the file](https://github.com/chriscroome/jc/blob/dev/jc/parsers/update_alt_q.py), I've tested this and created [a pull request for this](https://github.com/kellyjonbrazil/jc/pull/233) in case that helps.

**Comment by kellyjonbrazil** [comment]
I'm going to release this now in the v1.18.7 release on PIP-only. If things test ok, then I'll bump the github release as well. Thanks!

**Comment by chriscroome** [comment]
There seems to be a problem here:

```bash
update-alternatives --query php-fpm.sock
Name: php-fpm.sock
Link: /run/php/php-fpm.sock
Status: auto
Best: /run/php/php8.1-fpm.sock
Value: /run/php/php8.1-fpm.sock

Alternative: /run/php/php7.4-fpm.sock
Priority: 74

Alternative: /run/php/php8.0-fpm.sock
Priority: 80

Alternative: /run/php/php8.1-fpm.sock
Priority: 81
```

```bash
jc -p update-alternatives --query php-fpm.sock
{
  "name": "php-fpm.sock",
  "link": "/run/php/php-fpm.sock",
  "status": "auto",
  "best": "/run/php/php8.1-fpm.sock",
  "value": "/run/php/php8.1-fpm.sock",
  "alternatives": [
    {
      "alternative": "/run/php/php8.1-fpm.sock",
      "priority": 81
    }
  ]
}
```

Why are the alternatives missing from the JSON version? Any suggestions regarding how I might help debug this?

**Comment by kellyjonbrazil** [comment]
Yep, was a little bug in the logic. Cleaned that up and the fix will go into v1.18.8. You can test it here:

https://github.com/kellyjonbrazil/jc/blob/master/jc/parsers/update_alt_q.py

**Comment by chriscroome** [comment]
Great, thanks, I've tested it and it is working as expected, `jc -p update-alternatives --query php-fpm.sock` now results in:

```yml
{
  "name": "php-fpm.sock",
  "link": "/run/php/php-fpm.sock",
  "status": "auto",
  "best": "/run/php/php8.1-fpm.sock",
  "value": "/run/php/php8.1-fpm.sock",
  "alternatives": [
    {
      "alternative": "/run/php/php7.4-fpm.sock",
      "priority": 74
    },
    {
      "alternative": "/run/php/php8.0-fpm.sock",
      "priority": 80
    },
    {
      "alternative": "/run/php/php8.1-fpm.sock",
      "priority": 81
    }
  ]
}
```

I'm going to try to find time this evening to test a lot of other alternatives but first I want to write a Ansible `yq` role so I can generate YAML versions of the queries for feeding into the Ansible alternatives role I'm working on... BTW have you ever considered adding an option for `jc` to output YAML directly?

**Comment by chriscroome** [comment]
Cheers, have done https://github.com/kellyjonbrazil/jc/issues/237

**Comment by chriscroome** [comment]
The Ansible role I was planning to use to test the `jc` JSON `update-alternatives --query` output doesn't seem to work for alternatives with lots of slaves like `aptitude` and `editor` and I won't have time to look at this more until next week sometime -- however I can't see any `jc` bugs :-)
