### ISSUE TITLE
Package managers

### ISSUE THREAD

**Issue by kdeldycke** [kellyjonbrazil/jc#232]
I stumbled upon this project and it is epic! 😍

I just wanted to talk about my own open-source project called [Meta Package Manager](https://github.com/kdeldycke/meta-package-manager). It is a Python-based CLI that is unifying multiple package manager.

I can't help but notice some similarities with the goal of `jc`, as it allows you to perform the usual operations on multiple package managers and get a JSON output.

For example, here is how to perform a search of the `broot` package on `brew` and `cask` and get the result in JSON:
```shell-session
$ mpm --brew --cask --output-format json search "broot"
{
    "brew": {
        "errors": [],
        "id": "brew",
        "name": "Homebrew Formulae",
        "packages": [
            {
                "id": "broot",
                "latest_version": null,
                "name": "broot"
            },
            {
                "id": "root",
                "latest_version": null,
                "name": "root"
            },
            {
                "id": "brook",
                "latest_version": null,
                "name": "brook"
            },
            {
                "id": "boost",
                "latest_version": null,
                "name": "boost"
            }
        ]
    },
    "cask": {
        "errors": [],
        "id": "cask",
        "name": "Homebrew Cask",
        "packages": [
            {
                "id": "brook",
                "latest_version": null,
                "name": "brook"
            }
        ]
    }
}
```

So I don't know if package managers in general are in the scope of `jc` (I noticed the [support for `dpkg`](https://kellyjonbrazil.github.io/jc/docs/parsers/dpkg_l), but if you're looking to bootstrap support for some of them, maybe there are some stuff to reuse from my project. Anyway, if you see any potential for a collaboration, feel free to reach me out! :)

**Comment by kellyjonbrazil** [comment]
Awesome! Yes, I will take a look because I see jc complimenting various automation and DevOps use cases, and I think package management is in scope. Thanks for taking a look at jc!
