### ISSUE TITLE
Add a brew install

### ISSUE THREAD

**Issue by sledigabel** [kellyjonbrazil/jc#24]
Installing it with `pip` is great, but it would be fantastic to add it to brew as well.

**Comment by kellyjonbrazil** [comment]
Cool idea! I've not packaged for brew before but I'll check it out.

**Comment by kellyjonbrazil** [comment]
After doing some more research on this I’m going to table this request for now. It looks like there is potential for conflicts if brew is used to install jc and pip is later used to upgrade it and/or its dependencies. If someone has more experience in this area I am open to feedback and could be persuaded if there is more demand for this feature.

**Comment by kellyjonbrazil** [comment]
Homebrew packaging completed in v1.10.6.

**Comment by sledigabel** [comment]
Awesome work 👏
