### ISSUE TITLE
New parser: my_print_defaults

### ISSUE THREAD

**Issue by chriscroome** [kellyjonbrazil/jc#253]
Both [MariaDB](https://mariadb.com/kb/en/my_print_defaults/) and [MySQL](https://dev.mysql.com/doc/refman/8.0/en/my-print-defaults.html) provide `my_print_defaults` for displaying MariaDB / MySQL configuration.

They are not exactly the same, for example the MySQL version has [a `-s` option](https://dev.mysql.com/doc/refman/8.0/en/my-print-defaults.html#option_my_print_defaults_show) and the MariaDB version doesn't, but I don't think the differences would matter for a `jc` parser.

Usage examples:

```bash
my_print_defaults -c /home/example/.my.cnf client
--user=example
--password=XXX
--socket=/run/mysqld/mysqld.sock

my_print_defaults -c /etc/mysql/mariadb.conf.d/50-server.cnf mysqld
--user=mysql
--pid-file=/var/run/mysqld/mysqld.pid
--socket=/var/run/mysqld/mysqld.sock
--port=3306
--basedir=/usr
--datadir=/var/lib/mysql
--tmpdir=/tmp
--lc-messages-dir=/usr/share/mysql
--skip-external-locking
--bind-address=127.0.0.1
--key_buffer_size=16M
--max_allowed_packet=64M
--thread_stack=192K
--thread_cache_size=8
--myisam_recover_options=BACKUP
--max_connections=80
--max_user_connections=0
--table_cache=64
--thread_concurrency=10
--open_files_limit=122880
--table_open_cache=6000
--tmp_table_size=32M
--join_buffer_size=8M
--max_heap_table_size=32M
--query_cache_type=0
--query_cache_limit=0
--query_cache_size=0
--log_error=/var/log/mysql/error.log
--expire_logs_days=10
--max_binlog_size=100M
--innodb_buffer_pool_size=1G
--innodb_log_file_size=256M
--character-set-server=utf8mb4
--collation-server=utf8mb4_general_ci
```

I think that producing JSON would be a matter of, for each line of results, removing the `--` at the start, then splitting the string at the `=` sign.

Note that [the use of `-` or `_` in configuration options is interchangable](https://stackoverflow.com/q/7736395), perhaps it would make sense to change all dashes in variable names into underscores for consistency?

**Comment by kellyjonbrazil** [comment]
Looks like the —kv parser might work well for those.

**Comment by chriscroome** [comment]
Thanks, sorry I didn't think of that, it does work fairly well, for example:

```
my_print_defaults -c /etc/mysql/mariadb.conf.d/50-server.cnf mysqld | jc --kv -p
{
  "--user": "mysql",
  "--pid-file": "/var/run/mysqld/mysqld.pid",
  "--socket": "/var/run/mysqld/mysqld.sock",
  "--port": "3306",
  "--basedir": "/usr",
  "--datadir": "/var/lib/mysql",
  "--tmpdir": "/tmp",
  "--lc-messages-dir": "/usr/share/mysql",
  "--skip-external-locking": "",
  "--bind-address": "127.0.0.1",
  "--key_buffer_size": "16M",
  "--max_allowed_packet": "64M",
  "--thread_stack": "192K",
  "--thread_cache_size": "8",
  "--myisam_recover_options": "BACKUP",
  "--max_connections": "80",
  "--max_user_connections": "0",
  "--table_cache": "64",
  "--thread_concurrency": "10",
  "--open_files_limit": "122880",
  "--table_open_cache": "6000",
  "--tmp_table_size": "32M",
  "--join_buffer_size": "8M",
  "--max_heap_table_size": "32M",
  "--query_cache_type": "0",
  "--query_cache_limit": "0",
  "--query_cache_size": "0",
  "--log_error": "/var/log/mysql/error.log",
  "--expire_logs_days": "10",
  "--max_binlog_size": "100M",
  "--innodb_buffer_pool_size": "1G",
  "--innodb_log_file_size": "256M",
  "--character-set-server": "utf8mb4",
  "--collation-server": "utf8mb4_general_ci"
}
```

I guess something else could then be used to remove sort out the keys, for example `sed 's/^--//' | sed 's/-/_/g'`.

**Comment by kellyjonbrazil** [comment]
Cool! Depending on your use case, you probably don’t really need to worry too much about the key names.  Unless maybe  you are exposing it to a downstream user for something.

**Comment by chriscroome** [comment]
The [mysqltuner](https://packages.debian.org/bullseye/mysqltuner} Perl script has a `--json` output option available after `libjson-perl` has been installed and this together with `my_print_defaults` and the `jc --kv` parser results in so much JSON data that I think this issue can be closed! Thanks for considering it @kellyjonbrazil

**Comment by kellyjonbrazil** [comment]
Yeah I can fix that. I already do it for double quotes but didn’t think to do it for single quotes. You can use the -r or raw option to get the quotes back, if needed.
