### ISSUE TITLE
Add Bash and Zsh completions to Deb and RPM packages

### ISSUE THREAD

**Issue by kellyjonbrazil** [kellyjonbrazil/jc#259]
It might make sense to include the completion scripts in the `.deb` and `.rpm` packages?

_Originally posted by @chriscroome in https://github.com/kellyjonbrazil/jc/issues/252#issuecomment-1171368085_

**Comment by kellyjonbrazil** [comment]
Should have this working in v1.20.2.

**Comment by kellyjonbrazil** [comment]
I uploaded a new DEB and RPM in v1.20.2 that should install the completion scripts. Could you let me know if that looks ok or if you run into any issues? Thanks!

**Comment by chriscroome** [comment]
Looks good to me :+1: 

FWIW I've updated the Ansible role I've written so that the [Bash completion is not installed for this version or greater](https://github.com/webarch-coop/ansible-role-jc/blob/ef6324338cff8d3367f6bc13223af91cb3080eac/tasks/main.yml?#L119).
