### ISSUE TITLE
incorrect parsing of dpkg-l

### ISSUE THREAD

**Issue by awasaw** [kellyjonbrazil/jc#264]
I'm using a localized version of Ubuntu and I've run into a problem with dpkg-l not parsing correctly.
In my case, the word "Architecture" first occurs in the nmap-common package. because of this, most of the packets are lost, and the field names do not match

```
||/ Имя                                      Версия                                     Архитектура  Описание
+++-========================================-==========================================-============-================================================================================
ii  nmap                                     7.91+dfsg1+really7.80+dfsg1-2build1        amd64        The Network Mapper
ii  nmap-common                              7.91+dfsg1+really7.80+dfsg1-2build1        all          Architecture independent files for nmap
ii  ntfs-3g                                  1:2021.8.22-3ubuntu1.1                     amd64        read/write NTFS driver for FUSE
ii  numix-gtk-theme                          2.6.7-6                                    all          modern flat theme from the Numix project
```
```[
  {
    "ii": "ii",
    "nmap-common": "ntfs-3g",
    "7.91+dfsg1+really7.80+dfsg1-2build1": "1:2021.8.22-3ubuntu1.1",
    "all": "amd64",
    "architecture": "read/write",
    "independent": "NTFS",
    "files": "driver",
    "for": "for",
    "nmap": "FUSE"
  },
  {
    "ii": "ii",
    "nmap-common": "numix-gtk-theme",
    "7.91+dfsg1+really7.80+dfsg1-2build1": "2.6.7-6",
    "all": "all",
    "architecture": "modern",
    "independent": "flat",
    "files": "theme",
    "for": "from",
    "nmap": "the Numix project"
  }
]
```

**Comment by kellyjonbrazil** [comment]
Hi there - thank you for reporting this issue! Have you tried changing the locale to `C` to see if that helps?
```
$ LANG=C dpkg -l | jc --dpkg-l
```

**Comment by awasaw** [comment]
Replacing ` if 'Architecture' in line:` to `if '||/' in line:` or just `if '+++-===' in line:`  might solve the problem

**Comment by kellyjonbrazil** [comment]
Ah, I see. I think this would be best supported with a custom plugin parser. You could take the existing [`dpkg-l` parser](https://github.com/kellyjonbrazil/jc/blob/master/jc/parsers/dpkg_l.py), copy it to your `jc` [plugins folder](https://github.com/kellyjonbrazil/jc#custom-parsers), and modify it to meet your needs.

**Comment by kellyjonbrazil** [comment]
Hi there,

I created a custom parser that I think will work:
https://gist.github.com/kellyjonbrazil/88ce9d2e2e109338e084ede4a63b69f4

You can put this file named `dpkg_l_ru.py` in your `jc` plugin directory:

## Custom Parsers
Custom local parser plugins may be placed in a `jc/jcparsers` folder in your local "App data directory":

Linux/unix: `$HOME/.local/share/jc/jcparsers`
macOS: `$HOME/Library/Application Support/jc/jcparsers`
Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

Hope that helps!

**Comment by kellyjonbrazil** [comment]
I'll go ahead and close this issue. Let me know if you run into any other issues.
