### ISSUE TITLE
make jc switch locale automatically

### ISSUE THREAD

**Issue by dejj** [kellyjonbrazil/jc#27]
Some parsers presuppose English locale.
Currently I have to call e.g. `LANG=en jc df`.
Can `jc` or the parsers be modified to use the required language automatically?

**Comment by kellyjonbrazil** [comment]
I'll look into this. Could you send some samples of the output from your computer (sanitized, if need be). Which parsers are you seeing this issue with?

e.g.:
```
df > df.out
```

Thanks!

**Comment by kellyjonbrazil** [comment]
as a quick workaround, could you let me know if creating the following alias works?
```
alias jc='LANG=en jc'
```

**Comment by dejj** [comment]
> alias jc='LANG=en_US.UTF-8 jc'
Good idea! It does work :)

**Comment by kellyjonbrazil** [comment]
Sweet! I also like that trick to alias `jcp` to `jc -p`. :)

**Comment by jonhattan** [comment]
Better use the default locale C: `LANG=C jc df -h`

**Comment by kellyjonbrazil** [comment]
> as a quick workaround, could you let me know if creating the following alias works?
> 
> ```
> alias jc='LANG=en_US.UTF-8 jc'
> ```

Note that this only works when using the "magic" syntax. If you are using the standard piping of STDIN to STDOUT, then make sure to add the `LANG=C` assignment before the command you want to convert. E.g.:
```
LANG=C ls -l /usr/bin | jc --ls
```
