### ISSUE TITLE
Error parsing data from "lsusb -v"

### ISSUE THREAD

**Issue by g-v-egidy** [kellyjonbrazil/jc#271]
While parsing plain lsusb output is fine, the output from `lsusb -v` gives an error:
```
# lsusb -s 002:002 -v | jc --lsusb -d
Traceback (most recent call last):
  File "/usr/bin/jc", line 33, in <module>
    sys.exit(load_entry_point('jc==1.20.2', 'console_scripts', 'jc')())
  File "/usr/lib/python3.10/site-packages/jc/cli.py", line 619, in main
    result = parser.parse(data,
  File "/usr/lib/python3.10/site-packages/jc/parsers/lsusb.py", line 835, in parse
    if lsusb._populate_lists(line):
  File "/usr/lib/python3.10/site-packages/jc/parsers/lsusb.py", line 521, in _populate_lists
    self.hub_port_status_list.append(self._add_hub_port_status_attributes(line))
  File "/usr/lib/python3.10/site-packages/jc/parsers/lsusb.py", line 395, in _add_hub_port_status_attributes
    second_split = first_split[1].split(maxsplit=1)
IndexError: list index out of range
```

The lsusb output looks like this:
```
# lsusb -s 002:002 -v

Bus 002 Device 002: ID 8087:8000 Intel Corp. Integrated Rate Matching Hub
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 
  bDeviceProtocol         1 Single TT
  bMaxPacketSize0        64
  idVendor           0x8087 Intel Corp.
  idProduct          0x8000 Integrated Rate Matching Hub
  bcdDevice            0.04
  iManufacturer           0 
  iProduct                0 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0019
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 Full speed (or root) hub
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0002  1x 2 bytes
        bInterval              12
Hub Descriptor:
  bLength              11
  bDescriptorType      41
  nNbrPorts             8
  wHubCharacteristic 0x0009
    Per-port power switching
    Per-port overcurrent protection
    TT think time 8 FS bits
  bPwrOn2PwrGood        0 * 2 milli seconds
  bHubContrCurrent      0 milli Ampere
  DeviceRemovable    0x00 0x00
  PortPwrCtrlMask    0xff 0xff
 Hub Port Status:
   Port 1: 0000.0100 power
   Port 2: 0000.0100 power
   Port 3: 0000.0100 power
   Port 4: 0000.0100 power
   Port 5: 0000.0100 power
   Port 6: 0000.0100 power
   Port 7: 0000.0100 power
   Port 8: 0000.0100 power
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 
  bDeviceProtocol         0 Full speed (or root) hub
  bMaxPacketSize0        64
  bNumConfigurations      1
Device Status:     0x0001
  Self Powered
```

This is on Fedora Linux 36 with `LANG=en_US.utf8` and usbutils-014-2.fc36.x86_64. jc used was still version 1.20.2, but it doesn't look like the lsusb parser has been modified recently.

Similar errors occur whith the other usb devices. I just posted the data from one device for brevity, but could post full output or more information if helpful.

**Comment by kellyjonbrazil** [comment]
Thank you for reporting this issue! The `lsusb` parser is a special sort of beast, so hopefully this won't be too difficult to track down. Thanks for the sample - I'll see if I can find the issue here.

**Comment by kellyjonbrazil** [comment]
Ah, it looks like it has to do with the existence of the `Device Qualifier (for other device speed):` section. I don't have a handler for that (don't think I saw it before in my samples).  Looks like that shouldn't be too difficult to fix.

**Comment by kellyjonbrazil** [comment]
Hi there!

I added a handler for `device_qualifier` to the parser. It seems to work with the example above, but could you test it out with your other samples?

You can put this file in your `jc` plugin directory:
https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/lsusb.py

Here are the plugin directories for different OS versions:
- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

Thanks!

**Comment by g-v-egidy** [comment]
Thanks for working on this.

I tried out your new parser version and it indeed fixes the device data i posted in my initial report.

Unfortunately some other hub-like devices still don't work as they have some more fields. I guess I should have posted their data from the get-go.

Here are the `lsusb -v` dumps of all devices that still don't work from 3 different systems:
[lsusb-errors.zip](https://github.com/kellyjonbrazil/jc/files/9226582/lsusb-errors.zip)

**Comment by kellyjonbrazil** [comment]
No worries - thanks for the additional samples. I'll look into the issue.

**Comment by kellyjonbrazil** [comment]
It looks like the issue with these files was an additional `Binary Object Store Descriptor` section. I put in a handler to just ignore this section for now, which fixes the issue on all of the sample files. Could you let me know if that works for you? Thanks!

**Comment by g-v-egidy** [comment]
With your newest patch parsing lsusb -v passes on all my systems.

Thank you very much for fixing this so fast.
