### ISSUE TITLE
enhancement: parsing for top snapshot

### ISSUE THREAD

**Issue by fredjohnsen** [kellyjonbrazil/jc#28]
I know top runs as a process but parsing it is a mess it would be great to add this unless I am just missing it in your documentation. thanks.

**Comment by kellyjonbrazil** [comment]
I didn't consider `top` since there is `ps`, `free`, etc. What would the use case look like? Something like:
```
top > top.out
```
That seems to generate pretty ugly output, though.

**Comment by aapjeisbaas** [comment]
@fredjohnsen I'd just use the ps output, is there a specific value you're looking for from top?
If you are looking for top 5 cpu usage you might take a look at:
```txt
ps aux | jc --ps | jq 'sort_by(.cpu_percent) | .[-5:-1]'
```
And for memory based top 5 processes:
```txt
ps aux | jc --ps | jq 'sort_by(.mem_percent) | .[-5:-1]'
```
Hope this helps.

**Comment by kellyjonbrazil** [comment]
I’m going to close this feature request because there are other ways to get to the data top provides. I’m also not sure what the use case would be here since top uses an interactive UI.
