### ISSUE TITLE
please support parsing the `udevadm info` result

### ISSUE THREAD

**Issue by braindevices** [kellyjonbrazil/jc#291]
udevadm info can give lots of useful info when we try to have automatic usb device or pci device handling. It will be nice if we can parse the `udevadm info --query=all <device>` result.

- The `output prefixes: P, L, etc` can be found [here](https://man.archlinux.org/man/udevadm.8.en).
- the value pair can be list which is separated by space.

The expected format maybe:
```
{
  "P": "value",
  "L": "value",
  "S": [...],
  ...
  "E": {<key:val pairs>}

}
```

**Comment by kellyjonbrazil** [comment]
Hi there - thanks for the parser suggestion! I'll take a closer look at `udevadm` since I'm not very familiar with its output.

Here is what it outputs on my VM. Is this representative or is it missing anything?
```
$ udevadm info --query=all /dev/sda
P: /devices/pci0000:00/0000:00:10.0/host32/target32:0:0/32:0:0:0/block/sda
N: sda
L: 0
S: disk/by-path/pci-0000:00:10.0-scsi-0:0:0:0
E: DEVPATH=/devices/pci0000:00/0000:00:10.0/host32/target32:0:0/32:0:0:0/block/sda
E: DEVNAME=/dev/sda
E: DEVTYPE=disk
E: MAJOR=8
E: MINOR=0
E: SUBSYSTEM=block
E: USEC_INITIALIZED=6100111
E: SCSI_TPGS=0
E: SCSI_TYPE=disk
E: SCSI_VENDOR=VMware,
E: SCSI_VENDOR_ENC=VMware,\x20
E: SCSI_MODEL=VMware_Virtual_S
E: SCSI_MODEL_ENC=VMware\x20Virtual\x20S
E: SCSI_REVISION=1.0
E: ID_SCSI=1
E: ID_VENDOR=VMware_
E: ID_VENDOR_ENC=VMware\x2c\x20
E: ID_MODEL=VMware_Virtual_S
E: ID_MODEL_ENC=VMware\x20Virtual\x20S
E: ID_REVISION=1.0
E: ID_TYPE=disk
E: MPATH_SBIN_PATH=/sbin
E: ID_BUS=scsi
E: ID_PATH=pci-0000:00:10.0-scsi-0:0:0:0
E: ID_PATH_TAG=pci-0000_00_10_0-scsi-0_0_0_0
E: ID_PART_TABLE_UUID=a5bd0c01-4210-46f2-b558-5c11c209a8f7
E: ID_PART_TABLE_TYPE=gpt
E: DEVLINKS=/dev/disk/by-path/pci-0000:00:10.0-scsi-0:0:0:0
E: TAGS=:systemd:
```
Thanks!

**Comment by braindevices** [comment]
@kellyjonbrazil this output does show most common output, however, there are lots of other prefixs did not present here. And there can be multiple S: if you choose a disk that has id, partlabel, uuid, etc.

**Comment by kellyjonbrazil** [comment]
I have added a `udevadm` parser in the `dev` branch. You can test it by copying the [parser file](https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/udevadm.py) to your `jc` plugin directory.

- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

If you could send me more samples for testing, that would be great. Here is what it looks like, so far. I'd like to see other examples so I can see if it makes sense to convert any values to integer, etc.

```
$ udevadm info --query=all /dev/sda | jc --udevadm -p
{
  "P": "/devices/pci0000:00/0000:00:10.0/host32/target32:0:0/32:0:0:0/block/sda",
  "N": "sda",
  "L": "0",
  "S": [
    "disk/by-path/pci-0000:00:10.0-scsi-0:0:0:0"
  ],
  "E": {
    "DEVPATH": "/devices/pci0000:00/0000:00:10.0/host32/target32:0:0/32:0:0:0/block/sda",
    "DEVNAME": "/dev/sda",
    "DEVTYPE": "disk",
    "MAJOR": "8",
    "MINOR": "0",
    "SUBSYSTEM": "block",
    "USEC_INITIALIZED": "6100111",
    "SCSI_TPGS": "0",
    "SCSI_TYPE": "disk",
    "SCSI_VENDOR": "VMware,",
    "SCSI_VENDOR_ENC": "VMware,\\x20",
    "SCSI_MODEL": "VMware_Virtual_S",
    "SCSI_MODEL_ENC": "VMware\\x20Virtual\\x20S",
    "SCSI_REVISION": "1.0",
    "ID_SCSI": "1",
    "ID_VENDOR": "VMware_",
    "ID_VENDOR_ENC": "VMware\\x2c\\x20",
    "ID_MODEL": "VMware_Virtual_S",
    "ID_MODEL_ENC": "VMware\\x20Virtual\\x20S",
    "ID_REVISION": "1.0",
    "ID_TYPE": "disk",
    "MPATH_SBIN_PATH": "/sbin",
    "ID_BUS": "scsi",
    "ID_PATH": "pci-0000:00:10.0-scsi-0:0:0:0",
    "ID_PATH_TAG": "pci-0000_00_10_0-scsi-0_0_0_0",
    "ID_PART_TABLE_UUID": "a5bd0c01-4210-46f2-b558-5c11c209a8f7",
    "ID_PART_TABLE_TYPE": "gpt",
    "DEVLINKS": "/dev/disk/by-path/pci-0000:00:10.0-scsi-0:0:0:0",
    "TAGS": ":systemd:"
  }
}
```

**Comment by braindevices** [comment]
@kellyjonbrazil it looks fantastic. 
- about the integer conversion. The only thing make sense is the L. The key in E dict can be anything. Only disks has major:minor for example. Battery will have lots of numbers such as `POWER_SUPPLY_ENERGY_FULL_DESIGN`. And many of those files in sysfs are depends on modules. Thus I do not see any easy way to properly cover all cases. Then I think make them all as string value is the best option so far.
- Things about `\x20` in the udevadm output. I am not very sure if we should process this. I feel I always need to pre-process it and get rid of the `\x20` stuff. `"disk/by-partlabel/EFI\\x20System\\x20Partition"` or `"ID_MODEL_ENC": "SanDisk\\x20SDSSDHII960G\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20"` For the `\x20` in E dict we may leave it as it is as long and leave it to end user to convert. But The value in paths such has S list, we night consider to decode it to space?

**Comment by braindevices** [comment]
ah, never mind, some tools really need those `\x20` to work with those paths. So we should just leave it as it is and the end users should know when they need to decode when the do not.

**Comment by kellyjonbrazil** [comment]
If you think it's worth it, we could have `jc` try to convert numbers, but you can have the `--raw` (cli) or `raw=True` (module) option to suppress the conversion. If the output is too unpredictable then the attempted conversions can be more trouble than it's worth, though. Sometimes if it's unpredictable, but the end-user understands the expected output, I can add a `_int` suffix to a field to preserve the original and add an attempted conversion. Not sure if this makes sense in this case, but I'm open to it.

Also, with the `\x20` conversions - that can also be processed/suppressed with the `--raw` option and can also be done by adding another converted key/value (maybe something like `key_pretty` so we can preserve the original.

**Comment by kellyjonbrazil** [comment]
I'll leave the processing simple for now - only convert `L:` to integer. We can always add more processed fields if it they are requested.

**Comment by kellyjonbrazil** [comment]
Added to v1.22.1 available via pip. Binaries coming soon.
