### ISSUE TITLE
/proc/PID/stat can't be parsed when `comm` field contains spaces

### ISSUE THREAD

**Issue by hvenev** [kellyjonbrazil/jc#294]
```
$ cat a\ script.sh 
#!/bin/bash
cut -d' ' -f1-4 /proc/$$/stat
python3 -m jc /proc/$$/stat
```

```
$ ./a\ script.sh 
1377890 (a script.sh) S
jc:  Error - oc parser could not parse the input data.
             If this is the correct parser, try setting the locale to C (LC_ALL=C).
             For details use the -d or -dd option. Use "jc -h --oc" for help.
```

It appears that only the `comm` field can contain `)`, so a correct parser would read the entire file and consider everything between the first `(` and the last `)` (including spaces and newlines) to be the command.

**Comment by kellyjonbrazil** [comment]
Hi - thanks for reporting this issue! I'll take a look and should be able to get a fix out shortly.

**Comment by kellyjonbrazil** [comment]
Yep, didn't realize there could be spaces in that field so I was just doing a naive split. Can fix pretty simply with a regex instead. I should be able to get a fix out later today. Thanks again!

**Comment by hvenev** [comment]
Just don't forget that filenames can also contain newlines.

**Comment by kellyjonbrazil** [comment]
Interesting, it looks like the field will truncate to 15 characters:
```
$ cat this_is_a_really_long_filename
#!/bin/bash
cat /proc/$$/stat
$ ./this_is_a_really_long_filename
1984 (this_is_a_reall) S 1888 1984 1888 34816 1984 4202496 428 0 0 0 0 0 0 0 20 0 1 0 41832 115900416 297 18446744073709551615 4194304 5100612 140736094388496 140736094387144 139946537960476 0 65536 4 65538 18446744072034584486 0 0 17 0 0 0 0 0 0 7200240 7236240 12611584 140736094393950 140736094393993 140736094393993 140736094396375 0
```
Of course, the new-line character also counts as a character so you can get stuff like this:
```
$ cat "my file with
> spaces and newline"
#!/bin/bash
cat /proc/$$/stat
$ './my file with
spaces and newline' 
2001 (my file with
sp) S 1888 2001 1888 34816 2001 4202496 428 0 0 0 0 0 0 0 20 0 1 0 75513 115900416 297 18446744073709551615 4194304 5100612 140737020052256 140737020050904 140096699233308 0 65536 4 65538 18446744072034584486 0 0 17 0 0 0 0 0 0 7200240 7236240 35389440 140737020057179 140737020057223 140737020057223 140737020059606 0
```
Woohoo!

**Comment by hvenev** [comment]
Yes, according to `man 5 proc`:

>              (2) comm  %s
>                     The  filename  of  the  executable,  in  parentheses.   Strings  longer than
>                     TASK_COMM_LEN (16) characters (including  the  terminating  null  byte)  are
>                     silently  truncated.   This  is  visible  whether  or  not the executable is
>                     swapped out.

**Comment by kellyjonbrazil** [comment]
Ok, looks like I have this fixed in the `dev` branch. Basically just swapped to regex vs. simple split(). Had to update the signature match regex to allow for newlines as well. Tests are passing.

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/proc_pid_stat.py

You can test this new parser by copying it to your `jc` plugin directory (https://github.com/kellyjonbrazil/jc/tree/dev#custom-parsers)

Magic syntax won't work this way, but you can `cat /proc/pid/$$/stat | jc --proc-pid-stat` to test. This is because I also updated the signature in the top-level Proc parser.

For full testing of magic syntax and the normal `--proc` top-level parser you can clone the `dev` branch and test.

I'll wait for some more fixes before pushing a new release with the fix.

Thanks again for your help!

**Comment by hvenev** [comment]
Why do you use `re.search` instead of `re.match`? I don't expect that they would add anything else to the beginning of `/proc/PID/stat`. Using `re.match` means that in many cases you'd get `None` instead of a wrong result, which is definitely better.

**Comment by kellyjonbrazil** [comment]
No real reason. I thought since I used `^` in the pattern it would behave the same as `re.match`.  But `re.match` does seem to be more correct. I'm open to changing. Is my thinking off?

**Comment by hvenev** [comment]
No, I'm wrong. Sorry about that. I didn't notice the `^`, and by default it matches the start of the string rather than the start of a line. So,

LGTM

**Comment by kellyjonbrazil** [comment]
Added to v1.22.1 available via pip. Binaries coming soon.
