### ISSUE TITLE
Can we add support to `lspci -nnmmv`?

### ISSUE THREAD

**Issue by braindevices** [kellyjonbrazil/jc#297]
the lspci has some kind of machine readable output but not very easy to parse when try to use verbose output. There were attempts to add -J option to output json format, but those patches had never got merged.

Thanks!

**Comment by kellyjonbrazil** [comment]
Hi there!

Yeah, this one looks pretty easy to parse:
```
$ lspci -mm
00:00.0 "Host bridge" "Intel Corporation" "440BX/ZX/DX - 82443BX/ZX/DX Host bridge" -r01 "VMware" "Virtual Machine Chipset"
00:01.0 "PCI bridge" "Intel Corporation" "440BX/ZX/DX - 82443BX/ZX/DX AGP bridge" -r01 "" ""
00:07.0 "ISA bridge" "Intel Corporation" "82371AB/EB/MB PIIX4 ISA" -r08 "VMware" "Virtual Machine Chipset"
00:07.1 "IDE interface" "Intel Corporation" "82371AB/EB/MB PIIX4 IDE" -r01 -p8a "VMware" "Virtual Machine Chipset"
00:07.3 "Bridge" "Intel Corporation" "82371AB/EB/MB PIIX4 ACPI" -r08 "VMware" "Virtual Machine Chipset"
00:07.7 "System peripheral" "VMware" "Virtual Machine Communication Interface" -r10 "VMware" "Virtual Machine Communication Interface"
00:0f.0 "VGA compatible controller" "VMware" "SVGA II Adapter" "VMware" "SVGA II Adapter"
00:10.0 "SCSI storage controller" "Broadcom / LSI" "53c1030 PCI-X Fusion-MPT Dual Ultra320 SCSI" -r01 "VMware" "LSI Logic Parallel SCSI Controller"
00:11.0 "PCI bridge" "VMware" "PCI bridge" -r02 -p01 "" ""
00:15.0 "PCI bridge" "VMware" "PCI Express Root Port" -r01 "" ""
00:15.1 "PCI bridge" "VMware" "PCI Express Root Port" -r01 "" ""

$ lspci -mmv
Slot:	00:00.0
Class:	Host bridge
Vendor:	Intel Corporation
Device:	440BX/ZX/DX - 82443BX/ZX/DX Host bridge
SVendor:	VMware
SDevice:	Virtual Machine Chipset
Rev:	01

Slot:	00:01.0
Class:	PCI bridge
Vendor:	Intel Corporation
Device:	440BX/ZX/DX - 82443BX/ZX/DX AGP bridge
Rev:	01

Slot:	00:07.0
Class:	ISA bridge
Vendor:	Intel Corporation
Device:	82371AB/EB/MB PIIX4 ISA
SVendor:	VMware
SDevice:	Virtual Machine Chipset
Rev:	08

Slot:	00:07.1
Class:	IDE interface
Vendor:	Intel Corporation
Device:	82371AB/EB/MB PIIX4 IDE
SVendor:	VMware
SDevice:	Virtual Machine Chipset
Rev:	01
ProgIf:	8a

Slot:	00:07.3
Class:	Bridge
Vendor:	Intel Corporation
Device:	82371AB/EB/MB PIIX4 ACPI
SVendor:	VMware
SDevice:	Virtual Machine Chipset
Rev:	08
```
I'll look at this for the next release.

**Comment by braindevices** [comment]
@kellyjonbrazil thanks. And we actually prefer `-nnmmv`, which also give out all those id numbers.

**Comment by braindevices** [comment]
item looks like following:
```
Slot:   00:1d.6
Class:  PCI bridge [0604]
Vendor: Intel Corporation [8086]
Device: Cannon Lake PCH PCI Express Root Port #15 [a336]
Rev:    f0
```
please notice the `\[[0-9a-f]{4}\]` part

**Comment by braindevices** [comment]
@kellyjonbrazil I am on commit 486705297256a74500c95117131048ffdd0fdd6f (HEAD -> dev, origin/dev)

I feel like we should convert the numbers to int instead of string. I mean the actual numbers in `[nnnn]`, Rev, ProgIf and IOMMUGroup (we can see this in [lspci >=3.7.0](https://github.com/pciutils/pciutils/blob/d224993d423bcd0e88d8eacc0464bc3a66972e95/ChangeLog#L50)). I am not sure if NUMANode is always number yet.

**Comment by braindevices** [comment]
never mind, I think we'd better keep all the field as string for simplicity.

However, the domain number can never be null:
> -D     Always show PCI domain numbers. By default, lspci suppresses them on machines which have only domain 0
So basically if it is missing from slot, domain is 0.

I do not know if we should convert all the domain, bus, device, func to number yet. because some program use `%04x` for domain, some program use `0x%2x` for all fields, some just use decimal.

**Comment by kellyjonbrazil** [comment]
> However, the domain number can never be null:

Good catch - yes it makes sense to hard code that to zero, then.

> I think we should convert all the domain, bus, device, func to number.

I commented on this in the PR. I think it might make sense to add fields for this so you can choose which to use depending on the context (e.g. `.bus_int`). These conversions can be done in the `process` function so you can suppress them with the `--raw` (cli) or `raw=True` (module) options.

**Comment by kellyjonbrazil** [comment]
How does this look? You can use `-r` to suppress the additional `_int` fields:
```
[
  {
    "slot": "02:05.0",
    "domain": "00",
    "domain_int": 0,
    "bus": "02",
    "bus_int": 2,
    "dev": "05",
    "dev_int": 5,
    "function": "0",
    "function_int": 0,
    "class": "SATA controller",
    "class_id": "0106",
    "class_id_int": 262,
    "vendor": "VMware",
    "vendor_id": "15ad",
    "vendor_id_int": 5549,
    "device": "SATA AHCI controller",
    "device_id": "07e0",
    "device_id_int": 2016,
    "svendor": "VMware",
    "svendor_id": "15ad",
    "svendor_id_int": 5549,
    "sdevice": "SATA AHCI controller",
    "sdevice_id": "07e0",
    "sdevice_id_int": 2016,
    "physlot": "37",
    "physlot_int": 55,
    "progif": "01",
    "progif_int": 1
  },
  {
    "slot": "ff:02:05.0",
    "domain": "ff",
    "domain_int": 255,
    "bus": "02",
    "bus_int": 2,
    "dev": "05",
    "dev_int": 5,
    "function": "0",
    "function_int": 0,
    "class": "SATA controller",
    "class_id": "0106",
    "class_id_int": 262,
    "vendor": "VMware",
    "vendor_id": "15ad",
    "vendor_id_int": 5549,
    "device": "SATA AHCI controller",
    "device_id": "07e0",
    "device_id_int": 2016,
    "svendor": "VMware",
    "svendor_id": "15ad",
    "svendor_id_int": 5549,
    "sdevice": "SATA AHCI controller",
    "sdevice_id": "07e0",
    "sdevice_id_int": 2016,
    "physlot": "37",
    "physlot_int": 55,
    "progif": "01",
    "progif_int": 1
  }
]
```
I have `physlot` and `progif` converting as if they are hex. not sure if they are already integers.

**Comment by kellyjonbrazil** [comment]
Added to v1.22.1 available via pip. Binaries coming soon.
