### ISSUE TITLE
pci.ids (database for lspci) parser

### ISSUE THREAD

**Issue by braindevices** [kellyjonbrazil/jc#298]
pci.ids are also very useful especially the class database at the end `# List of known device classes, subclasses and programming interfaces`. If we can parse it and generate a class number: class name dictionary, it will be very helpful when we try to automate tools that only use device id and class/type numbers internally such has qemu, virsh, etc.

There are lots of attempts already to load `# Vendors, devices and subsystems.` section but most of them are long dead. Moreover, no project actually load the class section.

The newest version of the file can be download [here](https://raw.githubusercontent.com/pciutils/pciids/master/pci.ids)

**Comment by kellyjonbrazil** [comment]
Yeah, I think that makes sense. I would just ignore the comments in the file, unless you think they should be there in a `comment` field or something.

**Comment by braindevices** [comment]
so far I do not think the comment is important. I think they usually just show syntax

**Comment by kellyjonbrazil** [comment]
I have an initial version of the `pci.ids` file parser ready to test.

I went a little bit of a different route than normal and used nested dictionaries to represent the data. Since all of the vendor and class ID's are unique, it seems like this might make sense, but I'm not sure.

This structure seems to make sense to me because it allows queries like this:
```
$ cat pci.ids | jc --pci-ids | jq '.vendors["001c"]["0001"]["001c"]["0005"].subsystem_name'
                                               |     |      |       |
                                               |     |      |        subdevice
                                               |     |       subvendor
                                               |     device
                                                vendor
"2 Channel CAN Bus SJC1000 (Optically Isolated)"
```
Or for Classes:
```
$ cat pci.ids | jc --pci-ids | jq '.classes["0c"]["03"]["40"]'
                                             |    |     |
                                             |    |      prog_if
                                             |    subclass
                                              class
"USB4 Host Interface"
```
Here's the current Schema:
```
{
    "vendors": {
        "<vendor_id>": {
            "vendor_name":                   string,
            "<device_id>": {
                "device_name":               string,
                "<subvendor_id>": {
                    "<subdevice_id":         string
                }
            }
        }
    },
    "classes": {
        "<class_id>": {
            "class_name":                    string,
            "<subclass_id>": {
                "subclass_name":             string,
                "<prog_if>":                 string
            }
        }
    }
}
```
You can test the parser by copying [the file](https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/pci_ids.py) to your `jc` plugin directory:

- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

Let me know what you think!

**Comment by kellyjonbrazil** [comment]
I could also prefix the ID values with an _ or x or something so we don’t need to use bracket notation in jq.

**Comment by braindevices** [comment]
At the first glance it looks ok to me.
- I understand that jq cannot interpret the string start with number. So you want to add `_` or `x` in the front. I think it is good.
-  path query works fine:
   ```
   $ jc --pci-ids -p < /tmp/pci.ids | jq '.classes | path(recurse | select(.=="Endpoint mode" )) | join("")'
   "_06_08_01"
   # use vendor and device name to query the id
   $ jc --pci-ids -p < /tmp/pci.ids | jq '.vendors | select(.vendor_name="PEAK-System Technik GmbH") | path(recurse | select(.=="2 Channel CAN Bus SJC1000 (Optically Isolated)" ))[:-1] | join("")'
   "_001c_0001_001c_0005"
   ```
- some program such as virsh show class as `0x0c8000`. However, 0c80 does not have prog-if. Thus I have to do something like `jc --pci-ids -p < /tmp/pci.ids | jq '.classes._0c._08| (._00 // .subclass_name )'` to unify the class query.

A problem of nested dict is I cannot get both vendor and device_name easily by searching subsystem_name. But I doubt anyone will do this kind of query in practice.

So far I think this parser is nicely done. Thanks!

**Comment by kellyjonbrazil** [comment]
Added to v1.22.1 available via pip. Binaries coming soon.
