### ISSUE TITLE
New Parser: ntpq -p command

### ISSUE THREAD

**Issue by jakane** [kellyjonbrazil/jc#31]
It would be really useful to parse the output of `ntpq -p`

**Comment by kellyjonbrazil** [comment]
Great idea! I think `timedatectl status` might be good, too. I'll start researching these for the next release.

**Comment by kellyjonbrazil** [comment]
For reference:
https://community.hpe.com/t5/System-Administration/Interpreting-NTPQ-output/td-p/3616538

**Comment by kellyjonbrazil** [comment]
Sample output:
```
$ ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 ntpool1.603.new 204.9.54.119     2 u    1   64    1   73.191  5602175   0.267
 12.167.151.1    66.85.78.80      3 u    1   64    1   97.264  5602174   2.017
 www-ntp-org.nss 163.237.218.19   2 u    1   64    1   91.775  5602175   0.047
 cartwheel.spide 164.67.62.194    2 u    2   64    1   29.837  5602174   0.000
```

**Comment by kellyjonbrazil** [comment]
`ntpq -p` and `ntpq -pn` parser is added in dev branch. Tests are passing.

**Comment by kellyjonbrazil** [comment]
You should be able to get the new ntpq parser by running `pip3 install --upgrade jc`.

Happy parsing!
kb

**Comment by jakane** [comment]
Thanks Kelly .. I have updated and tested both `ntpq -p` and `timedatectl`

Awesome!
