### ISSUE TITLE
jc as REST API?

### ISSUE THREAD

**Issue by jmfayard** [kellyjonbrazil/jc#311]
Hello, I just stumbled upon jc and your blog posts and I find it fascinating.

I have the project to make a library for the JVM and [Kotlin](https://kotlinlang.org/) in particular typesafe
and I had thought about how to make writing commands typesafe - like not getting the `--option-name` wrong,
but combined with `jc` I would also have a typesafe output.

Now since I'm not doing python, I wonder how that would work.
A solution would be simply to execute `jc` and force the user to have it installed and up-to-date.
Another one could be do to a REST call to always benefit from the latest and the greatest version without any setup.

What do you think?

**Comment by kellyjonbrazil** [comment]
Hi there! Thanks for your interest in `jc`.

This sounds interesting and the REST approach you mentioned is probably the easiest and most generic approach so `jc` can be integrated with multiple languages, albeit at a performance cost.

I have a project called [jc-web](https://github.com/kellyjonbrazil/jc-web) which implements `jc` as a web interface:
https://jc-web.onrender.com/

I could do a simpler form of that as a rest-api package.

Some other options of integrating python functions (packages?) into Java/Kotlin can be found here, but this is outside of my expertise:

https://stackoverflow.com/questions/8898765/calling-python-in-java
https://medium.com/@shmulikamar/https-medium-com-shmulikamar-connecting-python-and-java-with-rust-11c256a1dfb0
https://chaquo.com/chaquopy/

In any case, I can play around with a REST-API version in the next few weeks.

**Comment by jmfayard** [comment]
ah yes that would be awesome, thanks

**Comment by kellyjonbrazil** [comment]
Another thought is it might be simpler and more efficient to use the `jc` binary and call it as a subprocess in Java while using STDIN/STDOUT:

https://stackoverflow.com/questions/10407308/redirect-stdin-and-stdout-in-java

The `jc` binaries can be found under the [GitHub Releases](https://github.com/kellyjonbrazil/jc/releases)

I still think it would be interesting to create a REST API, but this might be a faster path for you.

**Comment by jmfayard** [comment]
I would like to try both ideally, but yes I can do that, no time pressure for you to deliver anything

**Comment by kellyjonbrazil** [comment]
I have an initial working version of a `jc` REST API here: https://github.com/kellyjonbrazil/jc-restapi

I can host this on render.com for testing purposes. Might also make sense to turn this into a docker container.

**Comment by kellyjonbrazil** [comment]
I have a demo of this working at https://jc-api.onrender.com. See the https://github.com/kellyjonbrazil/jc-restapi for info on usage.
