### ISSUE TITLE
New parser: iwconfig

### ISSUE THREAD

**Issue by vrince** [kellyjonbrazil/jc#329]
Hi guys,

What about we add support for `iwconfig <interface>` to extract the current wifi setup? The output looks like this: 

```sh
wlp0s20f3  IEEE 802.11  ESSID:"BLABLABLA"  
          Mode:Managed  Frequency:5.24 GHz  Access Point: 74:13:C2:8B:C6:45   
          Bit Rate=270 Mb/s   Tx-Power=22 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          Link Quality=46/70  Signal level=-64 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:329   Missed beacon:0
```

**Comment by kellyjonbrazil** [comment]
Hi @vrince - looks like a good candidate. The output looks similar to `ifconfig` so we can use the same techniques.

**Comment by Daibao9999** [comment]
Okk

**Comment by kellyjonbrazil** [comment]
Could you get me a few good output samples? I only have linux VMs so I can’t generate the output on my side. I’d like the command run with no arguments and then with one or more interfaces selected. 

Thanks!

**Comment by vrince** [comment]
I'll give it a try, looks accessible actually
.

**Comment by kellyjonbrazil** [comment]
Added in v1.22.4.
