### ISSUE TITLE
Parser: plist parser should also read "old" nextstep plist format

### ISSUE THREAD

**Issue by muescha** [kellyjonbrazil/jc#330]
i have this example nextstep plist - but i can not read it with `jc --plist`

```plist
{
    key1 = Value1;
    key2 = "value3";
    DateOfStateChange = "2022-12-18 05:51:30 +0000";
    Destination = "F134545";
    Progress =     {
        Percent = "0.4563777755358589";
    };
}
```

but this can be converted with:

```shell
cat test.plist | plutil -convert json  -r -o - -- - | jq
```

i think plutil is only on macOS available - maybe there is some other library available for the nextstep plist

**Comment by kellyjonbrazil** [comment]
Ah yes, that would be cool for the plist parser to support Nextstep format. Looks like there are a couple python libraries I could use to do this.

**Comment by muescha** [comment]
maybe it is possible to use `plutil` on macOS and if this util is not available then to fallback to a python library on other systems?

**Comment by kellyjonbrazil** [comment]
I was thinking about that. Not sure it will be necessary, but if it is I might either:

1. Use `plutil` as a backup if the python library fails
2. Make the `--raw` parser option use `plutil`

Or something like that. I don't think I'll need to use plutil, though. I found a pretty good parser [library](https://github.com/samdmarshall/pbPlist) but it will just take a little work to vendor it into `jc`.

**Comment by kellyjonbrazil** [comment]
I was able to get NeXTSTEP Plist file support into the `--plist` parser in the `dev` branch. I'm using the [pbPlist](https://github.com/samdmarshall/pbPlist/releases/tag/v1.0.4) library for parsing.

Because I'm using a 3rd party library it's not as easy as copying the new parser file to the plugin directory to test. Tests are passing and it looks like it should be good to go for the next release:
```
% echo '{
    key1 = Value1;
    key2 = "value3";
    DateOfStateChange = "2022-12-18 05:51:30 +0000";
    Destination = "F134545";
    Progress =     {
        Percent = "0.4563777755358589";
    };
}' | jc --plist -p
{
  "key1": "Value1",
  "key2": "value3",
  "DateOfStateChange": "2022-12-18 05:51:30 +0000",
  "Destination": "F134545",
  "Progress": {
    "Percent": "0.4563777755358589"
  }
}
```

**Comment by kellyjonbrazil** [comment]
Added in v1.22.4.
