### ISSUE TITLE
group generic parsers in the jc -a list

### ISSUE THREAD

**Issue by muescha** [kellyjonbrazil/jc#333]
it would be nice if the generic parsers are grouped seperate in the parsers list

so if there is an unknown format i can discover this ones at first

**Comment by kellyjonbrazil** [comment]
Yes, the list of parsers is getting to be quite large. I think that makes sense. I may add a `generic` attribute to the parser info or something to implement this.

**Comment by kellyjonbrazil** [comment]
Might also make sense to add a `category` or `tag` attribute to the parsers so they can be grouped/filtered in different ways.

**Comment by muescha** [comment]
thats a good idea

**Comment by kellyjonbrazil** [comment]
I have added this functionality to the `dev` branch. I added a `tags` field to the parser info metadata so you can sort on that with `jq`, etc.:
```
$ jc -a | jq -r '.parsers[] | select(.tags[] | contains("generic")) | .description'
```
You can also see a list of parsers by category with a new help option:
```
% jc -hhh
Generic Parsers:  (3)
--asciitable        ASCII and Unicode table parser
--asciitable-m      multi-line ASCII and Unicode table parser
--kv                Key/Value file and string parser

Standard Spec Parsers:  (22)
--cef               CEF string parser
--cef-s             CEF string streaming parser
--clf               Common and Combined Log Format file parser
...
```
This is ready for the next release.

**Comment by kellyjonbrazil** [comment]
Added in v1.22.4.
