### ISSUE TITLE
Possible new parser: apt-get --dry-run -qq upgrade

### ISSUE THREAD

**Issue by chriscroome** [kellyjonbrazil/jc#340]
[apt-get](https://manpages.debian.org/bullseye/apt/apt-get.8.en.html) has a `--dry-run` mode which works with `upgrade` and `dist-upgrade`:

> ### -s, --simulate, --just-print, --dry-run, --recon, --no-act
> No action; perform a simulation of events that would occur based on the current system state but do not actually change the system. Locking will be disabled (`Debug::NoLocking`) so the system state could change while apt-get is running. Simulations can also be executed by non-root users which might not have read access to all apt configuration distorting the simulation. A notice expressing this warning is also shown by default for non-root users (`APT::Get::Show-User-Simulation-Note`). Configuration Item: `APT::Get::Simulate`.
>
> > Simulated runs print out a series of lines, each representing a dpkg operation: configure (`Conf`), remove (`Remv`) or unpack (`Inst`). Square brackets indicate broken packages, and empty square brackets indicate breaks that are of no consequence (rare).

However the output is only designed to be  machine parsable when used in combination with `-qq`:

> ### -q, --quiet
> Quiet; produces output suitable for logging, omitting progress indicators. More q's will produce more quiet up to a maximum of 2. You can also use `-q=#` to set the quiet level, overriding the configuration file. Note that quiet level 2 implies `-y`; you should never use `-qq` without a no-action modifier such as `-d`, `--print-uris` or `-s` as APT may decide to do something you did not expect. Configuration Item: `quiet`.

When there are no outstanding updates there is no output, when there are outstanding updates the output is like this:

```bash
sudo apt-get -sqq dist-upgrade
```

```
Inst base-files [10.3+deb10u4] (10.3+deb10u13 Debian:10.13/oldstable [amd64])
Conf base-files (10.3+deb10u13 Debian:10.13/oldstable [amd64])
Inst dpkg [1.19.7] (1.19.8 Debian:10.13/oldstable, Debian-Security:10/oldstable [amd64])
Conf dpkg (1.19.8 Debian:10.13/oldstable, Debian-Security:10/oldstable [amd64])
```

When it is run without `sudo` or not as `root` there is also a warning:

```bash
apt-get -sqq dist-upgrade
```

```
NOTE: This is only a simulation!
      apt-get needs root privileges for real execution.
      Keep also in mind that locking is deactivated,
      so don't depend on the relevance to the real current situation!
Inst base-files [10.3+deb10u4] (10.3+deb10u13 Debian:10.13/oldstable [amd64])
Conf base-files (10.3+deb10u13 Debian:10.13/oldstable [amd64])
Inst dpkg [1.19.7] (1.19.8 Debian:10.13/oldstable, Debian-Security:10/oldstable [amd64])
Conf dpkg (1.19.8 Debian:10.13/oldstable, Debian-Security:10/oldstable [amd64])
```

I'm currently using the [output of `apt-get -fqqs dist-upgrade`](https://git.coop/webarch/upgrade/-/blob/5b7d67899794cc555f0a2607bbcc64230b8d5558/tasks/main.yml#L11) to [generate a list of outstanding updates](https://git.coop/webarch/upgrade/-/blob/5b7d67899794cc555f0a2607bbcc64230b8d5558/tasks/upgrade.yml#L1) so only the first two columns matter in this case.

The optional 3rd column, which is enclosed by square brackets, appears to lists the currently installed version of a package (the manpage says this is a broken package) and the 3rd or 4th regular bracket enclosed column lists the proposed package version, the existing source, the proposed source and the architecture in square brackets.

I don't currently have a good suggestion for a JSON representation of this data but I'll have a think about it&hellip;

**Comment by kellyjonbrazil** [comment]
Thanks for the parser suggestion! I'll start to tackle these after the holidays.

**Comment by tallyoh** [comment]
Support for yum/dnf update list would be great too. Thanks

**Comment by kellyjonbrazil** [comment]
What would this parser be called? `apt-get` or `apt-get-dryrun`? Something else?

**Comment by kellyjonbrazil** [comment]
How about this schema?
```
    [
      {
        "operation":            string,  # configure, remove, or unpack
        "package":              string,
        "broken":               string or null,
        "proposed_pkg_ver":     string,
        "existing_src":         string,
        "architecture":         string
      }
    ]
```

**Comment by kellyjonbrazil** [comment]
Here is what I have so far:
```
% echo 'Inst base-files [10.3+deb10u4] (10.3+deb10u13 Debian:10.13/oldstable [amd64])
Conf base-files (10.3+deb10u13 Debian:10.13/oldstable [amd64])
Inst dpkg [1.19.7] (1.19.8 Debian:10.13/oldstable, Debian-Security:10/oldstable [amd64])
Conf dpkg (1.19.8 Debian:10.13/oldstable, Debian-Security:10/oldstable [amd64])' | jc --apt-get-sqq -p
[
  {
    "operation": "Inst",
    "package": "base-files",
    "broken": "10.3+deb10u4",
    "proposed_pkg_ver": "10.3+deb10u13 Debian:10.13/oldstable",
    "existing_src": null,
    "architecture": "amd64"
  },
  {
    "operation": "Conf",
    "package": "base-files",
    "broken": null,
    "proposed_pkg_ver": "10.3+deb10u13 Debian:10.13/oldstable",
    "existing_src": null,
    "architecture": "amd64"
  },
  {
    "operation": "Inst",
    "package": "dpkg",
    "broken": "1.19.7",
    "proposed_pkg_ver": "1.19.8 Debian:10.13/oldstable",
    "existing_src": "Debian-Security:10/oldstable",
    "architecture": "amd64"
  },
  {
    "operation": "Conf",
    "package": "dpkg",
    "broken": null,
    "proposed_pkg_ver": "1.19.8 Debian:10.13/oldstable",
    "existing_src": "Debian-Security:10/oldstable",
    "architecture": "amd64"
  }
]
```

**Comment by chriscroome** [comment]
I wonder if `existing_pkg_ver` might make sense?

Probably best if someone with a good knowledge of Debian packaging cast an eye over the proposal, but I'm not sure how best to solicit this.

**Comment by kellyjonbrazil** [comment]
Added in [v1.25.2](https://github.com/kellyjonbrazil/jc/releases/tag/v1.25.2)

**Comment by chriscroome** [comment]
BTW the [documentation](https://kellyjonbrazil.github.io/jc/docs/parsers/apt_get_sqq) would be better with something like this as an usage example:

```bash
$ apt-get -sqq upgrade | jc --apt-get-sqq
```

or

```bash
$ jc apt-get -sqq full-upgrade
```
