### ISSUE TITLE
x509 parser fails for Distinguished Name Serial Numbers

### ISSUE THREAD

**Issue by sumezulike** [kellyjonbrazil/jc#342]
https://github.com/kellyjonbrazil/jc/blob/c524d3713649fd04b943f70e088386f4a055a531/jc/parsers/x509_cert.py#L467-L468
The recursive conversion here finds the `serial_number` fields of `subject` or `issuer`, which are not required to be integers, as specified in [X.520](https://www.itu.int/rec/T-REC-X.520-201910-I/en).
This causes a crash with `AttributeError: 'str' object has no attribute 'to_bytes'`.

I have included an example certificate with which you can confirm the bug.

[cert.zip](https://github.com/kellyjonbrazil/jc/files/10316023/cert.zip)

**Comment by kellyjonbrazil** [comment]
Thanks for reporting this! Shouldn't be too hard to fix and get into the next release.

**Comment by kellyjonbrazil** [comment]
What do you think we should do for serial number strings? Convert them to hex representation as well or just leave them as strings? I could also add an additional field that preserves the string version of the value along with the current hex value.

**Comment by sumezulike** [comment]
I don't know about others, but for my usecase, the original strings would be absolutely sufficient.
Thanks for the quick response!

**Comment by kellyjonbrazil** [comment]
Hi there - I have a fix in the `dev` branch that seems to be working. I basically added a `serial_number_str` field that just does a simple convert to string, while the original `serial_number` field preserves the hex representation of the integer or string.

You can test by copying the parser file below to your plugin directory:
https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/x509_cert.py

- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

Let me know if you run into any further issues!

Thanks

**Comment by sumezulike** [comment]
Oh, that was quick! That definitely works for me. Thanks a lot!

**Comment by kellyjonbrazil** [comment]
Fixed in v1.22.4.
