### ISSUE TITLE
jc fails on lsusb -v output

### ISSUE THREAD

**Issue by hotab** [kellyjonbrazil/jc#346]
Output sample attached
[lsusb.txt](https://github.com/kellyjonbrazil/jc/files/10345246/lsusb.txt)

```
self = <jc.parsers.lsusb._LsUsb object at 0x000001D483FD5180>
line = '     Ext Status: 0000.0044'

    def _add_hub_port_status_attributes(self, line):
        # Port 1: 0000.0103 power enable connect
        first_split = line.split(': ', maxsplit=1)
        port_field = first_split[0].strip()
        second_split = first_split[1].split(maxsplit=1)
        port_val = second_split[0]
>       attributes = second_split[1].split()
E       IndexError: list index out of range
```

**Comment by kellyjonbrazil** [comment]
Hi - thanks for reporting this. The `lsusb` parser is probably the most complex of them all. I really wish they would add JSON output to that command! :)

It looks like there was some extra information in the Hub Port Status for Port 1:
```
Hub Port Status:
   Port 1: 0000.0263 5Gbps power suspend enable connect
     Ext Status: 0000.0044
       RX Speed Attribute ID: 4 Lanes: 1
       TX Speed Attribute ID: 4 Lanes: 1
```
I made an update to the parser to ignore the extra lines under the initial one and it looks like that works, except I see a bunch of these sections that also seem to be causing problems (though they do parse to JSON):
```
VideoStreaming Interface Descriptor:
        bLength                            15
        bDescriptorType                    36
        bDescriptorSubtype                  1 (INPUT_HEADER)
        bNumFormats                         2
        wTotalLength                   0x0281
        bEndpointAddress                 0x81  EP 1 IN
        bmInfo                              0
        bTerminalLink                       3
        bStillCaptureMethod                 1
        bTriggerSupport                     1
        bTriggerUsage                       0
        bControlSize                        1
        bmaControls( 0)                     0
        bmaControls( 1)                     0
```
I'll probably need to add a new section to parse those values correctly in the schema.

**Comment by kellyjonbrazil** [comment]
I have a fix for this and also to add the `videocontrol` and `videostreaming` interface descriptors in `dev`:
https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/lsusb.py

I'm still working on refactoring a lot of the code in the parser, but you can test it out by copying the file to your parser plugin directory:

- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

Let me know if that works for you or if you run into any other issues. Thanks!

**Comment by hotab** [comment]
Hey! So I ran it on the data and it did not fail, but I will come back probably tomorrow when I get to test it a bit more as well. Thanks!

**Comment by hotab** [comment]
I got to test this a little bit. It seemed to work fine in my case, but my set of devices is not that big - 3 machines.

**Comment by kellyjonbrazil** [comment]
Added in v1.22.5.
