### ISSUE TITLE
Unable to parse `zipinfo` output containing whitespace in the archive path

### ISSUE THREAD

**Issue by daniel-rhoades** [kellyjonbrazil/jc#347]
After running  `zipinfo` using a path to an archive containing a space character, `jc` is unable to consume the output.   Example reproduction:

```
$ zipinfo 'some_dir/another dir/archive.zip' > out

Archive:  some_dir/another dir/archive.zip
Zip file size: xxx bytes, number of entries: xxx
...
```

This works when there is no space in the path (e.g. `zipinfo archive.zip`).   However when it contains a space character an error occurs:

```
$ jc -d --zipinfo < out
Traceback (most recent call last):
  ...
    self.data_out = self.parser_module.parse(
  File "... jc/parsers/zipinfo.py", line 173, in parse
    _, archive = line.split()
ValueError: too many values to unpack (expected 2)
```

One solution is to replace:

https://github.com/kellyjonbrazil/jc/blob/36ce3c791dd2d3f0b5244961e889da5fe4bb0e6f/jc/parsers/zipinfo.py#L173

With:

```python
# Remove the field name prefix (the double-space is intentional)
archive = line.removeprefix('Archive:  ')
```

This will support both situations, tested on MacOS with `zipinfo`  v3.0.

Alternatively, a more specific separator could be used (e.g.  a double-space).  However, it would be safer to just remove the field name prefix from the line instead, as paths could also contain that same separator.

**Comment by kellyjonbrazil** [comment]
Thanks for reporting this and the potential solution! I'll take a look.

**Comment by kellyjonbrazil** [comment]
I have this fixed in `dev` and it will go into the next release. Thanks!

**Comment by daniel-rhoades** [comment]
GJ.  Thanks for the quick turnaround, I'll test it in the next release.

**Comment by kellyjonbrazil** [comment]
Added in v1.22.5.
