### ISSUE TITLE
Fix AIX ARP support

### ISSUE THREAD

**Issue by davemq** [kellyjonbrazil/jc#351]
arp.py says AIX is supported, but it didn't work for me on AIX 7.1 or 7.2.

**Comment by kellyjonbrazil** [comment]
Thanks for reporting and fixing! Yeah, I probably made some mistakes with the AIX support tags. I assumed some of these ancient commands were the same between Unixes, but it looks like that's not correct. I've never actually logged into an AIX machine before. :)

**Comment by kellyjonbrazil** [comment]
Added in v1.22.5.
