### ISSUE TITLE
Fails on acpi

### ISSUE THREAD

**Issue by jooooscha** [kellyjonbrazil/jc#356]
When `apci` gives output of this form:

```Battery 0: Discharging, 87%, discharging at zero rate - will never fully discharge.```

 which can happen shortly after plugging the laptop/pc,  `jc` throws the following error

```
jc:  Error - acpi parser could not parse the input data.
             If this is the correct parser, try setting the locale to C
                 (LC_ALL=C).
             For details use the -d or -dd option. Use "jc -h --acpi" for help.
```

**Comment by kellyjonbrazil** [comment]
Hi there - thank you for reporting this. I have a fix for this in the `dev` branch. You can test by copying the parser file to your plugin directory:
https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/acpi.py

- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

Alternatively, you can use the `-r` or `--raw` option with the current code to workaround this issue.

Let me know if you run into any other issues!

**Comment by kellyjonbrazil** [comment]
Added in v1.23.0
