### ISSUE TITLE
Xrandr parser freezes when a display has --reflect set to any value other than normal

### ISSUE THREAD

**Issue by tzeikob** [kellyjonbrazil/jc#358]
Trying to parse the xrandr data in my two monitor setup having the one of them in `reflect y` mode causes the jc to freeze.

To reproduce the issue try the following list of cmds:
```
xrandr --output <name> --reflect y
jc xrandr
```

Xrandr output:
```
Screen 0: minimum 320 x 200, current 2806 x 900, maximum 8192 x 8192
LVDS-1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1366x768      60.00*+
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   640x400       59.88    59.98  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
VGA-1 connected 1440x900+1366+0 normal Y axis (normal left inverted right x axis y axis) 408mm x 255mm
   1440x900      59.89*+  74.98  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      74.93    59.81  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
```

Version:
jc version:  1.22.5
python interpreter version:  3.10.8
python path:  /usr/bin/python

I'm able to get the xrandr json document only if all of my monitors have the reflect mode set to normal. Reading the doc top bottom, I realized that no reflect field is included, which makes me think that maybe the reflect feature is not taken into account.

My system:
OS: Arch Linux x86_64
Kernel: 6.0.7-arch1-1
Shell: bash 5.1.16
WM: bspwm
Vendor String: The X.Org Foundation
Vendor Release Number: 12101004
X.Org Version: 21.1.4

**Comment by kellyjonbrazil** [comment]
Thanks for reporting this, @tzeikob. Could you paste the `xrandr` output and we'll reproduce on our side?

@lyterk could you take a look?

**Comment by tzeikob** [comment]
@kellyjonbrazil I've added it in the original post.

Perhaps I can help, as I'm currently working in a personal project where I needed the xrandr output in JSON, so I already have awk code with well tested regexp parsing the output head line into JSON object including the reflect part. Reflect mode appears to be shown in the following forms next to the rotate part:

```
[name] [(dis)?connected] [primary]? [resolution+offsets]? [normal | left | right | inverted] [X axis | Y axis | XY axis] ...
```
The absence of X|Y|XY axis means normal reflect.

Code:
```
local re='^(.*)\s(connected|disconnected)\s?(primary)?\s?'
  re+='([0-9]+x[0-9]+)?(\+[0-9]+\+[0-9]+)?\s?'
  re+='(normal|right|left|inverted)?\s?(X\saxis|Y\saxis|X\sand\sY\saxis)?\s.*'

  local result
  result="$(echo "${head}" | awk 'match($0,/'"${re}"'/,a) {
    if (a[3] == "primary") {a[3] = "true"} else {a[3] = "false"};
    a[5] = gensub(/\+(.*)\+(.*)/, "\\1x\\2", "g", a[5]);
    a[7] = tolower(a[7]); gsub(/( |and|axis)/, "", a[7]);
  
    active="false"
    if (a[2] == "connected" && a[4]) {
      active="true"
      if(!a[6]) a[6] = "normal";
      if(!a[7]) a[7] = "normal";
    }
    f="\"name\":\"%s\","
    f=f "\"status\":\"%s\","
    f=f "\"active\":\"%s\","
    f=f "\"primary\":\"%s\","
    f=f "\"area\":\"%s\","
    f=f "\"position\":\"%s\","
    f=f "\"rotate\":\"%s\","
    f=f "\"reflect\":\"%s\""
    printf f, a[1], a[2], active, a[3], a[4], a[5], a[6], a[7]
  }')"
```

**Comment by kellyjonbrazil** [comment]
Thank you! I'm not too familiar with the `xrandr` parser code but I'll take a look. Might be a quick fix.

**Comment by kellyjonbrazil** [comment]
Doing some quick debugging. I've found where the never-ending loops are. I'll have to examine in more detail to see a way to fix/break out of them, but getting closer.

**Comment by kellyjonbrazil** [comment]
Probably the easiest way to get the `jc` dev env going and submit a PR is to just copy the parser code to your parser plugin directory, which will override the built-in parser. Then you can edit that file and test and create a PR with just that file changed (under the `jc/parsers` folder).

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/xrandr.py

Here are the plugin directories for different OSs:
- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

The longer way would probably be to clone the repo and then run the `install.sh` script. There should only be a few required dependencies like `pygments`, `xmltodict`, and `ruamel.yaml`. (I think)

**Comment by kellyjonbrazil** [comment]
I updated the regex in `dev` and I think that fixed it. Let's see if this latest push fixes both issues:
https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/xrandr.py

Thanks!

**Comment by tzeikob** [comment]
It works!

Obrigado @kellyjonbrazil

**Comment by kellyjonbrazil** [comment]
Added a test for this fix. This will be in the next release.

**Comment by kellyjonbrazil** [comment]
Added in v1.23.0
