### ISSUE TITLE
Modify the xrandr parser to extract display model name from EDID

### ISSUE THREAD

**Issue by tzeikob** [kellyjonbrazil/jc#364]
The xrandr tool has an option named `--properties` which causes xrandr to print more information per output, part of this information is the `EDID` hexadecimal string.

> EDID (Extended Display Identification Data) is an industry standard for AV Source and Display devices which automatically communicates manufacturer specification and data between devices.

So decoding the EDID string we can get more data per display, one of which is the model name (e.g. Asus W193). The problem is that calling xrandr along with `--properties` breaks the current implentation of the parser, as this changes the default xrandr output to:

```sh
xrandr --properties
Screen 0: minimum 320 x 200, current 1366 x 768, maximum 8192 x 8192
LVDS-1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
        EDID: 
                00ffffffffffff004ca3523100000000
                0014010380221378eac8959e57549226
                0f505400000001010101010101010101
                010101010101381d56d4500016303020
                250058c2100000190000000f00000000
                000000000025d9066a00000000fe0053
                414d53554e470a204ca34154000000fe
                004c544e313536415432343430310018
        scaling mode: Full aspect 
                supported: Full, Center, Full aspect
        link-status: Good 
                supported: Good, Bad
        CONNECTOR_ID: 61 
                supported: 61
        non-desktop: 0 
                range: (0, 1)
   1366x768      60.00*+
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00 
   ...
VGA-1 disconnected (normal left inverted right x axis y axis)
        link-status: Good 
                supported: Good, Bad
        CONNECTOR_ID: 64 
                supported: 64
        non-desktop: 0 
                range: (0, 1)
...
``` 

My suggestion is to modify the parser so we can make it hybrid and when xrandr is called with the option `--properties` the parser should try to decode and extract the model name from the EDID string, otherwise should be **backward compatible** and work the same way as it does with outputs from regular xrandr calls (no `--properties`).

So the command `xrandr --properties | jc --xrandr` should give the following JSON document:

```json
{
  "screens": [
    {
      "screen_number": 0,
      "minimum_width": 320,
      "minimum_height": 200,
      "current_width": 1366,
      "current_height": 768,
      "maximum_width": 8192,
      "maximum_height": 8192,
      "associated_device": {
        "associated_modes": [],
        "is_connected": true,
        "is_primary": true,
        "device_name": "LVDS-1",
        "device_model": "Built-in",
        "rotation": "normal",
        "reflection": "normal",
        "resolution_width": 1366,
        "resolution_height": 768,
        "offset_width": 0,
        "offset_height": 0,
        "dimension_width": 344,
        "dimension_height": 194
      }
    }
  ],
  "unassociated_devices": [
    {
      "associated_modes": [],
      "is_connected": true,
      "is_primary": false,
      "device_name": "VGA-1",
      "device_model": "ASUS VW193S",
      "rotation": "normal",
      "reflection": "normal"
    }
  ]
}
```

> For the sake of brevity some parts of the schema have been omitted.

There is one thing to note here though, in order to decode the EDID hexadecimal string we need to import one external third-party dependency. I found the python library [pyedid](https://pypi.org/project/pyedid/) which does the job really well. Be aware I already have code for this, so I could push this in a PR.

Let me know guys, what you think.

**Comment by kellyjonbrazil** [comment]
I like the idea. Looks like we can easily vendor the `pyedid` library so we don't need external dependencies. PR is welcome!

**Comment by tzeikob** [comment]
Great, in the next days I'll have the changes in a PR for further review.

Just to clarify, by *vendor the pyedid* you mean to declare the dependency in some configuration file in jc so it will get installed along with other deps via pip3 during the installation process of jc, right?

Actually what I did in order to test my code is to just execute `pip3 install pyedid` and then added an import statement in the xrandr parser file.

**Comment by kellyjonbrazil** [comment]
No worries on the vendoring, I can clean that up later. It's very similar to how I did `asn1crypto`, `pbPlist`, and `tomli` in the `parsers` folder. This library looks so small it could even be in-lined in the `xrander.py` file as it's own class or something, too.

**Comment by tzeikob** [comment]
Okay, I'll start with the code now and we get to this pyedid dep later on.

**Comment by tzeikob** [comment]
@kellyjonbrazil the code #4848fce is almost ready to be pushed in a PR although I have to add a few test units.
Apart from that I did try to vendor the pyedid library the same way as with the other libs under parsers but I'm getting the following exception:

```sh
Traceback (most recent call last):
  File "/home/bob/.local/bin/jc", line 8, in <module>
    sys.exit(main())
  File "/home/bob/sources/jc/jc/cli.py", line 890, in main
    JcCli().run()
  File "/home/bob/sources/jc/jc/cli.py", line 872, in run
    self._run()
  File "/home/bob/sources/jc/jc/cli.py", line 836, in _run
    self.standard_parse_and_print()
  File "/home/bob/sources/jc/jc/cli.py", line 731, in standard_parse_and_print
    self.data_out = self.parser_module.parse(
  File "/home/bob/sources/jc/jc/parsers/xrandr.py", line 505, in parse
    screen = _parse_screen(linedata)
  File "/home/bob/sources/jc/jc/parsers/xrandr.py", line 323, in _parse_screen
    device: Optional[Device] = _parse_device(next_lines)
  File "/home/bob/sources/jc/jc/parsers/xrandr.py", line 377, in _parse_device
    edid: Optional[Edid] = _parse_edid(next_lines, quiet)
  File "/home/bob/sources/jc/jc/parsers/xrandr.py", line 430, in _parse_edid
    parsed = pyedid.parse_edid(edid_hex_value)
AttributeError: module 'jc.parsers.pyedid' has no attribute 'parse_edid'
```
Python is not my thing and its import mechanism had always confused me to be honest. I hope you might see what the root cuase is with this code.

**Comment by kellyjonbrazil** [comment]
Sweet! I put a couple suggestions in there. I'm not sure if you need to instantiate an Edid object - haven't taken that close a look, but you need to find the path to the class/function and import up to that point.

**Comment by tzeikob** [comment]
I did manage pyedid to work with the xrandr parser after a few modifications though in one file. It seems that there is not need to use the Registry helper and so I removed it from the Edid class. Not sure if this is legal, I mean by modifying the original code, nevertheless I added the license file just to be sure.

The PR is already pushed for further review.

**Comment by kellyjonbrazil** [comment]
Very cool! No worries on modifying the code - the license allows that. I’ll take a look in the next few days.

**Comment by kellyjonbrazil** [comment]
Pull Request merged and this will be included in the next release.
