### ISSUE TITLE
pyoxidizer folder missing?

### ISSUE THREAD

**Issue by ehab2012** [kellyjonbrazil/jc#369]
hello

I am trying to build a single binary and from 

https://kellyjonbrazil.github.io/jc-packaging/

its mentions pyoxidizer folder but cannot find.

can you please add the missing folder?

Thank you and best regards
ehab

**Comment by kellyjonbrazil** [comment]
Hi there! You'll want to go to the actual github repository here:
https://github.com/kellyjonbrazil/jc-packaging

Then you will get the `pyoxidizer` folder when cloning the repo.

Hope that helps!

**Comment by ehab2012** [comment]
affirmative 

Thank you
