### ISSUE TITLE
Can we release a arm version binary?

### ISSUE THREAD

**Issue by monsterxx03** [kellyjonbrazil/jc#374]
I checked jc's rpm package, seems it bundles python interpreter and dependencies into a single binary.

I try to make jc work on linux aarch64 server. Don't want to mess up with system python (for some reason, virtualenv is not a choice).

Can you give guides how you package the binary? I think you use some tools like PyInstaller. Just work to keep consistent with yours. Or release a aarch64 linux version is super helpful ! think you.

**Comment by monsterxx03** [comment]
Thank you! I'll have a try

**Comment by kellyjonbrazil** [comment]
I have created an arm64 binary, deb, and rpm in version 1.25.1:

https://github.com/kellyjonbrazil/jc/releases/tag/v1.25.1
