### ISSUE TITLE
add FortiOs config parsing

### ISSUE THREAD

**Issue by georgettica** [kellyjonbrazil/jc#376]
I found this repo and created an issue there
https://github.com/deyixtan/fortigate-config-parser/issues/2

maybe someone smarter than me can let me/him know how far from a possibility this merge is

**Comment by kellyjonbrazil** [comment]
Interesting! I'll take a look at this.

**Comment by kellyjonbrazil** [comment]
I added a quick-and-dirty prototype for a parser at https://github.com/deyixtan/fortigate-config-parser/issues/2. Not sure if I want to include this parser with `jc` as I have not tested the quality of the config parser.

**Comment by kellyjonbrazil** [comment]
Cool - you can put the `FortiGate.py` file in the directory above the `jcparsers` directory so the plugin parser will see it:

e.g.:
```
$HOME/.local/share/jc/FortiGate.py
$HOME/.local/share/jc/jcparsers/fortigate_parser.py
```
