### ISSUE TITLE
Include py.typed marker in library

### ISSUE THREAD

**Issue by BubuOT** [kellyjonbrazil/jc#377]
Hi!

I've noticed that `jc` (used as a python library) actually comes with type annotations but it doesn't include a `py.typed` maker file in the installed package, so type-checkers like mypy won't use it for type checking calls against the library.

I.e. you get such an error:
> error: Skipping analyzing "jc": module is installed, but missing library stubs or py.typed marker  [import]

Would it be possible to add this? Or is there a reason not to expose the type information to library consumers?

**Comment by BubuOT** [comment]
I went ahead and just added the marker file to my install. Now additionally mypy (in strict mode) complains about functions not being explicitly re-exported from the `jc` module.

This could be fixed by defining `__all__`  manually in `__init__.py` or  doing all import the following way:

```python
from .lib import (
         __version__ as __version__,
         parse as parse,
         parser_mod_list as parser_mod_list,
         plugin_parser_mod_list as plugin_parser_mod_list,
         standard_parser_mod_list as standard_parser_mod_list,
         streaming_parser_mod_list as streaming_parser_mod_list,
         parser_info as parser_info,
         all_parser_info as all_parser_info,
         get_help as get_help,
     ) 
```

**Comment by kellyjonbrazil** [comment]
Also interesting - I am doing explicit imports in `__init__.py`:
```
from .lib import (__version__, parse, parser_mod_list, plugin_parser_mod_list,
                  standard_parser_mod_list, streaming_parser_mod_list,
                  parser_info, all_parser_info, get_help)
```
I didn't realize mypy doesn't like it like that. Is there a reason why you would have to add the `foo as foo` style? Just curious.

**Comment by BubuOT** [comment]
> Hmmm... I see py.typed is making it into the tar.gz archive at package build, but not the wheel file. Will have to dig deeper.

Give me a second, I've tracked this problem down multiple times by now :)

**Comment by kellyjonbrazil** [comment]
Too funny! Seems to be a common oversight. 😄

**Comment by BubuOT** [comment]
> I didn't realize mypy doesn't like it like that. Is there a reason why you would have to add the foo as foo style? Just curious.

I don't know what the reasoning is behind this, no. Here's some background discussion though, that I found earlier: https://github.com/python/mypy/issues/7042

And here's fastapi changing it's imports to "from Y import X as X", where I got this idea from: https://github.com/tiangolo/fastapi/pull/2547/files

**Comment by kellyjonbrazil** [comment]
These fixes will make it into the next release.

**Comment by kellyjonbrazil** [comment]
Added in v1.23.1 release
