### ISSUE TITLE
jc fails on lsusb -v output for LTE modem

### ISSUE THREAD

**Issue by gschoenberger** [kellyjonbrazil/jc#380]
First of all, thanks for your great tool! We heavily rely on jc for converting Linux command outputs.

Currently jc is failing on the following output:
[lsusb-jc.txt](https://github.com/kellyjonbrazil/jc/files/11037805/lsusb-jc.txt)

With debug output I am getting the following exception:
```
# lsusb -s 001:003 -v | ./jc --lsusb -d
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "jc.cli", line 890, in main
  File "jc.cli", line 872, in run
  File "jc.cli", line 836, in _run
  File "jc.cli", line 731, in standard_parse_and_print
  File "jc.parsers.lsusb", line 936, in parse
  File "jc.parsers.lsusb", line 727, in _populate_lists
  File "jc.parsers.lsusb", line 552, in _add_attributes
KeyError: 'description'
```
Our version:
```
# ./jc --version
jc version:  1.23.0
python interpreter version:  3.10.9
python path:  /tmp/jc

https://github.com/kellyjonbrazil/jc
© 2019-2023 Kelly Brazil
```

Any chance to fix this soon? 
THX for your help, Georg

**Comment by kellyjonbrazil** [comment]
Thanks for reporting this! I'll take a look.

**Comment by kellyjonbrazil** [comment]
It looks to be an issue with this part of the `lsusb` output:
```
CDC MBIM:
        bcdMBIMVersion       1.00
        wMaxControlMessage   4096
        bNumberFilters       32
        bMaxFilterSize       128
        wMaxSegmentSize      2048
        bmNetworkCapabilities 0x20
          8-byte ntb input size
      CDC MBIM Extended:
        bcdMBIMExtendedVersion           1.00
        bMaxOutstandingCommandMessages     64
        wMTU                             1500
```
The `CDC MBIM Extended` section has different spacing than the rest. I don't think this will be too tough to fix.

**Comment by kellyjonbrazil** [comment]
I added support for the `CDC MBIM` and `CDC MBIM Extended` fields in the `dev` branch:
https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/lsusb.py

You can copy that file to your parser plugin directory to test:

- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

Let me know if you run into any other issues!

**Comment by kellyjonbrazil** [comment]
Added in v1.23.1 release
