### ISSUE TITLE
For Magic Syntax allow jc to read multiple files in a single run.

### ISSUE THREAD

**Issue by frosencrantz** [kellyjonbrazil/jc#389]
I would like to be able to use `jc` to read multiple files in one run, like this, and I would like jc to to print out JSON for each of the files listed in the args:

```
jc /proc/*/status
```

When I try running it now I see something like:

```
jc /proc/41*/status
jc:  Error - "/proc/413/status /proc/414/status /proc/415/status /proc/417/status /proc/41/status" file could not be opened: No such file or directory.
```

There is a workaround, it is possible to use tools like xargs  to run `jc` once per file.  I think this will be slower than what you would get from a single run.

**Comment by kellyjonbrazil** [comment]
Thinking more about this - I think we'd want to do the procfile detection on each run because there is no guarantee that every file entered will be the same type. Shouldn't be too hard to add.

**Comment by frosencrantz** [comment]
@kellyjonbrazil  I am not clear what this means.  Would it be possible to use globs expanded arguments  to `jc` or would this need to use the new `--slurp` flag?  Glad to see you are planning on adding this.

**Comment by kellyjonbrazil** [comment]
I have this working in `dev`. Don't need to use the `--slurp` flag since it is implied when the magic syntax sees multiple filenames. Need to a bit more testing, but think it is looking pretty good now.

**Comment by kellyjonbrazil** [comment]
https://github.com/kellyjonbrazil/jc/commit/289d188fffa4ba45b07d3a7832d2cc93815b5f15

**Comment by frosencrantz** [comment]
Thank you @kellyjonbrazil!  That works. 

I realized when trying this feature that the dicts returned do not say which file the data came from.  I ran `jc /proc/*/status`. Those files don't contain the pid, so it would be useful if the resulting dicts would also say which pid or which file the data came from.  This may already be there, but I missed it.  This would be a useful add on features.

**Comment by muescha** [comment]
> I realized when trying this feature that the dicts returned do not say which file the data came from. I ran `jc /proc/*/status`. 

I have done a comment to the commit addressing this issue with the idea to returning an dict with the filename as key value:
https://github.com/kellyjonbrazil/jc/commit/289d188fffa4ba45b07d3a7832d2cc93815b5f15#r136843543

```json
{
	"/proc/meminfo": "<parser-output:meminfo>",
	"/proc/locks": "<parser-output:locks>",
	"/proc/410/status": "<parser-output:status>",
	"/proc/414/status": "<parser-output:status>"
}
```

**Comment by kellyjonbrazil** [comment]
I agree - I can either add a metafield like `_file` that contains the filename or use the filename as the key in a dict. The former is more consistent with the existing slurp behavior and is probably easier to implement. I can see if the latter isn't too hard to implement, but it is a little different than the way `jc` implements lists of objects in other instances.

**Comment by muescha** [comment]
when `_file` then also `_pid` and `_type` can be extracted in this step.
this meta should be there only on slurp? or it can extracted with every `proc_*` parser (when known)?

**Comment by frosencrantz** [comment]
If possible, it should be in both cases slurp and magic parse.  That information is useful.  When possible, make that information available.  I personally like having `_file` over one that the actual filename.

**Comment by kellyjonbrazil** [comment]
The only issue I ran into when implementing `_file` within the output is that in the case of a list of objects, we need to add `_file` to every object. Not the end of the world, but it does make discovering the file a bit awkward for those cases. That's why I'm leaning toward using the `--meta-out` option to list the files in order. I could make the output for the magic `proc` syntax to be the same as `--slurp`... that is wrap the entire slurped output into a dictionary with a key of `slurped`. Then the file information can be listed in the `_jc_meta` key as in https://github.com/kellyjonbrazil/jc/issues/506#issuecomment-1904703594.

**Comment by kellyjonbrazil** [comment]
Please see https://github.com/kellyjonbrazil/jc/issues/506 for the latest on this implementation.

**Comment by kellyjonbrazil** [comment]
Added in [v1.25.0](https://github.com/kellyjonbrazil/jc/releases/tag/v1.25.0)
