### ISSUE TITLE
XML: Process comments?

### ISSUE THREAD

**Issue by defensivedepth** [kellyjonbrazil/jc#406]
I have an XML file with extensive comments - there does not appear to be a way to process these comments at all with jc?

**Comment by kellyjonbrazil** [comment]
Hi there thanks for reporting this. `jc` should be able to support comments in xml documents:
```
% echo '<?xml version = "1.0" encoding = "UTF-8" ?>
<!--Students grades are uploaded by months-->
<class_list>
   <student>
      <name>Tanmay</name>
      <grade>A</grade>
   </student>
</class_list>' | jc --xml -p
{
  "class_list": {
    "student": {
      "name": "Tanmay",
      "grade": "A"
    }
  }
}
```
Could you provide a sanitized example that is not working for you? `jc` uses the xmltodict library at https://github.com/martinblech/xmltodict, so it should be able to support whatever xmltodict supports.

**Comment by defensivedepth** [comment]
Just getting back to this, I apologize for leaving it hanging. Even if your example, it does not appear that `<!--Students grades are uploaded by months-->` is parsed out into a separate field?

That's what I am looking for - to have `Students grades are uploaded by months` parsed into a field.

**Comment by kellyjonbrazil** [comment]
Ah, I see... You want to include comments in the JSON response instead of ignore them. Not sure if this is possible, but I'll check.

**Comment by kellyjonbrazil** [comment]
For investigation: https://github.com/martinblech/xmltodict/issues/232

**Comment by kellyjonbrazil** [comment]
Looks like processing comments might be flaky in some instances. Could do with a `try/except` so comment parsing is best-effort.

**Comment by kellyjonbrazil** [comment]
I have an update for this in the dev branch. Could you test by copying the `xml.py` file to your plugin directory?

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/xml.py

- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

Thanks!

**Comment by defensivedepth** [comment]
Fantastic! OOO right now, will test it out when I am back in next week, thanks!

**Comment by kellyjonbrazil** [comment]
Added in v1.23.5
