### ISSUE TITLE
[new parser request] .srt subtitle file

### ISSUE THREAD

**Issue by 07416** [kellyjonbrazil/jc#411]
https://en.wikipedia.org/wiki/SubRip

Presumably would be trivial to implement: remove lines containing the subtitle track numbers and timestamps, merge split lines.

**Comment by kellyjonbrazil** [comment]
This is ready to go for the next release. Thanks M.R. for building the parser!

**Comment by kellyjonbrazil** [comment]
Released in v1.23.3
