### ISSUE TITLE
Line by line parsing

### ISSUE THREAD

**Issue by mitar** [kellyjonbrazil/jc#418]
I have a stream of timestamps:

```
while true; do
  date
  sleep 1
done
```

I would like to pass this through jc to parse it into JSONs, one per line. But it seems this is not possible?

**Comment by kellyjonbrazil** [comment]
Hi there!

Does this provide the expected output?

```

while true; do
  date | jc —date
  sleep 1
done
```

**Comment by mitar** [comment]
Suure. But I do not control how is the stream of dates generates. That was just an example/reproduction to motivate this issue.

**Comment by mitar** [comment]
No hurry. I think it would be nice if any plugin could be converted to a stream one by simply reapplying it again and again on the stream. But probably that would require from each plugin to have a concept of chunks.

**Comment by mitar** [comment]
I got some inspiration from your [blog post](https://blog.kellybrazil.com/2019/11/26/bringing-the-unix-philosophy-to-the-21st-century/) and made [regex2json](https://gitlab.com/tozd/regex2json) tool which allows conversion of test-based data into JSON by just providing a regex. So similar to how jc works, but for more ad-hoc use cases where you write the pattern as CLI argument. And it also operates on line-to-line. This I think nicely works together with the jc tool and other tools operating on JSON.

So the example above could then be:

```sh
$ while true; do LC_TIME=C date; sleep 1; done | regex2json "(?P<date___time__UnixDate__RFC3339>.+)"
{"date":"2023-06-13T11:26:45Z"}
{"date":"2023-06-13T11:26:46Z"}
{"date":"2023-06-13T11:26:47Z"}
```
