### ISSUE TITLE
New parser for ```find```

### ISSUE THREAD

**Issue by solomonleang** [kellyjonbrazil/jc#431]
I made a parser for the find command in Linux. As of right now, it would parse all the files names or empty directories and provide a path to the parent directory of where this item is in.

Here is the schema that I am using:
```
[
      {
        "directory path":           string,
        "file or empty directory:   string
      }
   ]
```

For example, if the find command outputted this result:
```
.
./
./jc
./jc/tests
./jc/tests/test_find.py
./jc/tests/test_history.py
./jc/tests/test_hosts.py
./jc/anotherdirectory
```

The parser would take that data in and will output:
```
[{"directory path": "./jc/tests/","file or empty directory": "test_find.py"},
{"directory path": "./jc/tests/","file or empty directory": "test_history.py"},
{"directory path": "./jc/tests/","file or empty directory": "test_hosts.py"},
{"directory path": "./jc/","file or empty directory": "anotherdirectory"}]
```

I submitted a pull request and if you could review that for any changes to make that would be great!

**Comment by kellyjonbrazil** [comment]
Thank you for the parser contribution! I'll review in the PR.

**Comment by kellyjonbrazil** [comment]
Added in v1.23.4
