### ISSUE TITLE
Proposal "lsb_release -a" parser

### ISSUE THREAD

**Issue by DEvil0000** [kellyjonbrazil/jc#435]
Would be great to have this parser
I would expect something like this as a parser result:
`lsb_release -a | jq -nR 'reduce ( inputs | split(":\t") ) as [ $k, $v ] ( {}; . + { ($k): $v } )'`
```json
{
  "Distributor ID": "Ubuntu",
  "Description": "Ubuntu 20.04.6 LTS",
  "Release": "20.04",
  "Codename": "focal"
}
```

**Comment by kellyjonbrazil** [comment]
Thank you for the parser suggestion. I think it makes sense and should be pretty easy to implement.

**Comment by don-rumata** [comment]
This work for me: `lsb_release -a 2>/dev/null | jc --kv -p`. And `cat /etc/os-release | jc --kv -p`.

**Comment by kellyjonbrazil** [comment]
Ah yes, hadn't looked at the file in a while. Didn't realize it's just a key/value pair type. @don-rumata is right, you can use the `--kv` parser for this.

**Comment by don-rumata** [comment]
Maybe you should add an **alias** for the `--kv` key? `--lsb-release`.

**Comment by kellyjonbrazil** [comment]
Not a bad idea - I can do that in the upcoming release.

**Comment by kellyjonbrazil** [comment]
I have added a `lsb_release` and `/etc/os-release` parser that will be included in the next release. These are just aliases to the `kv` parser.

**Comment by kellyjonbrazil** [comment]
Added in v1.23.5
