### ISSUE TITLE
Support for AWS key[name]/value format

### ISSUE THREAD

**Issue by n8felton** [kellyjonbrazil/jc#436]
Wondering if this is possible today, and if not, potentially add it as a feature request.

[Passing `environment` in a AWS ECS task definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html) uses a different format than most JSON. 

AWS actually does this in a lot of places, but this is my most recent annoyance with it.

```
    "environment": [
      {
        "name": "string",
        "value": "string"
      }
    ]
```
The goal would be to take something like

```
HOST=db.host
USER=root
PASSWORD=betterlucknexttime!
```
and output it like (or similar)
```
{
  "name": "HOST",
  "value": "db.host"
},
{
  "name": "USER",
  "value": "root"
},
{
  "name": "PASSWORD",
  "value": "betterlucknexttime!"
},
```

**Comment by kellyjonbrazil** [comment]
Hi there! If I'm understanding correctly, the `env` parser already does this:
```
% echo 'HOST=db.host
USER=root
PASSWORD=betterlucknexttime!' | jc --env -p
[
  {
    "name": "HOST",
    "value": "db.host"
  },
  {
    "name": "USER",
    "value": "root"
  },
  {
    "name": "PASSWORD",
    "value": "betterlucknexttime!"
  }
]
```
You can also have it in this format with the `-r` (raw) option:
```
% echo 'HOST=db.host
USER=root
PASSWORD=betterlucknexttime!' | jc --env -rp
{
  "HOST": "db.host",
  "USER": "root",
  "PASSWORD": "betterlucknexttime!"
}
```

**Comment by n8felton** [comment]
So it does! I overlooked the `env` parser and was looking at the `kv` parser. Thanks for pointing it out!
