### ISSUE TITLE
pidstat bug with two output tables

### ISSUE THREAD

**Issue by vsoch** [kellyjonbrazil/jc#441]
There seems to be a bug with the pidstat parser that it expects one header for the table. As an example in the output below, adding `-T ALL` is going to show us the chosen task plus global set (see man pages here) but what jc seems to be doing is using the top level header, and then shoving the second row of values into it.

![image](https://github.com/kellyjonbrazil/jc/assets/814322/3f9b47ca-244a-4cec-8eea-5bbdade60f83)

E.g., the "command" for the second entry in the list, "sleep" has a header of "percent_wait" and it should be command.

**Comment by kellyjonbrazil** [comment]
Thanks for reporting this - I'll take a closer look at this in the next few days.

**Comment by vsoch** [comment]
Thanks @kellyjonbrazil ! For a workaround, I'm doing two separate calls, one for CHILD and for one TASK, and then parsing them separately, but it would be good to get them both at the same time in the list!

**Comment by kellyjonbrazil** [comment]
Couple of things:

1. You'll probably want to use `pidstat -hH` if you can so `jc` can properly parse the timestamp field
2. I didn't realize that multiple table-types could be output (as when using `-T`) so `jc` currently just looks up the columns of the first table it finds and applies it to the rest of the data. I'll need to rewrite the parser to check the table columns each time there is a header row.

**Comment by kellyjonbrazil** [comment]
I have a fix in the `dev` branch it would be great if you could test. You can copy the new parser files to your plugin directory:

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/pidstat.py
https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/pidstat_s.py

- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

Could you let me know if that works for you? I'll get this in the next release. Thanks!

**Comment by vsoch** [comment]
Thank you! I should be able to make some time this week to test this out in the operator where it is working - just added to my TODO and will send you an update when I do.

**Comment by vsoch** [comment]
hey! Apologies for the wait - I just tested it out, and it looks great!

![image](https://github.com/kellyjonbrazil/jc/assets/814322/45694beb-516c-452e-aeb6-233fbbe9fd26)

Please release away - I'll update my tools with the new release when you do. Thank you!

**Comment by kellyjonbrazil** [comment]
Added in v1.23.5
