### ISSUE TITLE
x509 parser crashes for certificates with negative serial number

### ISSUE THREAD

**Issue by sumezulike** [kellyjonbrazil/jc#444]
Trying to parse a certificate with a negative serial number causes the following exception:
`OverflowError: can't convert negative int to unsigned`

According to [RFC 5280](https://www.rfc-editor.org/rfc/rfc5280#section-4.1.2.2):
> The serial number MUST be a positive integer

but also

> Note: Non-conforming CAs may issue certificates with serial numbers
   that are negative or zero.  Certificate users SHOULD be prepared to
   gracefully handle such certificates.
   
I've been receiving a number of certificates with negative serial numbers and would suggest implementing the same behaviour as OpenSSL:
```
$ openssl x509 -text -in negative_serial.pem -nocert
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
             (Negative)43:21:98:76:dc:ba:00:00:43:21:98:76:dc:ba:00:00:11:11:00:00
...
```
Here is an example certificate to test this with:
[negative_serial.pem.txt](https://github.com/kellyjonbrazil/jc/files/12465608/negative_serial.pem.txt)
(.txt because GitHub doesn't like .pem)

**Comment by kellyjonbrazil** [comment]
Thanks for opening this issue and for the nice fix! I'll get this into the next release.

**Comment by kellyjonbrazil** [comment]
Added in v1.23.5
