### ISSUE TITLE
bug in handling multiline vars in the "env" parser

### ISSUE THREAD

**Issue by smolin** [kellyjonbrazil/jc#448]
Apparently, if an env var contains a newline, it can cause the "env" parser to choke. In my example, I'm using "grep -A 1" to extract just the problem env var:

```
% export ZORK='line 1
line 2'

% env | grep -A 1 ZORK
ZORK=line 1
line 2

% env | grep -a1 ZORK | jc --env
jc:  Error - env parser could not parse the input data.
             If this is the correct parser, try setting the locale to C (LC_ALL=C).
             For details use the -d or -dd option. Use "jc -h --env" for help.
```

**Comment by kellyjonbrazil** [comment]
Thanks for reporting this! I'll take a look in the next few days.

**Comment by kellyjonbrazil** [comment]
I could do a naive fix for this where lines that have a single `=` in them are variable definitions, but then we have this corner case:
```
% MYVAR='hello world
quote> hello=world'
% echo $MYVAR
hello world
hello=world
% export MYVAR
% env
...
MYVAR=hello world
hello=world
...
```
Not sure if that's a valid concern. I suppose it exists in the current parser as well.

**Comment by kellyjonbrazil** [comment]
I have a fix in the `dev` branch. Could you test by copying the `env.py` file into your plugin folder?

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/env.py

- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

**Comment by kellyjonbrazil** [comment]
Added in v1.23.5
