### ISSUE TITLE
Issue parsing destination-unreachable ping on Ubuntu 22.04

### ISSUE THREAD

**Issue by abreis** [kellyjonbrazil/jc#452]
The following command and output fails to parse using `jc-1.23.4`:

```shell
LC_ALL=C ping -c 3 10.0.3.22
```
```
PING 10.0.3.22 (10.0.3.22) 56(84) bytes of data.
From 10.0.0.1 icmp_seq=1 Destination Host Unreachable
From 10.0.0.1 icmp_seq=2 Destination Host Unreachable
From 10.0.0.1 icmp_seq=3 Destination Host Unreachable

--- 10.0.3.22 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2049ms
pipe 3
```

This is using Ubuntu 22.04.3 and `iputils-ping=3:20211215-1`.

<details><summary> Debug output</summary>
<p>
IndexError
Python 3.10.9: /usr/local/bin/jc
Sun Sep 10 12:26:38 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/abreis/<string> in <module>()

 /home/abreis/jc.cli in main()

 /home/abreis/jc.cli in run(self=<jc.cli.JcCli object>)

 /home/abreis/jc.cli in _run(self=<jc.cli.JcCli object>)

 /home/abreis/jc.cli in standard_parse_and_print(self=<jc.cli.JcCli object>)

 /home/abreis/jc.parsers.ping in parse(data='PING 10.0.3.22 (10.0.3.22) 56(84) bytes of data.... +3 errors, 100% packet loss, time 2043ms\npipe 3\n', raw=False, quiet=False)

 /home/abreis/jc.parsers.ping in _linux_parse(data='PING 10.0.3.22 (10.0.3.22) 56(84) bytes of data.... +3 errors, 100% packet loss, time 2043ms\npipe 3\n')

IndexError: list index out of range
    __cause__ = None
    __class__ = <class 'IndexError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of IndexError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of IndexError object>
    __doc__ = 'Sequence index out of range.'
    __eq__ = <method-wrapper '__eq__' of IndexError object>
    __format__ = <built-in method __format__ of IndexError object>
    __ge__ = <method-wrapper '__ge__' of IndexError object>
    __getattribute__ = <method-wrapper '__getattribute__' of IndexError object>
    __gt__ = <method-wrapper '__gt__' of IndexError object>
    __hash__ = <method-wrapper '__hash__' of IndexError object>
    __init__ = <method-wrapper '__init__' of IndexError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of IndexError object>
    __lt__ = <method-wrapper '__lt__' of IndexError object>
    __ne__ = <method-wrapper '__ne__' of IndexError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of IndexError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of IndexError object>
    __repr__ = <method-wrapper '__repr__' of IndexError object>
    __setattr__ = <method-wrapper '__setattr__' of IndexError object>
    __setstate__ = <built-in method __setstate__ of IndexError object>
    __sizeof__ = <built-in method __sizeof__ of IndexError object>
    __str__ = <method-wrapper '__str__' of IndexError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('list index out of range',)
    with_traceback = <built-in method with_traceback of IndexError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "jc.cli", line 890, in main
  File "jc.cli", line 872, in run
  File "jc.cli", line 836, in _run
  File "jc.cli", line 731, in standard_parse_and_print
  File "jc.parsers.ping", line 641, in parse
  File "jc.parsers.ping", line 349, in _linux_parse
IndexError: list index out of range
</p>
</details>

**Comment by abreis** [comment]
By the way, thank you for writing `jc`, it's been a real time saver. Cheers

**Comment by kellyjonbrazil** [comment]
Thanks for reporting this! We are working on some `ping` parser updates in this release so we can get these fixes in, too.

**Comment by abreis** [comment]
Ah, I can see that #442 fixes this. Thanks!
