### ISSUE TITLE
xrandr parser screen association issue

### ISSUE THREAD

**Issue by marcin-koziol** [kellyjonbrazil/jc#453]
It seems that in this situation, both outputs should be in {'screens': [{'screen_number': 0, [...] associated_devices array

```
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
DP-1 disconnected primary (normal left inverted right x axis y axis)
DP-2 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 521mm x 293mm
   1920x1080     60.00*+  59.94    60.00  
   1680x1050     60.00    59.88  
   1400x1050     60.00  
   1600x900      60.00  
   1280x1024     75.02    60.02    60.00  
```
meanwhile DP-2 is in unassociated_devices

**Comment by kellyjonbrazil** [comment]
@lyterk could you take a look at this?

**Comment by lyterk** [comment]
Sure, taking a look

**Comment by lyterk** [comment]
@kellyjonbrazil This should be ready to review, lemme know if you want me to bust out the commits more discretely

**Comment by kellyjonbrazil** [comment]
Thanks @lyterk! I'll take a look.

**Comment by kellyjonbrazil** [comment]
Added in v1.23.5
