### ISSUE TITLE
New Parser: airport -I

### ISSUE THREAD

**Issue by chrisbergeron** [kellyjonbrazil/jc#46]
It would be nice to have a parser for the Mac OSX 'airport' command.  Output of 'airport -I' is:
     agrCtlRSSI: -73
     agrExtRSSI: 0
    agrCtlNoise: -92
    agrExtNoise: 0
          state: running
        op mode: station
     lastTxRate: 176
        maxRate: 867
lastAssocStatus: 0
    802.11 auth: open
      link auth: wpa2-psk
          BSSID: 58:d9:d5:3:40:35
           SSID: Tenda_034030_5G
            MCS: 2
        channel: 36,80

**Comment by kellyjonbrazil** [comment]
Hey there - thanks for the request! What program should I install on my Mac to get airport? Is it a brew install?

**Comment by chrisbergeron** [comment]
I think it's built in to OS X:
/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport
I symlinked it into /usr/local/bin

If you don't have it there, I'll see what package I used to install it.

**Comment by chrisbergeron** [comment]
airport -s is also a very useful one (in addition to -i [uppercase]):
airport -s

                            SSID BSSID             RSSI CHANNEL HT CC SECURITY (auth/unicast/group)
                           Papa2 20:25:64:b3:e5:98 -83  1       Y  US WPA2(PSK/AES/AES)
                     xfinitywifi 82:f2:9e:c8:9d:40 -88  1       Y  US NONE
                     xfinitywifi e2:88:5d:7a:e1:70 -81  1       Y  -- NONE
                     RedHot Spot 78:f2:9e:d6:a7:28 -88  6       Y  US WPA2(PSK/AES/AES)
                     xfinitywifi 0a:c0:3e:3f:d1:1c -73  6       Y  US NONE

**Comment by kellyjonbrazil** [comment]
Ah yes, I see it there. Cool - looks pretty simple to parse so I'll add it to the next release.

**Comment by kellyjonbrazil** [comment]
Now supporting `airport -I` and `airport -s`:
### airport -I
```
$ airport -I | jc --airport -p
{
  "agrctlrssi": -66,
  "agrextrssi": 0,
  "agrctlnoise": -90,
  "agrextnoise": 0,
  "state": "running",
  "op_mode": "station",
  "lasttxrate": 195,
  "maxrate": 867,
  "lastassocstatus": 0,
  "802_11_auth": "open",
  "link_auth": "wpa2-psk",
  "bssid": "3c:37:86:15:ad:f9",
  "ssid": "SnazzleDazzle",
  "mcs": 0,
  "channel": "48,80"
}
```
### airport -s
```
$ airport -s | jc --airport-s -p
[
  {
    "ssid": "DIRECT-4A-HP OfficeJet 3830",
    "bssid": "00:67:eb:2a:a7:3b",
    "rssi": -90,
    "channel": "6",
    "ht": true,
    "cc": "--",
    "security": [
      "WPA2(PSK/AES/AES)"
    ]
  },
  {
    "ssid": "Latitude38",
    "bssid": "c0:ff:d5:d2:7a:f3",
    "rssi": -85,
    "channel": "11",
    "ht": true,
    "cc": "US",
    "security": [
      "WPA2(PSK/AES/AES)"
    ]
  },
  {
    "ssid": "xfinitywifi",
    "bssid": "6e:e3:0e:b8:45:99",
    "rssi": -83,
    "channel": "11",
    "ht": true,
    "cc": "US",
    "security": [
      "NONE"
    ]
  },
  ...
]
```

**Comment by chrisbergeron** [comment]
Awesome, thank you!

**Comment by kellyjonbrazil** [comment]
You got it! Still working on some other things but this should go out in the 1.9.0 release soon.

**Comment by kellyjonbrazil** [comment]
You should be able to do a `pip3 install --upgrade jc` to get the new airport parsers.

Happy parsing!
kb
