### ISSUE TITLE
Wrong parsing with no jump target in iptables

### ISSUE THREAD

**Issue by nkakouros** [kellyjonbrazil/jc#462]
1. Create a rule with no jump target, like:

```
sudo iptables -A INPUT --protocol udp
```

2. List the rules:

```
sudo iptables -L
```

This gives:

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
           udp  --  anywhere             anywhere

...
```

3. List the rules with jc:

```
sudo iptables -L | jc --iptables | jq
```

This gives:

```
...
{
  "target": "udp",
  "prot": "--",
  "opt": "0.0.0.0/0",
  "source": "0.0.0.0/0"
}
...
```

`target` should be omitted and `prot` should be `udp`.

**Comment by kellyjonbrazil** [comment]
Thanks for reporting this!

**Comment by nkakouros** [comment]
Thank you for this wonderful application!

________________________________

**Comment by kellyjonbrazil** [comment]
I have a fix for this in the `dev` branch. Could you copy the parser file below into your plugin directory to test?

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/iptables.py

- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

Thanks!

**Comment by kellyjonbrazil** [comment]
Delivered in v1.24.0: https://github.com/kellyjonbrazil/jc/releases/tag/v1.24.0
