### ISSUE TITLE
nsd-parser clean up

### ISSUE THREAD

**Issue by kellyjonbrazil** [kellyjonbrazil/jc#466]
Hi @pettai. I have merged in the new `nsd-control` command parser but there are a couple of parts in the `parse` function that don't look like they are doing anything as the variables are not defined or used anywhere. Can you take a look in the `dev` branch and see if you need to make any changes and/or add some tests?

https://github.com/kellyjonbrazil/jc/blob/0a028456bf224d8491d95a1fc5662f5baeedcae5/jc/parsers/nsd_control.py#L161-L169

Thanks!

**Comment by pettai** [comment]
Good that you caught it 👍  I rewrote parts of the parser and apparently missed those :( 
`cookies.update` should be changed to `itr.update`, then it works as expected.

**Comment by kellyjonbrazil** [comment]
Cool I made the changes and pushed to `dev`. Thanks!

**Comment by pettai** [comment]
ok, via a new pull request?

**Comment by kellyjonbrazil** [comment]
Yes, that would be perfect - thanks!

**Comment by pettai** [comment]
Here https://github.com/kellyjonbrazil/jc/pull/468 you go

**Comment by kellyjonbrazil** [comment]
Looks great, thanks!
