### ISSUE TITLE
The df parser does not support df output when it's not in English

### ISSUE THREAD

**Issue by marcuoli** [kellyjonbrazil/jc#467]
Ex:

```Sist. Arq.                           1K-blocos      Usado Disponível Uso% Montado em
devtmpfs                             197148512          0  197148512   0% /dev
tmpfs                                394496000    9922948  384573052   3% /dev/shm
tmpfs                                197196536       5900  197190636   1% /run
tmpfs                                197196536          0  197196536   0% /sys/fs/cgroup
/dev/mapper/VGExaDb-LVDbSys1          36689920   19158764   17531156  53% /
/dev/sda1                               521792      81540     440252  16% /boot
/dev/sda2                               260094       7455     252639   3% /boot/efi
/dev/mapper/vg-lv1                     2086912    1494932     591980  72% /var
/dev/mapper/vg-lv2                     4184064    2134508    2049556  52% /home
/dev/mapper/vg-lv3                     3135488    1027488    2108000  33% /tmp
/dev/mapper/vg-lv4                    29349888    9861860   19488028  34% /var/log
/dev/mapper/vg-lv5                     1038336     145844     892492  15% /var/log/audit
/dev/mapper/vg-lv6                   629094400  398803976  230290424  64% /fs6
tmpfs                                 39439308          0   39439308   0% /run/user/1001```

**Comment by kellyjonbrazil** [comment]
Hi there - thanks for reporting this. I believe this is working as designed. Could you try prepending `LC_ALL=C` to the command per the recommendation [here](https://github.com/kellyjonbrazil/jc#locale)?

```
LC_ALL=C  df
```

**Comment by marcuoli** [comment]
Here is the test:

root@xxxxxxx:~# LC_ALL=C df | jc --df
jc:  Error - df parser could not parse the input data. Did you use the correct parser?
             For details use the -d or -dd option. Use "jc -h" for help.

root@xxxxxxx:~# df
Sist. Arq. 1K-blocos Usado Disponível Uso% Montado em
devtmpfs 197148512 0 197148512 0% /dev
tmpfs 394496000 9922948 384573052 3% /dev/shm
tmpfs 197196536 5900 197190636 1% /run
tmpfs 197196536 0 197196536 0% /sys/fs/cgroup
/dev/mapper/VGExaDb-LVDbSys1 36689920 19158764 17531156 53% /
/dev/sda1 521792 81540 440252 16% /boot
/dev/sda2 260094 7455 252639 3% /boot/efi
/dev/mapper/vg-lv1 2086912 1494932 591980 72% /var
/dev/mapper/vg-lv2 4184064 2134508 2049556 52% /home
/dev/mapper/vg-lv3 3135488 1027488 2108000 33% /tmp
/dev/mapper/vg-lv4 29349888 9861860 19488028 34% /var/log
/dev/mapper/vg-lv5 1038336 145844 892492 15% /var/log/audit
/dev/mapper/vg-lv6 629094400 398803976 230290424 64% /fs6
tmpfs 39439308 0 39439308 0% /run/user/1001
root@xxxxxxx:~#

root@xxxxxxx:~# df |jc --df -d
Traceback (most recent call last):
  File "/usr/bin/jc", line 33, in <module>
    sys.exit(load_entry_point('jc==1.17.3', 'console_scripts', 'jc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jc/cli.py", line 643, in main
    result = parser.parse(data, raw=raw, quiet=quiet)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jc/parsers/df.py", line 234, in parse
    raw_output = jc.parsers.universal.sparse_table_parse(fix_data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jc/parsers/universal.py", line 89, in sparse_table_parse
    while h_end > 0 and entry[h_end] not in string.whitespace:
                        ~~~~~^^^^^^^
IndexError: string index out of range
root@xxxxxxx:~#

Thanks !

**Comment by kellyjonbrazil** [comment]
Thanks - can you past the output of `LC_ALL=C df`?

**Comment by marcuoli** [comment]
# LC_ALL=C df
Sist. Arq. 1K-blocos Usado Disponível Uso% Montado em
devtmpfs 197148512 0 197148512 0% /dev
tmpfs 394496000 9922948 384573052 3% /dev/shm
tmpfs 197196536 5900 197190636 1% /run
tmpfs 197196536 0 197196536 0% /sys/fs/cgroup
/dev/mapper/VGExaDb-LVDbSys1 36689920 19158764 17531156 53% /
/dev/sda1 521792 81540 440252 16% /boot
/dev/sda2 260094 7455 252639 3% /boot/efi
/dev/mapper/vg-lv1 2086912 1494932 591980 72% /var
/dev/mapper/vg-lv2 4184064 2134508 2049556 52% /home
/dev/mapper/vg-lv3 3135488 1027488 2108000 33% /tmp
/dev/mapper/vg-lv4 29349888 9861860 19488028 34% /var/log
/dev/mapper/vg-lv5 1038336 145844 892492 15% /var/log/audit
/dev/mapper/vg-lv6 629094400 398803976 230290424 64% /fs6
tmpfs 39439308 0 39439308 0% /run/user/1001

OEL 7

**Comment by kellyjonbrazil** [comment]
Sorry, could you paste it in again between triple backticks (\`\`\`)so it will preserve formatting?
```
This way preserves formatting.
```
Thanks!

**Comment by marcuoli** [comment]
```
# LC_ALL=C df
Sist. Arq. 1K-blocos Usado Disponível Uso% Montado em
devtmpfs 197148512 0 197148512 0% /dev
tmpfs 394496000 9922948 384573052 3% /dev/shm
tmpfs 197196536 5900 197190636 1% /run
tmpfs 197196536 0 197196536 0% /sys/fs/cgroup
/dev/mapper/VGExaDb-LVDbSys1 36689920 19158764 17531156 53% /
/dev/sda1 521792 81540 440252 16% /boot
/dev/sda2 260094 7455 252639 3% /boot/efi
/dev/mapper/vg-lv1 2086912 1494932 591980 72% /var
/dev/mapper/vg-lv2 4184064 2134508 2049556 52% /home
/dev/mapper/vg-lv3 3135488 1027488 2108000 33% /tmp
/dev/mapper/vg-lv4 29349888 9861860 19488028 34% /var/log
/dev/mapper/vg-lv5 1038336 145844 892492 15% /var/log/audit
/dev/mapper/vg-lv6 629094400 398803976 230290424 64% /fs6
tmpfs 39439308 0 39439308 0% /run/user/1001
```

**Comment by marcuoli** [comment]
```
# LC_ALL=C df |cat -A
Sist. Arq. 1K-blocos Usado DisponM-CM--vel Uso% Montado em$
devtmpfs 197148512 0 197148512 0% /dev$
tmpfs 394496000 9922948 384573052 3% /dev/shm$
tmpfs 197196536 5900 197190636 1% /run$
tmpfs 197196536 0 197196536 0% /sys/fs/cgroup$
/dev/mapper/VGExaDb-LVDbSys1 36689920 19158764 17531156 53% /$
/dev/sda1 521792 81540 440252 16% /boot$
/dev/sda2 260094 7455 252639 3% /boot/efi$
/dev/mapper/vg-lv1 2086912 1494932 591980 72% /var$
/dev/mapper/vg-lv2 4184064 2134508 2049556 52% /home$
/dev/mapper/vg-lv3 3135488 1027488 2108000 33% /tmp$
/dev/mapper/vg-lv4 29349888 9861860 19488028 34% /var/log$
/dev/mapper/vg-lv5 1038336 145844 892492 15% /var/log/audit$
/dev/mapper/vg-lv6 629094400 398803976 230290424 64% /fs6$
tmpfs 39439308 0 39439308 0% /run/user/1001$
```

**Comment by kellyjonbrazil** [comment]
Strange, I'm not able to reproduce this. I installed OEL7 in a VM (minimal install) with Spanish as the default language. When I run `LC_ALL=C df` I get this, which should work with `jc`

<img width="572" alt="image" src="https://github.com/kellyjonbrazil/jc/assets/24423665/97de8e08-b488-49c7-a0ff-a2ab272981d4">

I wonder if the default localization packages may have been removed from your system?

**Comment by marcuoli** [comment]
Ah ok, now I see what you wanted. 

The problem is that I receive the outputs from other systems so LC_ALL is not an option. This way this approach would. I was simulating df using an alias to 'cat df.txt'.

Running from the system itself probably would work as you expected. You are totally right.

Thanks anyway.

**Comment by kellyjonbrazil** [comment]
Oh, I see! Yes, this would probably require a new parser. It is possible to take the existing `df` parser, modify it for Spanish language, then add it to the plugin folder.

https://github.com/kellyjonbrazil/jc/blob/master/jc/parsers/df.py

- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

**Comment by marcuoli** [comment]
Sorry to reply so late. I will look into it. Just a little adjustment, it's
Portuguese from Brazil (We do not speak Spanish in Brazil) :P

Thank you. Regards

Marcus

"Eu andarei vestido e armado com as armas de São Jorge para que meus
inimigos, tendo pés não me alcancem, tendo mãos não me peguem, tendo olhos
não me vejam, e nem em pensamentos eles possam me fazer mal."

**Comment by kellyjonbrazil** [comment]
Ah, my apologies - not sure why I assumed it was Spanish. Yes, my last name is Brazil and I am part Portuguese, myself. 😄 🇧🇷
