### ISSUE TITLE
Prebuilt binaries for Windows weren't released at v1.23.6

### ISSUE THREAD

**Issue by suzuki-shunsuke** [kellyjonbrazil/jc#478]
https://github.com/kellyjonbrazil/jc/releases/tag/v1.23.6

<img width="320" alt="image" src="https://github.com/kellyjonbrazil/jc/assets/13323303/86aa1dcf-2f1c-43f8-b72d-c042b30bd614">

Could you release prebuilt binaries for Windows at v1.23.6?

**Comment by kellyjonbrazil** [comment]
Will do - I was going to wait until tomorrow morning because I didn't think anyone would notice. 😄 Windows binary should be done compiling in a few minutes.

**Comment by kellyjonbrazil** [comment]
Binaries are now up!

**Comment by suzuki-shunsuke** [comment]
Thank you!
