### ISSUE TITLE
New parser request: Debian/Ubuntu Packages index

### ISSUE THREAD

**Issue by don-rumata** [kellyjonbrazil/jc#480]
Hi! Can you add a `Packages` parser?

Example:
https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/Packages

https://mirror.yandex.ru/ubuntu/dists/jammy/main/binary-amd64/Packages.gz

This is `yaml`, but `jc --yaml` - not work.

**Comment by kellyjonbrazil** [comment]
Hi there - yes, this seems like something easy to parse. It looks close to YAML, but not quite. (no `---` separators between packages and no text continuation escapes above indented multiline values)

**Comment by kellyjonbrazil** [comment]
These files are very similar to `rpm -qi` output. I added a small change to the `--rpm-qi` parser in the `dev` branch. You can test by copying the following file to your Plugin folder and using the `--rpm-qi` parser.

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/rpm_qi.py

- Linux/unix: $HOME/.local/share/jc/jcparsers
- macOS: $HOME/Library/Application Support/jc/jcparsers
- Windows: $LOCALAPPDATA\jc\jc\jcparsers

If that works for you then I'll probably create a new `--packages` parser that aliases to this one. Thanks!

**Comment by don-rumata** [comment]
@kellyjonbrazil , I tested it manually, and it worked.

And over script:

```bash
#!/usr/bin/env bash

# https://wikipedia.org/Packages and https://google.com/Packages - 4 test error.

PACKAGES_URLS="https://download.videolan.org/pub/debian/stable/Packages \
https://packages.mozilla.org/apt/dists/mozilla/main/binary-amd64/Packages \
https://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages \
https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/Packages \
https://download.onlyoffice.com/repo/debian/dists/squeeze/main/binary-i386/Packages \
https://apt.postgresql.org/pub/repos/apt/dists/focal-pgdg/main/binary-amd64/Packages \
https://download.opensuse.org/repositories/home:/pzz/xUbuntu_20.04/Packages \
https://dl.google.com/linux/talkplugin/deb/dists/stable/main/binary-amd64/Packages \
https://wikipedia.org/Packages \
https://google.com/Packages"

# https://github.com/kellyjonbrazil/jc/issues/480#issuecomment-1793568843
mkdir -p "$HOME/.local/share/jc/jcparsers"
curl --silent https://raw.githubusercontent.com/kellyjonbrazil/jc/dev/jc/parsers/rpm_qi.py > "$HOME/.local/share/jc/jcparsers/rpm_qi.py"

# mkdir 4 indexes
mkdir /tmp/jc-test 2>/dev/null

for i in $PACKAGES_URLS
	do
    PACKAGE_FILE_NAME=$(echo "$i" | sed 's|:|_|g ; s|/|-|g')

    curl --silent --connect-timeout 30 "$i" > /tmp/jc-test/"$PACKAGE_FILE_NAME"

    jc --rpm-qi -p < /tmp/jc-test/"$PACKAGE_FILE_NAME" | grep -q -i '"package":' || echo -e '\n \e[1;31m' /tmp/jc-test/"$PACKAGE_FILE_NAME" is not a valid yaml '\e[0m \n'
done
```

**Comment by kellyjonbrazil** [comment]
Any objection to the name `--deb-packages` for this parser? If so, any other ideas?

**Comment by don-rumata** [comment]
Maybe `--deb-packages-index`? Not so long?

**Comment by kellyjonbrazil** [comment]
Sounds good. This is now available in `dev` and will be available in the next release.

**Comment by kellyjonbrazil** [comment]
I have renamed this parser to `pkg-index-deb`.

**Comment by kellyjonbrazil** [comment]
Delivered in v1.24.0: https://github.com/kellyjonbrazil/jc/releases/tag/v1.24.0
