### ISSUE TITLE
OSS-Fuzz Integration

### ISSUE THREAD

**Issue by ennamarie19** [kellyjonbrazil/jc#481]
My name is McKenna Dallmeyer and I would like to submit jc to OSS-Fuzz. If you are not familiar with the project, OSS-Fuzz is Google's platform for continuous fuzzing of Open Source Software. In order to get the most out of this program, it would be greatly beneficial to be able to merge-in my fuzz harness and build scripts into the upstream repository and contribute bug fixes if they come up. Is this something that you would support me putting the effort into?

Thank you!

**Comment by kellyjonbrazil** [comment]
Thanks - I'll take a look at the project!

**Comment by ennamarie19** [comment]
Great! Please let me know if you'd like me to proceed.

**Comment by kellyjonbrazil** [comment]
Hi @ennamarie19 I am interested in proceeding but I'm haven't fully digested the process. Is there anything you need me to do on my side to support this?

**Comment by ennamarie19** [comment]
Hi! I would just need you to eventually merge the harness and bug fixes that I write for the project. For now, I would just need an email of someone who would like to be notified of bugs and also would like to have access to the OSS-Fuzz dashboard. I will include this in a project.yaml file that will be submitted to OSS-Fuzz for review. Once they approve of the project, I can start writing the fuzz harness for jc.

**Comment by kellyjonbrazil** [comment]
Sounds good. You can use kellyjonbrazil@gmail.com. Thanks!
