### ISSUE TITLE
Parsing "mount" fails when mount_point contains spaces

### ISSUE THREAD

**Issue by wolkenarchitekt** [kellyjonbrazil/jc#482]
I have a mount point containing spaces (an Ubuntu OS image, auto mounted by udisks):

```
$ mount | grep Ubuntu
/dev/sda1 on /media/ingo/Ubuntu 22.04.3 LTS amd64 type iso9660 (ro,nosuid,nodev,relatime,nojoliet,check=s,map=n,blocksize=2048,uid=1000,gid=1000,dmode=500,fmode=400,iocharset=utf8,uhelper=udisks2)
```

When parsing this output with jc 1.23.6:
```
import jc

jc.parse(parser_mod_name="mount", data=subprocess.check_output(["mount"], text=True))
```

The result is:
```
...
 {'filesystem': '/dev/sda1',
  'mount_point': '/media/ingo/Ubuntu',
  'type': 'LTS',
  'options': ['amd64']},
...
```

But it should be:
```
...
 {'filesystem': '/dev/sda1',
  'mount_point': '/media/ingo/Ubuntu 22.04.3 LTS amd64',
  'type': 'iso9660',
  'options': ['ro',
    'nosuid',
    'nodev',
    'relatime',
    'nojoliet',
    'check=s',
    'map=n',
    'blocksize=2048',
    'uid=1000',
    'gid=1000',
    'dmode=500',
    'fmode=400',
    'iocharset=utf8',
    'uhelper=udisks2']},
...
```

It seems that the jc parser does not consider that the mount point can contain spaces.
Instead it should parse the mount point until "type".

**Comment by wolkenarchitekt** [comment]
I created a quickfix that uses a regex:
https://github.com/kellyjonbrazil/jc/compare/master...wolkenarchitekt:jc:master
However tests are missing

**Comment by kellyjonbrazil** [comment]
Nice - looks great! I turned this into a PR and will add tests. Thanks!

**Comment by kellyjonbrazil** [comment]
fixed in `dev` branch

**Comment by kellyjonbrazil** [comment]
Delivered in v1.24.0: https://github.com/kellyjonbrazil/jc/releases/tag/v1.24.0
