### ISSUE TITLE
support iftop

### ISSUE THREAD

**Issue by georgettica** [kellyjonbrazil/jc#485]
given iftop has a `write to stdout` mode. I thought `jc` can format it as json so it can be used by other tools (for example, exporting the data to monitoring servers)

I started to fidget with it in #484 , but very basic and not even starting to cover basic code.

I hope this effort is not a hinderance in any way, if so I will close the PR until I have tested it more robustly

**Comment by kellyjonbrazil** [comment]
Thanks for the parser suggestion! Could you add some raw STDOUT `iftop` output samples here? That will make it much easier to develop the parser. No worries on the PR - I'll probably start from scratch on it unless you want to work on it more.

**Comment by don-rumata** [comment]
My `stdout`:

`root@ubuntu-2004-clean-01:~/# LC_ALL=C iftop -i enp0s3 -t -P -s 1`
```
interface: enp0s3
IP address is: 10.10.15.129
MAC address is: 08:00:27:c0:4a:4f
Listening on enp0s3
   # Host name (port/service if enabled)            last 2s   last 10s   last 40s cumulative
--------------------------------------------------------------------------------------------
   1 ubuntu-2004-clean-01:ssh                 =>       448b       448b       448b       112B
     10.10.15.72:40876                        <=       208b       208b       208b        52B
--------------------------------------------------------------------------------------------
Total send rate:                                       448b       448b       448b
Total receive rate:                                    208b       208b       208b
Total send and receive rate:                           656b       656b       656b
--------------------------------------------------------------------------------------------
Peak rate (sent/received/total):                       448b       208b       656b
Cumulative (sent/received/total):                      112B        52B       164B
============================================================================================

```

`iftop, version 1.0pre4`

**Comment by kellyjonbrazil** [comment]
Thanks - I have merged the implementation into `dev` and it will make it into the next release!

**Comment by kellyjonbrazil** [comment]
Delivered in v1.24.0: https://github.com/kellyjonbrazil/jc/releases/tag/v1.24.0
