### ISSUE TITLE
jc in Photon

### ISSUE THREAD

**Issue by oliverkurth** [kellyjonbrazil/jc#486]
Not really an issue, but you can add this to the `README.md` - `jc` is now available in Photon 5.0 and later (see https://github.com/vmware/photon/tree/5.0/SPECS/jc). Just install with:
```
tdnf install jc
```

**Comment by kellyjonbrazil** [comment]
Nice, thanks!

**Comment by kellyjonbrazil** [comment]
I've added to the new `README.md` in `dev`.
