### ISSUE TITLE
 New parser request: Alpine Linux packages index

### ISSUE THREAD

**Issue by don-rumata** [kellyjonbrazil/jc#487]
Hi! Can you add a Alpine Linux Packages parser?

https://wiki.alpinelinux.org/wiki/Apk_spec#APKINDEX_Format

Example: `curl --silent http://dl-cdn.alpinelinux.org/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz | zcat`

**Comment by kellyjonbrazil** [comment]
Sure, looks pretty easy.

**Comment by r-darwish** [comment]
So I suppose what's actually supposed to be parsed here is the APKINDEX file inside the tar itself.

@kellyjonbrazil should this parser receive the extracted file as the input, or should it extract & parse it from the tar.gz?

Also, here's a package from the file
```
C:Q1znBl9k+RKgY6gl5Eg3iz73KZbLY=
P:yasm
V:1.3.0-r4
A:x86_64
S:772109
I:1753088
T:A rewrite of NASM to allow for multiple syntax supported (NASM, TASM, GAS, etc.)
U:http://www.tortall.net/projects/yasm/
L:BSD-2-Clause
o:yasm
m:Natanael Copa <ncopa@alpinelinux.org>
t:1681228881
c:84a227baf001b6e0208e3352b294e4d7a40e93de
D:so:libc.musl-x86_64.so.1
p:cmd:vsyasm=1.3.0-r4 cmd:yasm=1.3.0-r4 cmd:ytasm=1.3.0-r4

C:Q1D3O+vigqMNGhFeVW1bT5Z9mZEf8=
P:yasm-dev
V:1.3.0-r4
A:x86_64
S:449076
I:1773568
T:A rewrite of NASM to allow for multiple syntax supported (NASM, TASM, GAS, etc.) (development files)
U:http://www.tortall.net/projects/yasm/
L:BSD-2-Clause
o:yasm
m:Natanael Copa <ncopa@alpinelinux.org>
t:1681228881
c:84a227baf001b6e0208e3352b294e4d7a40e93de
```
I understand most of the field names but not all of them. Can anyone elaborate?

**Comment by kellyjonbrazil** [comment]
This is ready to ship in the next release.

**Comment by don-rumata** [comment]
@kellyjonbrazil, the `apkindex` key is the final version? Or will it be like in https://github.com/kellyjonbrazil/jc/issues/480? I.e. `--apk-packages-index`.

**Comment by kellyjonbrazil** [comment]
I was thinking about that, too. Probably makes sense to normalize the name. That's an easy fix.

**Comment by kellyjonbrazil** [comment]
I think I'll rename both to `pkg-index-deb` and `pkg-index-alpine`. That way they show up together in help and we can support other formats using the same naming convention.

**Comment by kellyjonbrazil** [comment]
Parser name changed to `pkg-index-deb`.

**Comment by don-rumata** [comment]
@kellyjonbrazil , may be `pkg-index-apk`?

**Comment by kellyjonbrazil** [comment]
I thought using `apk` in there since I assume it stands for "Alpine Package", but I'm not sure. I guess it makes sense to use `apk` and just have Alpine in the description.

**Comment by kellyjonbrazil** [comment]
updated name to  `pkg-index-apk`

**Comment by kellyjonbrazil** [comment]
Delivered in v1.24.0: https://github.com/kellyjonbrazil/jc/releases/tag/v1.24.0
