### ISSUE TITLE
Learning / Showcase exercise

### ISSUE THREAD

**Issue by fduran** [kellyjonbrazil/jc#494]
Hello,

I'd love to showcase `jc` in [https://github.com/fduran/sadservers](SadServers), the general idea would be to have a challenge  that can be solved using regular Bash tooling but it's much easier using `jc`. An example would be this [blog post](https://blog.kellybrazil.com/2019/11/26/bringing-the-unix-philosophy-to-the-21st-century/).  

As requirements, the scenario VM must not use outside (Internet) networking (so no "dig" for ex). Debian is the preferred target OS.

As a "nice to have", a "Capture the flag" or specific short solution that can be tested via a bash script is preferred over "follow along" (guided learning) or having multiple solutions.

**Comment by kellyjonbrazil** [comment]
Hi Fernando - cool project! I'm happy to help. I'll have to think of an interesting scenario unless someone else has a good use-case. I have a few other blog posts at https://blog.kellybrazil.com/ that might offer some inspiration:

- https://blog.kellybrazil.com/2021/04/12/practical-json-at-the-command-line/
- https://blog.kellybrazil.com/2022/08/29/tutorial-rapid-script-development-with-bash-jc-and-jq/
- https://blog.kellybrazil.com/2022/07/14/convert-x-509-certificates-to-json-with-jc/
- https://blog.kellybrazil.com/2022/05/17/easily-convert-git-log-output-to-json/
- https://blog.kellybrazil.com/2022/03/26/a-new-way-to-parse-plain-text-tables/

**Comment by fduran** [comment]
I'll check out the blog articles, thanks!

> Do the scenario VMs power-on with all of the required dependencies installed or will the student need to download and install jc as part of the scenario?

I'd add `jc` (and anything else needed like files to process) to the VM image so that there's no need to install anything else.
