### ISSUE TITLE
tests failing in s390x

### ISSUE THREAD

**Issue by sudipm-mukherjee** [kellyjonbrazil/jc#500]
The package `jc` in Debian was updated to v1.23.6 and with that the tests are failing in s390x architecture with the error:
```
=================================== FAILURES ===================================
 35s __________________________ MyTests.test_proc_net_tcp6 __________________________
 35s 
 35s self = <tests.test_proc_net_tcp.MyTests testMethod=test_proc_net_tcp6>
 35s 
 35s     def test_proc_net_tcp6(self):
 35s         """
 35s         Test '/proc/net/tcp6'
 35s         """
 35s >       self.assertEqual(jc.parsers.proc_net_tcp.parse(self.f_in['proc_net_tcp6'], quiet=True),
 35s                                                        self.f_json['proc_net_tcp6'])
 35s E       AssertionError: Lists differ: [{'en[543 chars]s': '4606:126:f1:19e::4c3a:0', 'local_port': 5[2894 chars]30'}] != [{'en[543 chars]s': '2601:646:9e01:f100::3a4c', 'local_port': [2893 chars]30'}]
 35s E       
 35s E       First differing element 1:
 35s E       {'ent[23 chars]s': '4606:126:f1:19e::4c3a:0', 'local_port': 5[352 chars]000'}
 35s E       {'ent[23 chars]s': '2601:646:9e01:f100::3a4c', 'local_port': [353 chars]000'}
 35s E       
 35s E       Diff is 4818 characters long. Set self.maxDiff to None to see it.
 35s 
 35s tests/test_proc_net_tcp.py:48: AssertionError
 35s =========================== short test summary info ============================
 35s FAILED tests/test_proc_net_tcp.py::MyTests::test_proc_net_tcp6 - AssertionErr...
 35s ======================== 1 failed, 1355 passed in 6.43s ========================
```
The full test log can be seen at https://ci.debian.net/data/autopkgtest/unstable/s390x/j/jc/41094874/log.gz

**Comment by kellyjonbrazil** [comment]
Hi - thanks for reporting this. Has `jc` ever passed tests on the 390x architecture before? Doesn't look like there have been any changes to that parser since it was introduced in v1.23.4. I'll see what might be causing that.

**Comment by kellyjonbrazil** [comment]
Looks like it probably has to do with the different endian-ness of the platform and the hext-to-ip conversion function here: https://github.com/kellyjonbrazil/jc/blob/master/jc/parsers/proc_net_tcp.py#L179

Might need to reverse the bytes or something if that platform is detected.

**Comment by sudipm-mukherjee** [comment]
> Hi - thanks for reporting this. Has `jc` ever passed tests on the 390x architecture before? Doesn't look like there have been any changes to that parser since it was introduced in v1.23.4. I'll see what might be causing that.

Yes, It has always.            
https://ci.debian.net/data/autopkgtest/testing/s390x/j/jc/41077279/log.gz is the log from s390x for v1.22.5.

**Comment by kellyjonbrazil** [comment]
Ah, yes - `proc-net-tcp` wasn't there in v1.22.5 so it makes sense it passed before.  I can make a fix for this architecture but I'll need some assistance on testing as I don't have that system type to test on.

**Comment by sudipm-mukherjee** [comment]
Sure, send me a patch or link to a branch and I can test it,

**Comment by kellyjonbrazil** [comment]
Please excuse how ugly this patch is, but I decided to do simple text-level manipulation instead of bit manipulation to get around the issue. Perhaps this can be cleaned up a bit.

I'm still not sure what the output of `/proc/net/tcp6` looks like on an s390x system. That is, do the IPv6 addresses look exactly the same on x86 systems or are the bytes reversed? If they are the same, then I believe this patch will work fine. Otherwise we will just be fixing the test but not how the file should be parsed.

```
diff --git a/jc/parsers/proc_net_tcp.py b/jc/parsers/proc_net_tcp.py
index 99c3ddac..1ad7a76b 100644
--- a/jc/parsers/proc_net_tcp.py
+++ b/jc/parsers/proc_net_tcp.py
@@ -155,9 +155,9 @@ Examples:
       ...
     ]
 """
-import binascii
 import socket
 import struct
+import ipaddress
 from typing import List, Dict
 import jc.utils
 
@@ -181,10 +181,19 @@ def hex_to_ip(hexaddr: str) -> str:
         addr_long = int(hexaddr, 16)
         return socket.inet_ntop(socket.AF_INET, struct.pack("<L", addr_long))
     elif len(hexaddr) == 32:
-        addr = binascii.a2b_hex(hexaddr)
-        addr_tup = struct.unpack('>IIII', addr)
-        addr_bytes = struct.pack('@IIII', *addr_tup)
-        return socket.inet_ntop(socket.AF_INET6, addr_bytes)
+        newaddr = ''
+        for chunk in range(0, len(hexaddr), 8):
+            left_chunk = hexaddr[chunk + 4:chunk + 8]
+            left_chunk_1 = left_chunk[2:4]
+            left_chunk_2 = left_chunk[0:2]
+            right_chunk = hexaddr[chunk:chunk + 4]
+            right_chunk_1 = right_chunk[2:4]
+            right_chunk_2 = right_chunk[0:2]
+            left = left_chunk_1 + left_chunk_2
+            right = right_chunk_1 + right_chunk_2
+            newaddr = newaddr + left + right
+        full_addr = ':'.join(newaddr[i:i+4] for i in range(0, len(hexaddr), 4))
+        return ipaddress.IPv6Address(full_addr).compressed
 
     return ''

```

**Comment by sudipm-mukherjee** [comment]
Thanks, just tested on a s390x system.  This fixes the tests in it.           
And, also the output of `/proc/net/tcp6` is:
```
$ cat  /proc/net/tcp6
  sl  local_address                         remote_address                        st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode
   0: 00000000000000000000000000000000:1355 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 16050 1 00000000e7c9df10 100 0 0 10 0
   1: 00000000000000000000000000000001:0035 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 15974 1 00000000b29c42de 100 0 0 10 0
   2: 00000000000000000000000000000000:0016 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 54310797 1 00000000bc448fe1 100 0 0 10 0
   3: 00000000000000000000000000000000:0019 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 16164 1 00000000c6f3d63f 100 0 0 10 20
   4: 00000000000000000000000000000001:22F9 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 15977 1 0000000002ff1a00 100 0 0 10 0
   5: 00000000000000000000000000000000:1622 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000   110        0 56192927 1 000000000b30fb48 100 0 0 10 0
```

**Comment by kellyjonbrazil** [comment]
Thanks! Any way you could generate more tcp traffic on that s390x host (maybe with curl to a known IPv6 address)? That will give more meaningful IP addresses to compare since they are just all `::` and `::1` in this example.

**Comment by sudipm-mukherjee** [comment]
Looks like its not on IPv6 network.              
Tried doing ping but that failed.
```
$ ping6 2606:4100:3880:1255:b67a:f1ff:fe73:320
ping6: connect: Network is unreachable
```
I can try to access a different system tomorrow and test there.

**Comment by sudipm-mukherjee** [comment]
I am not getting more than 3 rows on this, and only the last 2 addresses are there. Hope this helps.

```
$ cat /proc/net/tcp6
  sl  local_address                         remote_address                        st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode
   0: 00000000000000000000000000000000:0016 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 16995 1 0000000000000000 100 0 0 10 0
   1: FEC0000000000000505400FFFE123456:C5CC 2620002D400000010000000000000027:0050 06 00000000:00000000 03:000010CE 00000000     0        0 0 3 0000000000000000
   2: FEC0000000000000505400FFFE123456:C5E6 26031030020E0003000000000000023C:0050 06 00000000:00000000 03:0000144F 00000000     0        0 0 3 0000000000000000
```

**Comment by sudipm-mukherjee** [comment]
Thanks.            
Please ping me after the patch is ready and I can try it again on the s390x machine.

**Comment by kellyjonbrazil** [comment]
You can go ahead and release with the existing patch and I'll work on a permanent fix for v1.24.1. If I implement option 3 it will change the tests, which will be a little more involved so we can do that on a normal release.

**Comment by kellyjonbrazil** [comment]
This has been fixed in the `dev` branch and will make it into the next release.

**Comment by sudipm-mukherjee** [comment]
Thanks.  I have added your previous patch in Debian as a temporary measure. WIll drop that with the next release.

**Comment by kellyjonbrazil** [comment]
Added in [v1.25.0](https://github.com/kellyjonbrazil/jc/releases/tag/v1.25.0)
