### ISSUE TITLE
Generic Split Parsers

### ISSUE THREAD

**Issue by muescha** [kellyjonbrazil/jc#504]
## Possible additional generic parsers

- `--split {delimiter}` 
- `--split-first {delimiter}`
- `--split-last {delimiter}`

```shell
echo "/Users/muescha/.docker/bin/executable.sh" | jc --split-first '/'
```
```json
"Users"
```

```shell
echo "/Users/muescha/.docker/bin/executable.sh" | jc --split-last '/'
```
```json
"executable.sh"
```

```shell
echo "/Users/muescha/.docker/bin/executable.sh" | jc --split '/'
```
```json
 {
	      "Users",
    	  "muescha",
	      ".docker",
    	  "bin",
    	  "executable",
}
```

maybe also chainable:

one split:
```shell
echo "/Users/muescha/.docker/bin:/Users/muescha/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin" \
| jc --split ':'
```
```json
[
  "/Users/muescha/.docker/bin",
  "/Users/muescha/.asdf/shims",
  "/opt/homebrew/opt/asdf/libexec/bin"
]
```

chained split all the results from first split:
```shell
echo "/Users/muescha/.docker/bin:/Users/muescha/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin" \
| jc --split ':' --split '/'
```
```json
[
  ["Users", "muescha", ".docker", "bin"],
  ["Users", "muescha", ".asdf", "shims"],
  ["opt", "homebrew", "opt", "asdf", "libexec", "bin"]
]

```

chained split-first of all the results from first split:
```shell
echo "/Users/muescha/.docker/bin:/Users/muescha/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin" \
| jc --split ':' --split-last '/'
```
```json
[
  "bin",
  "shims",
  "bin"
]
```

**Comment by kellyjonbrazil** [comment]
I think `jq` is a good tool for this sort of thing:

```
% echo $PATH | jq -R 'split(":")' 
[
  "/Users/kelly/.pyenv/shims",
  "/Users/kelly/.gem/ruby/2.6.0/bin",
  "/Users/kelly/.local/bin",
  "/Users/kelly/.cargo/bin",
  "/usr/local/bin",
  "/System/Cryptexes/App/usr/bin",
  "/usr/bin",
  "/bin",
  "/usr/sbin",
  "/sbin",
  "/Library/Apple/usr/bin",
  "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin",
  "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin",
  "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
]
```

**Comment by muescha** [comment]
thats a good idea - but now i like to have this as input for jc --url (I wrote the #506)

**Comment by muescha** [comment]
Should we incorporate these ideas into a 'How To' document? 

I'm not very familiar with all the command line commands, so having some common problems documented would be really helpful.

**Comment by kellyjonbrazil** [comment]
I have been adding things like that to the [Wiki](https://github.com/kellyjonbrazil/jc/wiki), or we could add these tips to Discussions.

**Comment by kellyjonbrazil** [comment]
Cool, I think it makes sense to some sort of `--multi-in` argument that works on single line string input, and maybe even with file paths for file parsers (e.g. `/proc/*/status`)

**Comment by muescha** [comment]
thats make sense. to implement splitting as a generic preprocessor makes no sense, because there are many other tools around here.



I can only imaging that we can have with this generic processors here we could define an easy alias for `--env-path` like: `--split ":" --multi-in --url`

```shell
echo "/Users/muescha/.docker/bin:/Users/muescha/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin" \
| jc --env-path
```
would be replaced with

```shell
echo "/Users/muescha/.docker/bin:/Users/muescha/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin" \
| jc --split ":" --multi-in --url
```

where at first the `--split` starts as preprocessor, then the `--multi-in` acts as a preprocessor for the `--url` parser.

**Comment by kellyjonbrazil** [comment]
Closing this as the multi-line functionality has been implemented via the `--slurp` option.

https://github.com/kellyjonbrazil/jc/issues/506

**Comment by muescha** [comment]
👍

**Comment by muescha** [comment]
it is ok to close this

# Summary

the split functionality can be done with many command line tools (`awk`,`sed`) or:

- `tr`
```shell
echo "1:2:3:4:5" | tr ":" "\n"
1
2
3
4
5
```

- `jq`
```shell
echo "1:2:3:4:5" | jq -R 'split(":")'
[
  "1",
  "2",
  "3",
  "4",
  "5"
]
```

- or when creating an alias, using the python [`split`](https://docs.python.org/3.3/library/stdtypes.html?highlight=split#str.split) command

> `str.split(sep=None, maxsplit=-1)`
Return a list of the words in the string, using sep as the delimiter string. If maxsplit is given, at most maxsplit splits are done (thus, the list will have at most maxsplit+1 elements). If maxsplit is not specified or -1, then there is no limit on the number of splits (all possible splits are made).

**Comment by kellyjonbrazil** [comment]
You can also do the following in `jq`:
```
% echo "1:2:3:4:5" | jq -rR 'split(":") | .[]'
1
2
3
4
5
```
