### ISSUE TITLE
Alias

### ISSUE THREAD

**Issue by muescha** [kellyjonbrazil/jc#508]
as mentioned in 

in some cases new parsers can be done with the generic parsers and some output strip down:

for example:

- `tmutil status | jc 1: --plist -p`
- `tmutil destinationinfo | jc 2: --kv -p`

aliases:
```json
{
	"tmutil-status": "1: --plist",
	"tmutil-destinationinfo": "2: --kv",
	"kv-dup": "--ini-dup"
}
```

but with this short json we don't get the documentation generated :(

maybe create an stub parser file with just an `alias=true` and alias_command="--ini-dup" at the info block?

**Comment by muescha** [comment]
related:
- #331 
- #341

**Comment by kellyjonbrazil** [comment]
This is an interesting idea, though it seems like a normal Bash alias might work just as well. Something like:

```
alias jc-tmutil-status="jc 1: --plist"
```

Then use:

```
% tmutil status | jc-tmutil-status
{"ClientID":"com.apple.backupd","Percent":"-1","Running":"0"}
```

**Comment by muescha** [comment]
yes, but then there is no documentation. 

but: new users can not find this useful aliases with the `jc -hh` or `jc -hhh` help pages.

**Comment by kellyjonbrazil** [comment]
Here is how we currently do aliases in `jc`:

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/kv.py

Most of it is just the doc string, but importing the aliased parser,  an `info` class, and a `parse` function are the only things really required.

This is what the `parse` function looks like:

```
def parse(data, raw=False, quiet=False):
    """
    Main text parsing function

    Parameters:

        data:        (string)  text data to parse
        raw:         (boolean) unprocessed output if True
        quiet:       (boolean) suppress warning messages if True

    Returns:

        Dictionary representing a Key/Value pair document.
    """
    # This parser is an alias of ini.py
    ini.info = info  # type: ignore
    return ini.parse(data, raw, quiet)
```

Just two functional lines of code. Maybe we just document how to create aliases or have a template?

**Comment by kellyjonbrazil** [comment]
For example, `tmutil-destinationinfo` would have this in the `parse` function:

```
# This parser is an alias of ini.py
ini.info = info  # type: ignore
return ini.parse(data[2:], raw, quiet)
```

**Comment by muescha** [comment]
I like your solution, and there's no necessity to alter the toolchain or core functionality—keeping it simple (KISS).

If I want to include additional information, I can introduce new values without reusing existing ones. 

Additionally, a documentation section detailing how to create aliases or custom parsers based on the existing ones would be valuable.

**Comment by muescha** [comment]
As an optional enhancement for the `info` section, we could consider adding an extra tag labeled `['alias']`, along with fields such as `"alias_for": "2: --kv"` and `"based_on": ["kv"]`. However, I'm uncertain if this warrants a separate section.

Is the line ini.info = info necessary?

**Comment by muescha** [comment]
This is also interesting if there a 2 or more sections with different encodings like:

```text
Text blabla ---
ab: de
de: ef
Text blabla ---
{
	f = "x"
	x = "y"
}
```

**Comment by kellyjonbrazil** [comment]
Oops, looks like my alias example was too simple. We would need to slice by lines and my example would have only sliced by characters. It would be more like:
```
datalines = data.splitlines()
data = '\n'.join(datalines[2:])
return ini.parse(data, raw, quiet)
```

**Comment by kellyjonbrazil** [comment]
> Is the line ini.info = info necessary?

It’s really just there in case there are any compatibility differences since all of the parsers do a compatibility test. Wouldn’t really break anything to leave it out but ensures the parser acts as you define it in the `info` class.

**Comment by muescha** [comment]
Could the [slicer](https://github.com/kellyjonbrazil/jc/blob/dcc4d35d554712f0be3edd7c956071a759ce7915/jc/cli.py#L656-L695)  function be extracted or refactored for reusability? This would allow users to utilize the code similarly to the example provided, and perhaps enable its functionality with streams as well.

```python
import jc.parsers.ini as ini
import jc.slicer as slicer
...
return ini.parse(slicer(data,"2:"), raw, quiet)
```

**Comment by kellyjonbrazil** [comment]
I'll look into moving the slicer function into `utils.py`

**Comment by kellyjonbrazil** [comment]
I added the `line_slice()` function in `utils.py` in the dev branch.

**Comment by muescha** [comment]
maybe there should be a section at the docs where is described some examples of "alias" parsers - parsers that are combinations of other parsers. with example of with the slice command.  


```markdown
# Alias - Or how to create a parser based on existing parsers
```

**Comment by kellyjonbrazil** [comment]
Added in [v1.25.0](https://github.com/kellyjonbrazil/jc/releases/tag/v1.25.0)
