### ISSUE TITLE
Incorrect parsing of numbers using comma as decimal seperator

### ISSUE THREAD

**Issue by linnnus** [kellyjonbrazil/jc#521]
# My issue

I was gathering some latency data using the following command.

```shell
$ ping -c 5 google.com | jc --ping | jq '.responses.[].time_ms'
50218.0
41182.0
53265.0
48576.0
28508.0
```

The result was rather surprising; apparently each round-trip was taking upwards of 50 seconds! For reference, this is the output of just running the `ping command`:

```shell
$ ping -c 5 google.com
PING google.com (172.217.23.206): 56 data bytes
64 bytes from 172.217.23.206: icmp_seq=0 ttl=119 time=30,406 ms
64 bytes from 172.217.23.206: icmp_seq=1 ttl=119 time=29,177 ms
64 bytes from 172.217.23.206: icmp_seq=2 ttl=119 time=31,549 ms
64 bytes from 172.217.23.206: icmp_seq=3 ttl=119 time=31,647 ms
64 bytes from 172.217.23.206: icmp_seq=4 ttl=119 time=30,226 ms
--- google.com ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max/stddev = 29,177/30,601/31,647/0,916 ms
```

The durations (e.g. `31,929`) correctly use comma as the decimal separator in accordance with my locale. To confirm this hunch, I tried running the below command which (I believe) makes sure `ping` acts with the default locale. Running `ping` in this bare environment results in the following output:

```shell
$ LC_NUMERIC=C ping -c 5 google.com
PING google.com (172.217.23.206): 56 data bytes
64 bytes from 172.217.23.206: icmp_seq=0 ttl=119 time=55.455 ms
64 bytes from 172.217.23.206: icmp_seq=1 ttl=119 time=59.710 ms
64 bytes from 172.217.23.206: icmp_seq=2 ttl=119 time=61.732 ms
64 bytes from 172.217.23.206: icmp_seq=3 ttl=119 time=88.535 ms
64 bytes from 172.217.23.206: icmp_seq=4 ttl=119 time=60.186 ms
--- google.com ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max/stddev = 55.455/65.124/88.535/11.889 ms
```

Note how the durations (e.g. `88.535`) now use a full stop as the separator.
Running this output through the entire pipeline gives the expected result, i.e. the numbers of a more appropriate scale.

```shell
$ LC_NUMERIC=C ping -c 10 google.com | jc --ping | jq '.responses.[].time_ms'
32.049
55.479
35.032
37.542
86.248
```

The result here is much more sensible! It appears **`jc` is parsing the numbers using `,` as the decimal separator incorrectly**.

# Expected result

I expect `jc` to correctly convert numbers, regardless of locale.

In this case, my locale was
```shell
$ locale
LANG="da_DK.UTF-8"
LC_COLLATE="da_DK.UTF-8"
LC_CTYPE="da_DK.UTF-8"
LC_MESSAGES="da_DK.UTF-8"
LC_MONETARY="da_DK.UTF-8"
LC_NUMERIC="da_DK.UTF-8"
LC_TIME="da_DK.UTF-8"
LC_ALL=
```
and `ping` thus correctly used `,` as the decimal separator, and `jc` should also parse numbers like this.

# Potential solution

It appears the number parsing for the `ping` parser happens in [`_process`][process] which calls into [`convert_to_float`][convert_to_float]. `convert_to_float` should be updated to parser correctly parse numbers based on locale.

# Possible issues with solution

First of all `jq` may not be called with the same environment as `ping`. This is actually the case in my "correct" example above; the environment variable `LC_NUMERIC` is overwritten in the invocation of `ping` but for `jc`.

I'm not sure all programs are as dilligent as `ping` in using the correct decimal separator. Some programs may still use `,` for the thousands separator when the locale specifies that `,` is used as the decimal separator. Taking this into account must be done on a per-parser basis.

[convert_to_float]: https://github.com/kellyjonbrazil/jc/blob/dcc4d35d554712f0be3edd7c956071a759ce7915/jc/utils.py#L215
[process]: https://github.com/kellyjonbrazil/jc/blob/dcc4d35d554712f0be3edd7c956071a759ce7915/jc/utils.py#L215

**Comment by muescha** [comment]
Just note - on my macOS this is the default locale (I don't remember that I changed it):
```shell
locale
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by kellyjonbrazil** [comment]
Yes, this is an issue when parsing text output. If commands would support JSON output then we wouldn't be in this mess. 😄 

I'm not sure about addressing this issue other than the documented [Caveat](https://github.com/kellyjonbrazil/jc#locale).

As you mentioned, it is not necessarily easy to assume `,` will be a decimal separator. Using `export LC_ALL=C` is the best way to get around the issue. Also, `jc` cannot go by the local locale information, either, since `jc` may be processing text from another machine on another locale. That is why locale and timezone issues have been 'punted' on by only supporting the `C` locale and the `UTC` timezone for timezone-aware values.

**Comment by linnnus** [comment]
Oh, my bad! I totally missed that section of the documentation. Glad to see it's already been considered.

I can't really figure out a good strategy for warning users in the most common cases. I have left my musings below but they didn't really amount to much. Closing this issue.

> I wonder if it would be possible to introduce some sort of warning instead? Perhaps `jc` could print a warning if it is invoked in a locale that isn't `LC_ALL=C`. This approach would generate warnings for general command-line use like
> 
> ```
> ping -c 10 google.com | jc --ping
> ```
> 
> Though on the other hand it would generate a false positive in more advanced use-cases like this:
> 
> ```
> $ LC_ALL=C ping -c 10 google.com >ping.txt
> $ jc --ping <ping.txt
> ```
> 
> which might be more common in scripting situations. Event the super duper correct case of
> 
> ```
> $ LC_ALL=C ping -c 10 google.com | jc --ping
> ```
> 
> would generate  a false positive. A flag like `--no-warn-locale` could be introduce, but it feels like it would need to be used pretty much all the time.
