### ISSUE TITLE
Idea: Generic Dict Data Mapper

### ISSUE THREAD

**Issue by muescha** [kellyjonbrazil/jc#530]
I see on many places that dictionary needs some conversions. 

1) convert_to_int / convert_to_bool

```python
 for key in proc_data: 
     if key in int_list: 
         proc_data[key] = jc.utils.convert_to_int(proc_data[key]) 
```

2) int/float

https://github.com/kellyjonbrazil/jc/blob/140a61702b903918683b4fd0c2861638266e0805/jc/parsers/sysctl.py#L84-L91

3) utils.timestamp

```python
 datetime_list = {'filesystem_created', 'last_mount_time', 'last_write_time', 'last_checked'} 
  
 for key in proc_data.copy(): 
     if key in datetime_list: 
         dt = jc.utils.timestamp(proc_data[key], (1000,)) 
         proc_data[key + '_epoch'] = dt.naive 
         proc_data[key + '_epoch_utc'] = dt.utc 
```

4) bytes

https://github.com/kellyjonbrazil/jc/blob/140a61702b903918683b4fd0c2861638266e0805/jc/parsers/iptables.py#L197-L219

5) remove quotation:

https://github.com/kellyjonbrazil/jc/blob/140a61702b903918683b4fd0c2861638266e0805/jc/parsers/ini.py#L90-L98
https://github.com/kellyjonbrazil/jc/blob/140a61702b903918683b4fd0c2861638266e0805/jc/parsers/ini.py#L115-L122

6) Renaming keys / modifiying: lowercase the keys, replace `-` with `_`

https://github.com/kellyjonbrazil/jc/blob/140a61702b903918683b4fd0c2861638266e0805/jc/parsers/asciitable.py#L151-L155

change the names `status_code` to `Status-Code`

so there comes in my mind to have some standard converters and mappers ... 

Setup can be done with:

```python
mapper_config = {
	# the remove_ instead as options better as value mapper functions to '*'
    'remove_quotas': true, 
    'remove_single_quotas': true,
    'remove_double_quotas': true,

    'value_mapper': {
        '*': clean_quotes,  # every value
		'hidden': jc.utils.convert_to_bool,
		'size': jc.utils.convert_byte_to_int,
		'counter': jc.utils.convert_to_int,
		'temperature': jc.utils.convert_to_float_int,
    },
    'key_mapper': {
        '*': [ 
            jc.utils.convert_to_lower_case, 
            jc.utils.convert_to_snake_case 
        ],
        'version' : 'HTTP-Version',
        'status_code': 'Status-Code',
        'status_reason': 'Status-Reason'
    },
    'item_mapper': {
        # named groups are applied as: 
        # raw_output.update(match.groupdict())
		'*:first_match': re.compile(r'^HTTP/(?P<version>\d+(\.\d+)?) (?P<status_code>\d+)(?: (?P<status_reason>.+))?$'),

		'filesystem_created': jc.utils.add_timestamps,
		'last_mount_time': jc.utils.add_timestamps,
		'/^.?_time$/': jc.utils.timestamp,  # key check with regex
	},
    'remove_keys': [
        'status_name'
    ],
}

utils.data_mapper(raw_output, mapper_config)
```

`key_mapper`: calls the function for matching keys with `f(key)`
`value_mapper`: calls the function for matching keys with `f(value)`
`item_mapper`: calls the function for matching keys with `f(key, value)`

there are 3 mappers so that `jc.utils.*` functions can called direct with `key` or `value` and at `item_mapper` the special functions with the signature `f(key,value)`

This is just a concept under consideration. However, I'm concerned that ultimately it might become overly complex and contradict the principle of KISS (Keep It Simple, Stupid).

**Comment by kellyjonbrazil** [comment]
`#4` (bytes) I can probably remove that code and use `utils.convert_size_to_int()` now.

`#5` (remove quotes) can probably be added to `utils` as a function.

`#6` (normalize keys) can probably be added to `utils` as a function.

The dict mapper idea is not a bad one, but probably not at the top of my priority list at the moment.

**Comment by muescha** [comment]
I have made some initial attempts as a personal exploration:

I currently have a draft version, but I am not entirely satisfied with it :(

You can find the code here:
- Implementation: [dict_mapper.py](https://github.com/muescha/dict_mapper/blob/main/dict_mapper/dict_mapper.py)
- Test cases: [test_dict_mapper.py](https://github.com/muescha/dict_mapper/blob/main/tests/test_dict_mapper.py)

The issue I am facing is that I initially examine `item_mappings` and then move on to `key_mappings`. However, the resulting changes are not as predictable for the end user.

I believe implementing changes in a pipeline would be more effective, allowing users to define the order themselves:

```python
mapper_options = Pipeline([
	# find matches and add results to the dict
	UpdateMapper({'http-update': matcher}),

	KeyMapper({
		'version' : 'HTTP-Version',
		'status_code': 'Status-Code',
		'status_reason': 'Status-Reason'
    }),
	KeyMapper('replace_this_key', 'replaced_key'),
	KeyMapper({'.+_change$': lambda x: x.lower()}),

	ValueMapper({'*': lambda x: x.upper()})
])
```
- KeyMapper = update a key `key = change(key)`
- ValueMapper = update the value `value = change(value)`
- UpdateMapper = add key:values to the data `dict = change(key, value)`
- ItemMapper = change the value, the function signature is `value = change(key,value)`

**Comment by muescha** [comment]
> ... can probably be added to `utils` as a function.

yes the idea was to map helper functions (maybe all placed in `utils.converter`) to some dict values identified by keys.

> The dict mapper idea is not a bad one, but probably not at the top of my priority list at the moment.

yes - you are right - the mapper would be out of scope of jc 

While I think more about it: it is better to have it KISS than a bunch of additional code to just replace one-liners

I will close this issue, maybe reopen it when I have better and leaner implementation available
