### ISSUE TITLE
busybox 'uptime' makes showing number of logged in users optional

### ISSUE THREAD

**Issue by BubuOT** [kellyjonbrazil/jc#538]
Sorry to bother you with all these niche issues :sweat_smile: 

busybox uptime implementation makes showing the number of users optional at compile time: https://git.busybox.net/busybox/tree/procps/uptime.c#n22

An  example then might look like this: ` 00:03:32 up 3 min,  load average: 0.00, 0.00, 0.00`, there's another example in the source file linked above.

Note: this isn't something I need to have working, it's just something I ran into while trying to write a test case for the jc package in buildroot.

**Comment by kellyjonbrazil** [comment]
No trouble at all - thanks for reporting this and helping make `jc` better! I'll take a look.

**Comment by BubuOT** [comment]
I forgot to report the actual problem this leads to. The the uptime in the cmd output gets parsed into jc's number of users variable and the actual uptime variable stays at 0.

**Comment by kellyjonbrazil** [comment]
I have a fix for this in `dev`.

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/uptime.py

**Comment by kellyjonbrazil** [comment]
fix in [v1.25.1](https://github.com/kellyjonbrazil/jc/releases/tag/v1.25.1)
