### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by nitrocode** [kellyjonbrazil/jc#54]
Great tool!

It would be easier to install if we could do something like

```
brew install jc
```

**Comment by kellyjonbrazil** [comment]
I'll have to look at this again. Last time I checked there were some complications to installing a python app with all of its dependencies via brew. If it is installed this way then can only be used as a cli utility and not a python library, which is probably fine for over 90% of the use cases.

**Comment by kellyjonbrazil** [comment]
I got an executable package of `jc` working with pyoxidizer, so I may be able to create brew, rpm, and deb packages after all.  Need some more time to work on this but so far looks promising.

**Comment by kellyjonbrazil** [comment]
I have the linux binary and packages up (see readme). Still working on macOS.

**Comment by kellyjonbrazil** [comment]
I have a macOS binary available (see readme). Unfortunately I haven't been able to compile for an OS below Mojave version, so it's probably only compatible on Mojave or higher. I can eventually get this binary into brew.

**Comment by kellyjonbrazil** [comment]
The brew formula has been accepted and should be available soon!

**Comment by nitrocode** [comment]
Great! Looks like it was merged earlier today.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/jc.rb

I installed it locally using brew. Can we add this to the `README.md` too ?

```
$ brew install jc
==> Downloading https://homebrew.bintray.com/bottles/jc-1.10.6.catalina.bottle.tar.gz
##O=#  #
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "jc"
Download failed: https://homebrew.bintray.com/bottles/jc-1.10.6.catalina.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://files.pythonhosted.org/packages/17/7f/5820ca206b8ce79142c5385ff5a4262757a0f568d96beee45945dfbd83db/jc-1.10.6.
######################################################################## 100.0%
...
🍺  /usr/local/Cellar/jc/1.10.6: 2,296 files, 34.3MB, built in 56 seconds

$ ls -l /usr/bin | jc --ls | jq '.[0]'
{
...
}
```

**Comment by kellyjonbrazil** [comment]
Ah i didn't know it was available yet. I see that they are still working on that catalina bottle 404. I was planning to update the readme once they got that fixed on their side.

**Comment by kellyjonbrazil** [comment]
Sweet, looks like they figured it out. Closing this one out!
