### ISSUE TITLE
iwconfig parser don't work

### ISSUE THREAD

**Issue by viktory683** [kellyjonbrazil/jc#541]
iwconifg parser don't return anything
❌ `iwconifg | jc --iwconifg`
❌ `jc iwconifg`

![image](https://github.com/kellyjonbrazil/jc/assets/35001580/09061a91-570d-4ab4-bd93-67ab4d3dca86)
![image](https://github.com/kellyjonbrazil/jc/assets/35001580/6ab701cd-54bf-45c9-a2ad-15494e8a5c1a)

but
![image](https://github.com/kellyjonbrazil/jc/assets/35001580/fdec29bc-2220-4d12-9622-48237378cd55)

**Comment by viktory683** [comment]
distro: Arch

iwconfig installed with `wireless_tools`
```
Name            : wireless_tools
Version         : 30.pre9-3
Description     : Tools allowing to manipulate the Wireless Extensions
Architecture    : x86_64
URL             : https://hewlettpackard.github.io/wireless-tools/Tools.html
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : None
Optional Deps   : None
Required By     : conky
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 352.27 KiB
Packager        : Evangelos Foutras <evangelos@foutrelis.com>
Build Date      : Wed 13 Nov 2019 10:13:01 PM +06
Install Date    : Mon 13 Mar 2023 09:57:11 AM +06
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```
![image](https://github.com/kellyjonbrazil/jc/assets/35001580/0da958a9-d6b5-4d01-8df9-7e0420e99582)

**Comment by kellyjonbrazil** [comment]
Hi - thanks for reporting this. Could you copy/paste the `iwconfig` output in a code block here? Something like this:

```
$ iwconfig > iwconfig.out
$ cat iwconfig
...
```

**Comment by viktory683** [comment]
sure
![image](https://github.com/kellyjonbrazil/jc/assets/35001580/cdef60bf-acfb-40e0-bf68-7d0761ddf131)

**Comment by lubomir-brindza** [comment]
It's likely the parser trips up due to the ESSID string containing the caret (`^`) character:
```
$ cat orig.txt
wlp0s20f3  IEEE 802.11  ESSID:"Sacharidy"  
          Mode:Managed  Frequency:5.22 GHz  Access Point: E6:63:DA:A8:E4:91   
          Bit Rate=270 Mb/s   Tx-Power=22 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          Link Quality=38/70  Signal level=-72 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:4143   Missed beacon:0

$ cat orig.txt | jc --iwconfig
[{"name":"wlp0s20f3","protocol":"IEEE 802.11","essid":"Sacharidy","mode":"Managed","frequency":5.22,"frequency_unit":"GHz","access_point":"E6:63:DA:A8:E4:91","bit_rate":270.0,"bit_rate_unit":"Mb/s","tx_power":22,"tx_power_unit":"dBm","retry_short_limit":7,"rts_threshold":false,"fragment_threshold":false,"power_management":true,"link_quality":"38/70","signal_level":-72,"signal_level_unit":"dBm","rx_invalid_nwid":0,"rx_invalid_crypt":0,"rx_invalid_frag":0,"tx_excessive_retries":0,"invalid_misc":4143,"missed_beacon":0}]

$ cat broken.txt
wlp0s20f3  IEEE 802.11  ESSID:"^_^"  
          Mode:Managed  Frequency:5.22 GHz  Access Point: E6:63:DA:A8:E4:91   
          Bit Rate=270 Mb/s   Tx-Power=22 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          Link Quality=38/70  Signal level=-72 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:4143   Missed beacon:0

$ cat broken.txt | jc --iwconfig
[]
```

**Comment by viktory683** [comment]
thank, it work
sry for bothering
I'll wait for `1.25.x` build for Arch

**Comment by kellyjonbrazil** [comment]
This is fixed in the `dev` branch: https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/iwconfig.py

You can test by copying the file above to your `jc` parser plugin directory:

- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

**Comment by viktory683** [comment]
thanks
I don't know much regex but I think it should work fine
Waiting for merge dev to master and bulding package for Arch

**Comment by kellyjonbrazil** [comment]
Sounds good - reopening this issue and I'll close when the next version is released.

**Comment by kellyjonbrazil** [comment]
Added in [v1.25.2](https://github.com/kellyjonbrazil/jc/releases/tag/v1.25.2)
