### ISSUE TITLE
/proc/pid/state parser add missing state 'I'

### ISSUE THREAD

**Issue by rishid** [kellyjonbrazil/jc#543]
The proc pid stat parser does not support a state value of `I` representing Idle.

Reference: https://man7.org/linux/man-pages/man5/proc.5.html   (search for `/proc/pid/stat`)

**Comment by kellyjonbrazil** [comment]
I added support for `I` ("Idle") in the `dev` branch: https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/proc_devices.py

In the next release you should be able to test `/proc` file parser fixes by copying the file to the parser plugin directory, but in this version and earlier you would need to replace the file in situ or just clone the `dev` branch.

**Comment by kellyjonbrazil** [comment]
Added in [v1.25.2](https://github.com/kellyjonbrazil/jc/releases/tag/v1.25.2)
