### ISSUE TITLE
jc --rsync, it should be able to parse the summary of rsync, but doesn't work

### ISSUE THREAD

**Issue by deepwather** [kellyjonbrazil/jc#545]
I'm facing a strange issue.
According to the documentation on: https://kellyjonbrazil.github.io/jc/docs/parsers/rsync.html  jc --rsync, it should be able to parse the summary section of the rsync output, which includes statistics like bytes sent, received, and speedup.
But when I try that, there is no output. As well not, if files are copied, there I only see the new or changed files but not the stats or even that files which failed to copy:

```
[root@rlbu01 ~]# cat /var/log/last-backup.rsync_1
sending incremental file list

sent 8.71M bytes  received 29.88K bytes  10.99K bytes/sec
total size is 221.79G  speedup is 25,388.23
[root@rlbu01 ~]#
[root@rlbu01 ~]# cat /var/log/last-backup.rsync_1 | /usr/local/bin/jc --rsync
[]
```

My Rsync is: version 3.1.3  and protocol version 31
The same happens with --rsync-s

The full rsync command was: `rsync -avh --progress --no-perms --no-owner --no-group --delete --delete-excluded --times --exclude '*@SynoResource' --exclude '@eaDir' --exclude '*.vsmeta' --exclude '.DS_Store' $backup_source_folder/  $backup_destination/`

**Comment by kellyjonbrazil** [comment]
Hi, thanks for reporting this! Maybe I missed it, but was the  `-i` or `--itemize-changes` option used in `rsync`? One of those are required, but we may be able to enhance the parsers to support your output.

**Comment by kellyjonbrazil** [comment]
I have a simple summary parsing working on my local machine. Still working on tests, but here is what the output looks like:
```
% echo 'sending incremental file list

sent 8.71M bytes  received 29.88K bytes  10.99K bytes/sec
total size is 221.79G  speedup is 25,388.23' | jc --rsync -p
[
  {
    "summary": {
      "sent": 8710000,
      "received": 29880,
      "bytes_sec": 10990.0,
      "total_size": 221790000000,
      "speedup": 25388.23
    },
    "files": []
  }
]
```
This will make the next release.

**Comment by kellyjonbrazil** [comment]
And here is the `rsync-s` streaming parser output. This is now available in the `dev` branch.
```
% echo 'sending incremental file list

sent 8.71M bytes  received 29.88K bytes  10.99K bytes/sec
total size is 221.79G  speedup is 25,388.23' | jc --rsync-s -p
{
  "type": "summary",
  "sent": 8710000,
  "received": 29880,
  "bytes_sec": 10990.0,
  "total_size": 221790000000,
  "speedup": 25388.23
}
```

**Comment by deepwather** [comment]
This sounds great, I will test it as soon as the release is out. I also tried it with the switch `--itemize-changes`, this works, but my log file is then about `519Mb` big. Without `--itemize-changes` the rsync log is only about `43Mb` big. I haven't tested `--log-file` yet, maybe this would be a good option for a smaller file size too.

**Comment by kellyjonbrazil** [comment]
Added in [v1.25.2](https://github.com/kellyjonbrazil/jc/releases/tag/v1.25.2)
