### ISSUE TITLE
colored output

### ISSUE THREAD

**Issue by amanjitsk** [kellyjonbrazil/jc#55]
Hi, 
I was wondering if there is any plan to add support for color customization/themes ? The default colors can be pretty unreadable on a dark background. For ex. the keys in blue
![image](https://user-images.githubusercontent.com/12499495/78958408-fb2e3480-7ab5-11ea-88e5-30f6e9d13d6c.png)
Thanks,
Amanjit

**Comment by kellyjonbrazil** [comment]
There is a black and white theme with -m. :)

**Comment by kellyjonbrazil** [comment]
I'm using a similar color scheme to `jq` and I'm using simple ANSI colors for consistency and compatibility.  It looks like `jq` can accept color code bindings from an environment variable:
https://stackoverflow.com/questions/51338701/how-do-i-customize-the-colors-used-by-jq-c

I could probably do something similar to that so you could bind your own custom colors to each token [key names, (true, false, null), (int, float), string, array_id, array_brackets]. Something like:
```
JELLO_COLORS=1,34:0,90:0,35:0,32:0,31:0,35
```

**Comment by amanjitsk** [comment]
Oh ye that would be nice !

**Comment by kellyjonbrazil** [comment]
@amanjitsk I have added support for the `JC_COLORS` environment variable in v1.10.4, available via `pip3 install --upgrade jc`.

You can specify custom colors via the `JC_COLORS` environment variable. The `JC_COLORS` environment variable takes four comma separated string values in the following format:
```
JC_COLORS=<keyname_color>,<keyword_color>,<number_color>,<string_color>
```
Where colors are: black, red, green, yellow, blue, magenta, cyan, gray, brightblack, brightred, brightgreen, brightyellow, brightblue, brightmagenta, brightcyan, white, or default

For example, to set to the default colors:
```
JC_COLORS=blue,brightblack,magenta,green
```
or
```
JC_COLORS=default,default,default,default
```
Let me know if that works for you!

**Comment by amanjitsk** [comment]
Wow thanks for the quick change! This works perfect
![image](https://user-images.githubusercontent.com/12499495/79079752-ef718680-7cde-11ea-9165-8d3a290cf96f.png)
Looks much better now that it uses the terminal colors
