### ISSUE TITLE
jc ls --time-style=+"%F %T" -al -> wrong output

### ISSUE THREAD

**Issue by martin-christen** [kellyjonbrazil/jc#579]
if you run jc ls with a time-style the output is wrong
  filename is empty
  date contains the date and the filename

[
	{
		"filename": "",
		"flags": "-rw-r--r--.",
		"links": 1,
		"owner": "xcarrier",
		"group": "oinstall",
		"size": 423,
		"date": "2024-07-08 01:37:13 crontab.txt",
		"epoch": null,
		"epoch_utc": null
	}
]

**Comment by kellyjonbrazil** [comment]
Hi there - thanks for your interest in `jc`! only the `full-iso` `time-style` option for `ls` is supported by the parser.

> Options supported:
> - `lbaR1`
> - `--time-style=full-iso`

https://github.com/kellyjonbrazil/jc/blob/master/docs/parsers/ls.md
