### ISSUE TITLE
tests is installing in global site-packages

### ISSUE THREAD

**Issue by kellyjonbrazil** [kellyjonbrazil/jc#58]
Unit tests are being installed as `tests` in the global site-packages which can conflict with another tool called `tests`. Need to either exclude the `test` package altogether or move tests under the `jc` package directory.

**Comment by kellyjonbrazil** [comment]
@atemu I would it be ok to exclude tests?

**Comment by Atemu** [comment]
If it's inconvenient for you to keep them in, sure.

Thanks for the heads up!

**Comment by kellyjonbrazil** [comment]
Thanks for your understanding, @Atemu!

**Comment by kellyjonbrazil** [comment]
removed tests from packages in 1.10.8
