### ISSUE TITLE
Incorrect handling of "k" "K" and similar suffixes for df, should be binary

### ISSUE THREAD

**Issue by cdleonard** [kellyjonbrazil/jc#592]
Running `df -Bk` or `df -BK` is equivalent to `df -BKiB` but jc handles this as equivalent to `df -BKB`.

Coreutils handling of k/K as identical to KiB is documented here: https://www.gnu.org/software/coreutils/manual/html_node/Block-size.html, not sure how other systems handle this.

As a workaround it is possible to run `df -BKB` or `df -BKiB` explicitly

**Comment by kellyjonbrazil** [comment]
This is fixed in `dev` and will make it in the next release.

**Comment by kellyjonbrazil** [comment]
Now available in release v1.25.4
