### ISSUE TITLE
Add ruff as a code formatter and setup pre-commit for GitHub Actions Workflow

### ISSUE THREAD

**Issue by Luigi31415** [kellyjonbrazil/jc#603]
## Summary
This issue suggests setting up Ruff as a code formatter and linter in this repository and configuring it to run as part of a GitHub Actions workflow. Additionally, it proposes setting up pre-commit to manage the ruff formatting checks on every commit, ensuring consistent code style across the project.
## Why?
- Code Consistency: Running ruff as a formatter in a pre-commit workflow will ensure that code changes meet the required formatting standards before they are committed.
- Automated Workflow: Adding pre-commit and configuring it in GitHub Actions will allow automated checks on every PR, reducing the manual overhead of code reviews for formatting issues.

**Comment by kellyjonbrazil** [comment]
I appreciate the idea, but I have some wacky formatting that I just can't bear to part with. 😄
