### ISSUE TITLE
JC doesnt include output table from iptables

### ISSUE THREAD

**Issue by swetoast** [kellyjonbrazil/jc#69]
JC doesnt include output table from iptables

it creates a JSON with INPUT and FORWARD no OUTPUT even though there are rules under OUTPUT

ive tried all variants of commands from JC to try and populate OUTPUT rules but it doesnt work

**Comment by kellyjonbrazil** [comment]
Hi, thanks for opening this issue! Could you attach the iptables output that is not working to this issue? Go ahead and sanitize, if needed (but try not to modify the format). I should be able to add the OUTPUT rules to the parser.

**Comment by swetoast** [comment]
So here are my rules
```
iptables  -A OUTPUT -o eth0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables  -A OUTPUT -o eth0 -m conntrack --ctstate INVALID -j DROP
iptables  -A OUTPUT -o lo -j ACCEPT
```
typing the command `iptables -L -n -v | jc -p --iptables`

returns INPUT and FORWARD but not OUTPUT 

here is the output the command returns
```json
[
  {
    "chain": "INPUT",
    "rules": [
      {
        "pkts": null,
        "bytes": 2382000000,
        "target": "all",
        "prot": "--",
        "opt": "*",
        "in": "*",
        "out": "0.0.0.0/0",
        "source": "0.0.0.0/0"
      },
      {
        "pkts": 0,
        "bytes": 0,
        "target": "ACCEPT",
        "prot": "all",
        "opt": null,
        "in": "lo",
        "out": "*",
        "source": "0.0.0.0/0",
        "destination": "0.0.0.0/0"
      }
    ]
  },
  {
    "chain": "FORWARD",
    "rules": [
      {
        "pkts": 0,
        "bytes": 0,
        "target": "all",
        "prot": "--",
        "opt": "*",
        "in": "*",
        "out": "0.0.0.0/0",
        "source": "0.0.0.0/0"
      },
      {
        "pkts": 0,
        "bytes": 0,
        "target": "DROP",
        "prot": "all",
        "opt": null,
        "in": "*",
        "out": "*",
        "source": "0.0.0.0/0",
        "destination": "0.0.0.0/0",
        "options": "state INVALID"
      }
    ]
  }
]
```

**Comment by kellyjonbrazil** [comment]
Ah I was actually looking for the iptables output, not the jc output. Let me try to reproduce this on my end.

**Comment by kellyjonbrazil** [comment]
This might be a platform/distro-specific iptables implementation issue since I see the OUTPUT chain in my tests.  Probably something easy to fix. I'll just need some examples of the iptables output you are seeing so I can update the parser.

**Comment by kellyjonbrazil** [comment]
I think I figured out the issue. It looks like the iptables parser was no outputting the last chain. I should have a fix soon.

**Comment by kellyjonbrazil** [comment]
Could you try the latest version (v1.11.7) to see if this is fixed?

```
$ pip3 install --upgrade jc
```

Thanks!

**Comment by swetoast** [comment]
Works perfect , thx :D
