### ISSUE TITLE
ls colors

### ISSUE THREAD

**Issue by T0mK0** [kellyjonbrazil/jc#75]
modern `ls`  colors the output for different types of files and this can produce something like this : 

`  {
    "filename": "\u001b[01;34mtemplate\u001b[0m",
    "flags": "drwxr-xr-x",
    "links": 10,
    "owner": "user",
    "group": "staff",
    "size": 320,
    "date": "Jul 29 16:55"
  },
` 

It would be nice if jc could strip off escape sequences of colors in ls output .

**Comment by kellyjonbrazil** [comment]
I also tried copy/pasting colorized `ls` output from my terminal (macOS terminal) but the color codes did not come over. I might need more information to reproduce this.

Thanks!

**Comment by T0mK0** [comment]
$ alias ls
ls='ls --color'
$ ls -l | jc --ls -p

**Comment by T0mK0** [comment]
ls --color is the default in most linux distros , AFAIK

**Comment by kellyjonbrazil** [comment]
I think it should be `alias ls='ls --color=auto' so this doesn't happen. It looks like that's the default for my linux distros. (CentOS, Fedora, Debian, Ubuntu, etc.). I think the `auto` option helps `ls` to do the right thing when piping data vs. displaying to the terminal.
