### ISSUE TITLE
dig flags should be an array?

### ISSUE THREAD

**Issue by ilyash-b** [kellyjonbrazil/jc#8]
In readme, I've seen that for `dig`, jc returns `"flags": "qr rd ra",`.

I think it would be more semantically correct to return an array - `["qr", "rd", "ra"]`

What do you think?

**Comment by kellyjonbrazil** [comment]
Yeah, was thinking about that too - i'm open to doing that.

**Comment by ilyash-b** [comment]
Your project, your decision :)
I just think it makes sense

**Comment by kellyjonbrazil** [comment]
updated in dev branch
