### ISSUE TITLE
lsblk major/minor

### ISSUE THREAD

**Issue by ilyash-b** [kellyjonbrazil/jc#9]
Readme says `lsblk` output is parsed into `"maj_min": "8:0"`.

Why not into two separate numbers?

**Comment by ilyash-b** [comment]
Not sure if relevant but it is also not the same format as `lsof` - `"device": "8,2"'

**Comment by kellyjonbrazil** [comment]
I didn't know enough about the lsof output to know how users might want that. I'm happy to split it out.

**Comment by ilyash-b** [comment]
Nothing from the top of my head how this particular piece of info from `lsof` should be used. Probably worth waiting for feedback from somebody with real use case.

**Comment by kellyjonbrazil** [comment]
leaving as is for now until we get more feedback on this field
