### ISSUE TITLE
dig TXT with spaces not working

### ISSUE THREAD

**Issue by army1349** [kellyjonbrazil/jc#99]
Parsing of dig output for TXT record that contains spaces does not work.
Cmd:
`dig TXT x.y.z.w.bl.spamcop.net`
dig answer section:
`x.y.z.w.bl.spamcop.net. 2100 IN TXT     "Blocked - see https://www.spamcop.net/bl.shtml?w.z.y.x"`
jc response.data:
`"\"Blocked"`

**Comment by kellyjonbrazil** [comment]
Thanks for reporting this - seems like it should be an easy fix. Let me look into it.

**Comment by kellyjonbrazil** [comment]
This should be fixed now in v1.14.2 now available on pypi vi pip install. Let me know if you run into any other issues.

Thanks!

**Comment by army1349** [comment]
Looks good, thanks!
